### ISSUE TITLE
--filter=[origin/{whatever}] not working as expected

### ISSUE THREAD

**Issue by moogus** [vercel/turbo#6311] opened 2023-10-30 09:19 UTC
### What version of Turborepo are you using?

1.10.16

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Mac

### Summary

**When using any version of Turborepo post `1.5.6` and using the syntax to filter against a remote git branch, no packages are filtered in the mono-repo.**

### System set-up
- node 18.*
- yarn 1.*

Please note the git folder and remote branch is available to the repo. The script executed is as simple as possible, running a single task available in all workspace packages.

### Expected Behavior

**Packages should be filtered to only those that have changed with reference to the remote branch. As seen with version 1.5.6**

```bash:
$ turbo run tsc --filter=[origin/develop] --no-daemon
• Packages in scope: //, @website/account-hooks, @website/component-account-detail-bookings-section
• Running tsc in 3 packages
• Remote caching disabled
@website/account-hooks:tsc: cache miss, executing 78d44c32d6c93f09
@website/component-account-detail-bookings-section:tsc: cache miss, executing d101c034e7f2be48
@website/component-account-detail-bookings-section:tsc: $ tsc
@website/account-hooks:tsc: $ tsc
```

### Scenario _Single package change_
> In a mono-repo with multiple package folders, when a single package in a workspace is altered compared to a remote branch and, a turbo task is configured to run across all packages, filtering the difference between the remote branch and the current `HEAD`.

```json:
"tsc:husky": "turbo run tsc --filter=[origin/develop]"
```

**When running a turbo task across multiple packages with Turborepo version 1.10.16 =>**
```bash:
$ turbo run tsc --filter=[origin/develop] --no-daemon
• Packages in scope: //, 
# Lots of packages listed
...
Running tsc in 388 packages
```

**When running a turbo task across multiple packages with Turborepo version  1.5.6  =>**
```bash:
$ turbo run tsc --filter=[origin/develop] --no-daemon
• Packages in scope: //, @website/component-account-detail-bookings-section
• Running tsc in 2 packages
• Remote caching disabled
@website/component-account-detail-bookings-section:tsc: cache miss, executing d101c034e7f2be48
@website/component-account-detail-bookings-section:tsc: $ tsc
```

### Scenario _Multiple package change_
> In a mono-repo with multiple package folders, when packages in workspaces are altered compared to a remote branch and, a turbo task is configured to run across all packages, filtering the difference between the remote branch and the current `HEAD``

```json:
"tsc:husky": "turbo run tsc --filter=[origin/develop]"
```

**When running a turbo task across multiple packages with Turborepo version 1.10.16 =>**
```bash:
$ turbo run tsc --filter=[origin/develop] --no-daemon
• Packages in scope: //, 
# Lots of packages listed
...
Running tsc in 388 packages
```

**When running a turbo task across multiple packages with Turborepo version 1.5.6 =>**
```bash:
$ turbo run tsc --filter=[origin/develop] --no-daemon
• Packages in scope: //, @website/account-hooks, @website/component-account-detail-bookings-section
• Running tsc in 3 packages
• Remote caching disabled
@website/account-hooks:tsc: cache miss, executing 78d44c32d6c93f09
@website/component-account-detail-bookings-section:tsc: cache miss, executing d101c034e7f2be48
@website/component-account-detail-bookings-section:tsc: $ tsc
@website/account-hooks:tsc: $ tsc
```

**Comment by arlyon** [comment] 2023-11-13 16:56
Hello, just wanted to leave a comment and say I am actively investigating this.

**Comment by arlyon** [comment] 2023-12-01 21:53
I have exhausted about every permutation of local and remote branch config I can think of and have not managed to find a different in implementation between rust and go, neither have I managed to trigger the case you are describing so are you able to get a simple repro that I can investigate?

Both versions delegate to git to calculate diffs between different refs (in this case, `git diff --name-only origin/develop...HEAD`) and report identical file outputs. Please ping me if you are able to produce a repo with some instructions.

Have a nice weekend!

**Comment by moogus** [comment] 2023-12-06 10:46
@arlyon happy to set up a call to show you the issue live. I've emailed you directly

**Comment by moogus** [comment] 2024-01-06 10:16
@arlyon [sample repo](https://github.com/moogus/ISSUE-6311) built to demonstrate the issue using the latest version of turbo. I have noticed if no packages are changed, and a turbo command is called, all packages are checked, too; in `1.5.6`, nothing is run in that scenario.

**Comment by arlyon** [comment] 2024-01-10 17:12
Hey! I am going to take some time with this tomorrow. Thanks for putting it together.

**Comment by arlyon** [comment] 2024-01-19 16:28
So, had some time to look at the repro. When I run yarn install, it produces two extra files (deleting an empty deps field and updating the lock file) which causes all items to build since a 'global dep' has changed. When I commit those files, and run a build against master it filters as expected. Creating a change in one of the files then only triggers a change in one file as expected. 

Hopefully you'll be able to run line-by-line though this script and verify that the behaviour is what you expect

```bash
podman run -it alpine:3.17
apk add yarn nodejs git
git clone https://github.com/moogus/ISSUE-6311.git
cd ISSUE-6311/
yarn
yarn turbo tsc --filter='[origin/main]'
echo '// comment' >> components/component-one/index.ts
yarn turbo tsc --filter='[origin/main]'
```

**Comment by moogus** [comment] 2024-01-24 16:07
Hi @arlyon, thanks for spending the time on this. We don't use docker in the work repo, so I would prefer not to.

I've just cloned the repo I provided, and I'm not getting the issue, so I updated turbo in the work repo, but it's still happening.  I am not quite sure what's going on, I'll see if I can get a more consistent version of the issue.

**Comment by arlyon** [comment] 2024-02-21 18:04
I am going to close this since I can't reproduce the issue. If you are able to get a repro working in a docker container (so that the environment is known) then please add a comment and I will re-open. Thanks anyways for taking the time.

**Closed by arlyon** 2024-02-21 18:04 UTC
Labels: kind: bug, owned-by: turborepo
