### ISSUE TITLE
cannot copy to non-directory DOCKER MACOS

### ISSUE THREAD

**Issue by yovanoc** [vercel/turbo#1997] opened 2022-09-18 17:20 UTC
### What version of Turborepo are you using?

1.4.7

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

On Mac, I tested on windows and this run perfectly, with this repo: https://github.com/yovanoc/turbo-test

if we run `pnpm build:docker` this give:

<img width="1438" alt="image" src="https://user-images.githubusercontent.com/7302317/190920082-9555464d-c48c-47ca-bf6a-b56aadf34e74.png">

### Expected Behavior

Should work on Mac too

### To Reproduce

Just clone the repo and build with docker

**Comment by yovanoc** [comment] 2022-09-19 15:22
@nathanhammond really sorry just push it again was just some tests :/

**Comment by nathanhammond** [comment] 2022-09-19 15:25
@yovanoc Looking now.

**Comment by weyert** [comment] 2022-09-20 12:08
Wondering if it’s related to symlinks; what if you add node_modules to the .dockerignore file to avoid its including it as part of the build context?

**Comment by yovanoc** [comment] 2022-09-20 13:30
Adding node_modules to .dockerignore doesn't solve this issue but yeah I think about symlinks related problem too

**Comment by weyert** [comment] 2022-09-20 14:05
Yeah, not sure, if it also needs to include the Pnpm store directory or nested node_modules. You can also try if it works without Buildkit (DOCKER_BUILDKIT=0)

**Comment by yovanoc** [comment] 2022-09-20 15:17
Yeah I also tested that the other time, and I don't know for others but me I have that:

<img width="903" alt="image" src="https://user-images.githubusercontent.com/7302317/191297550-aebf2d6f-1b98-4a2d-bac2-4dfb4b990199.png">

**Comment by matesmac** [comment] 2022-09-20 22:32
I am having this issue as well. Also on a Mac (M1). Was not yet able to test on a Windows machine but will do. 
This is my (very similar) Dockerfile:

```dockerfile
FROM node:alpine AS base
RUN apk update

# Globally install `turbo`
RUN yarn global add turbo

# Prune the workspace for the `tester` app
FROM base as pruner
WORKDIR /app
COPY . .
RUN turbo prune --scope=@wecoma-lite-tester/tester --docker

FROM base AS builder
WORKDIR /app
COPY .gitignore .gitignore
COPY --from=pruner /app/out/json/ .
COPY --from=pruner /app/out/pnpm-lock.yaml ./pnpm-lock.yaml
COPY --from=pruner /app/out/pnpm-workspace.yaml ./pnpm-workspace.yaml
COPY .npmrc .

# Install the deps needed to build the target
RUN corepack enable
RUN pnpm install

# Copy source code of pruned subworkspace and build
COPY --from=pruner /app/out/full/ .
COPY turbo.json turbo.json
RUN pnpm turbo run build --scope=@wecoma-lite-tester/tester...
```

And the error I get:
![Screenshot 2022-09-21 at 0 29 25](https://user-images.githubusercontent.com/6613604/191376337-3b8cc11c-ab99-4bbf-98a2-31fdcc10296d.jpg)

I already tested all mentioned fix ideas but nothing worked for me.

**Comment by gnohj** [comment] 2022-10-04 00:25
erroring out on same step as well:
![Screenshot from 2022-10-03 20-24-33](https://user-images.githubusercontent.com/25188993/193708809-9c1badbf-ad6f-4c30-8346-f15388a1d2ba.png)

im on linux.

**Comment by Manuelbaun** [comment] 2022-10-05 15:58
I got the same issue: 
turbo: 1.5.5
docker desktop: v4.12.0

**Comment by jennysharps** [comment] 2022-10-07 09:50
I had this same issue & noticed that after running the prune command, each package in `out/full` had a `node_modules` with the expected file structure, but with no actual source code.  I think everything that pnpm symlinked is just missing in the full pruned output. I was able to work around this by doing the following:

```docker
FROM node:16-alpine AS builder
RUN apk update
# Set working directory
WORKDIR /app
RUN corepack enable
COPY . .
RUN pnpm --package=turbo dlx turbo prune --scope=web --docker
# remove all corrupt node_modules & run install to re-populate them
RUN rm -rf /app/out/full/*/*/node_modules
RUN cd /app/out/full && pnpm i

# Add lockfile and package.json's of isolated subworkspace
FROM node:16-alpine AS installer
RUN apk update
RUN corepack enable
WORKDIR /app

# First install the dependencies (as they change less often)
COPY .gitignore .gitignore
COPY --from=builder /app/out/json/ .
COPY --from=builder /app/out/pnpm-lock.yaml ./pnpm-lock.yaml
RUN pnpm install

# Build the project
COPY turbo.json turbo.json
COPY --from=builder /app/out/full/ .
RUN pnpm turbo run build --filter=web...

FROM node:16-alpine AS runner
WORKDIR /app

ENV NODE_ENV production
ENV NEXT_TELEMETRY_DISABLED 1

# Don't run production as root
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs
USER nextjs

# Automatically leverage output traces to reduce image size 
# https://nextjs.org/docs/advanced-features/output-file-tracing
COPY --from=installer --chown=nextjs:nodejs /app/apps/web/.next/standalone ./
COPY --from=installer --chown=nextjs:nodejs /app/apps/web/.next/static ./.next/static

CMD node apps/web/server.js
```

I'm not actually sure what the intention is with the prune command though -- ie:, why does the `with-docker` example copy over just the pruned packages and lockfile before running pnpm install, and THEN copy over the full source code?  Wouldn't the pruned lockfile & package.json just be installing everything already in `out/full` anyway?  Why not just copy over `out/full` and then run install?

**Comment by Suniron** [comment] 2022-10-09 18:31
Same here on Windows 11 > WSL2 (Ubuntu 22.10)

**Comment by John-Hejzlar** [comment] 2022-10-10 16:33
Try add `**/node_modules` to `.dockerignore`

**Comment by John-Hejzlar** [comment] 2022-10-10 17:26
I had this issue too with just `node_modules`, but `**/node_modules` will ignore all node_modules.

**Comment by alitnk** [comment] 2022-10-20 07:11
Had the same issue. It was fixed by adding `**/node_modules` to `.dockerignore`, like @John-Hejzlar said.

**Comment by yusufulusoy** [comment] 2022-11-15 10:41
The solution of copy 'out' dir during build for M1 users:
Add to docker environment:
`DOCKER_DEFAULT_PLATFORM=linux/amd64`

**Comment by sneko** [comment] 2022-11-17 19:04
> Try add `**/node_modules` to `.dockerignore`

Works great. Just watch out, in my case Prettier was changing `**` to `\*\*` and I was not sure if it would be a thing... it is ;) (use `.prettierignore` and list `**/.dockerignore`)

**Comment by emilbryggare** [comment] 2022-12-15 14:38
Just reproduced this on the with-docker example when using **pnpm**. It works great when using **yarn**. Adding the details if it helps to debug.

### What version of Turborepo are you using?
1.6.3

### What package manager are you using / does the bug impact?
pnpm

### What operating system are you using?
Mac M1


### To Reproduce
`npx degit vercel/turbo/examples/with-docker with-docker\ncd with-docker`

Update Dockerfile to use pnpm instead of yarn:
```
# This Dockerfile is copy-pasted into our main docs at /docs/handbook/deploying-with-docker.
# Make sure you update both files!

FROM node:alpine AS builder
# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
RUN apk add --no-cache libc6-compat
RUN apk update
# Set working directory
WORKDIR /app
RUN yarn global add turbo pnpm
COPY . .
RUN turbo prune --scope=web --docker

# Add lockfile and package.json's of isolated subworkspace
FROM node:alpine AS installer
RUN apk add --no-cache libc6-compat
RUN apk update
WORKDIR /app

# First install the dependencies (as they change less often)
RUN yarn global add pnpm
COPY .gitignore .gitignore
COPY --from=builder /app/out/json/ .
COPY --from=builder /app/out/pnpm-lock.yaml ./pnpm-lock.yaml
RUN pnpm install

# Build the project
COPY --from=builder /app/out/full/ .
COPY turbo.json turbo.json
RUN pnpm turbo run build --filter=web...

FROM node:alpine AS runner
WORKDIR /app

# Don't run production as root
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs
USER nextjs

COPY --from=installer /app/apps/web/next.config.js .
COPY --from=installer /app/apps/web/package.json .

# Automatically leverage output traces to reduce image size
# https://nextjs.org/docs/advanced-features/output-file-tracing
COPY --from=installer --chown=nextjs:nodejs /app/apps/web/.next/standalone ./
COPY --from=installer --chown=nextjs:nodejs /app/apps/web/.next/static ./apps/web/.next/static

CMD node apps/web/server.js
```
Build image
```
rm yarn.lock
pnpm install
docker build  -f apps/web/Dockerfile .
```

**Comment by productdevbook** [comment] 2023-01-19 06:54
same problem linux

**Comment by wlcharlie** [comment] 2023-02-08 09:44
> I had this issue too with just `node_modules`, but `**/node_modules` will ignore all node_modules.

same issue on M1 and this work

**Comment by abetoots** [comment] 2023-02-20 05:52
encountered the same with WSL2 Ubuntu. `**/node_modules` fixed it for me

**Comment by xencodes** [comment] 2023-03-05 01:47
solved by update `node_modules` to `**/node_modules` in .dockerignore 😄 

but, go the next lined up error: `failed to compute cache key: "/app/apps/web/.next/standalone" not found: not found`

**Comment by XavierGeerinck** [comment] 2023-03-13 15:22
> Try add `**/node_modules` to `.dockerignore`

Lifesaver!

**Comment by cornwe19** [comment] 2023-03-17 22:25
@xencodes I ran into the same thing, I think the example build assumes you're using standalone output https://nextjs.org/docs/advanced-features/output-file-tracing#automatically-copying-traced-files

**Comment by ARMATAV** [comment] 2023-04-21 03:37
> Yeah, not sure, if it also needs to include the Pnpm store directory or nested node_modules. You can also try if it works without Buildkit (DOCKER_BUILDKIT=0)

It works with `DOCKER_BUILDKIT=0`, but slow

**Comment by ARMATAV** [comment] 2023-04-24 02:44
https://github.com/vercel/turbo/discussions/3346#discussioncomment-5703415

Yeah it's the symlinks

**Comment by anthonyshew** [comment] 2023-12-06 04:44
Looks like we have some answers above that solve these Docker configuration issues. Will close!

**Closed by anthonyshew** 2023-12-06 04:44 UTC
Labels: kind: bug, owned-by: turborepo
