### ISSUE TITLE
[turborepo] `turbo build` hangs on linux

### ISSUE THREAD

**Issue by alvesvaren** [vercel/turbo#5908] opened 2023-09-08 13:37 UTC
### What version of Turborepo are you using?

1.10.13

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Linux

### Describe the Bug

Turbo hangs on all tasks for me, (at least for ~5 minutes, haven't waited longer than that).

I tried v1.9.5 and with that one it runs basically instantly.

### Expected Behavior

Turbo tasks run as usual

### To Reproduce

- Create a new from the basic template
- Try to run any task (`turbo build`)
- It gets stuck

<sub>[TURBO-1398](https://linear.app/vercel/issue/TURBO-1398/[turborepo]-turbo-build-hangs-on-linux)</sub>

**Comment by gsoltis** [comment] 2023-09-08 20:27
I was not able to reproduce this, using Ubuntu 20.04, pnpm, and `turbo@1.10.13`. Can you provide more details? What do the logs look like, can you run with `-vvv`?

All works as expected:
```
npx -y create-turbo@1.1013 my-turborepo pnpm
cd my-turborepo
pnpm build
```

Do you have different steps to reproduce the issue?

**Comment by nathanhammond** [comment] 2023-09-08 23:59
Can you try pinning to 1.10.3?

**Comment by alvesvaren** [comment] 2023-09-09 09:37
Installed 1.10.3 and tried again with `-vvv`:
```
2023-09-09T11:32:02.166+0200 [DEBUG] turborepo_lib::shim: Global turbo version: 1.10.3
2023-09-09T11:32:02.167+0200 [DEBUG] turborepo_lib::shim: No local turbo binary found at: /home/alve/dev/project-name/node_modules/turbo-linux-64/bin/turbo
2023-09-09T11:32:02.167+0200 [DEBUG] turborepo_lib::shim: No local turbo binary found at: /home/alve/dev/project-name/node_modules/turbo/node_modules/turbo-linux-64/bin/turbo
2023-09-09T11:32:02.167+0200 [DEBUG] turborepo_lib::shim: Repository Root: /home/alve/dev/project-name
╭────────────────────────────────────────────────────────────────────────╮
│                                                                        │
│                  Update available v1.10.3 ≫ v1.10.13                   │
│    Changelog: https://github.com/vercel/turbo/releases/tag/v1.10.13    │
│               Run "npx @turbo/codemod update" to update                │
│                                                                        │
│      Follow @turborepo for updates: https://twitter.com/turborepo      │
╰────────────────────────────────────────────────────────────────────────╯
2023-09-09T11:32:02.167+0200 [DEBUG] turborepo_lib::shim: Running command as global turbo
2023-09-09T11:32:02.167+0200 [TRACE] log: registering event source with poller: token=Token(2147483649), interests=READABLE
2023-09-09T11:32:02.168+0200 [DEBUG] turborepo_lib::cli: pkg_inference_root set to ""
2023-09-09T11:32:02.169+0200 [TRACE] turborepo_lib::execution_state: Found pnpm as package manager
2023-09-09T11:32:02.169+0200 [DEBUG] turbo: Found go binary at "/home/alve/.local/share/pnpm/global/5/.pnpm/turbo@1.10.3/node_modules/turbo/bin/go-turbo"
2023-09-09T11:32:02.169+0200 [TRACE] turbo: Invoking go binary with {"api_client_config":{"token":null,"team_id":null,"team_slug":null,"api_url":"https://vercel.com/api","use_preflight":false,"timeout":20},"package_manager":"pnpm","cli_args":{"api":null,"color":false,"cpu_profile":null,"cwd":"/home/alve/dev/project-name","heap":null,"login":null,"no_color":false,"preflight":false,"remote_cache_timeout":null,"team":null,"token":null,"trace":null,"verbosity":3,"test_run":false,"command":{"Run":{"cache_dir":null,"cache_workers":10,"concurrency":null,"continue_execution":false,"dry_run":null,"single_package":false,"filter":[],"force":null,"framework_inference":true,"global_deps":[],"graph":null,"env_mode":"Infer","ignore":[],"include_dependencies":false,"no_cache":false,"no_daemon":false,"no_deps":false,"output_logs":null,"only":false,"parallel":false,"pkg_inference_root":"","profile":null,"remote_only":false,"scope":[],"since":null,"summarize":null,"log_prefix":null,"tasks":["build"],"pass_through_args":[],"experimental_space_id":null}}}}
2023-09-09T11:32:02.173+0200 [DEBUG] turbo: build tag: rust
2023-09-09T11:32:02.196+0200 [DEBUG] turbo: running in daemon mode
2023-09-09T11:32:02.196+0200 [DEBUG] turbo: global hash env vars: vars=[]
2023-09-09T11:32:02.424+0200 [DEBUG] turbo: global hash: value=ec8aba6e703c91fa
2023-09-09T11:32:02.424+0200 [DEBUG] turbo: local cache folder: path=""
** gets stuck here for at least 5 minutes**
```

I can't reproduce it when creating a new repo, so it's probably something with how I've set it up (nothing weird, just a normal monorepo with a few apps/packages)

**Comment by alvesvaren** [comment] 2023-09-09 09:40
`turbo.json` from my repository that doesn't work:
```
{
  "$schema": "https://turbo.build/schema.json",
  "globalDependencies": ["**/.env.*local"],
  "pipeline": {
    "build": {
      "dependsOn": ["^build"],
      "outputs": [".next/**", "!.next/cache/**"]
    },
    "lint": {},
    "dev": {
      "cache": false,
      "persistent": true
    },
    "db:generate": { "cache": false },
    "db:push": { "cache": false },
    "db:deploy": { "cache": false },
    "db:migrate": { "cache": false }
  }
}
```

I am on arch with node v18.17.1

**Comment by nathanhammond** [comment] 2023-09-11 01:49
Well, since we're here, [in 1.10 we shipped better handling for `.env` files](https://turbo.build/repo/docs/core-concepts/caching/environment-variable-inputs#env-files).

Your `turbo.json` should likely look like this:
```
{
  "$schema": "https://turbo.build/schema.json",
  "globalDotEnv": [".env"],
  "pipeline": {
    "build": {
      "dotEnv": [".env.production.local", ".env.local", ".env.production", ".env"],
      "dependsOn": ["^build"],
      "outputs": [".next/**", "!.next/cache/**"]
    },
    "lint": {},
    "dev": {
      "cache": false,
      "persistent": true
    },
    "db:generate": { "cache": false },
    "db:push": { "cache": false },
    "db:deploy": { "cache": false },
    "db:migrate": { "cache": false }
  }
}
```

That (shouldn't be) related to this change, but with you patiently getting us more information I'm pleased that we can at least help with one thing while looking for the other issue. 😅

One last test: can you try pinning to 1.9.5?

**Comment by nathanhammond** [comment] 2023-09-11 02:59
Actually, looking at this again, `"globalDependencies": ["**/.env.*local"],` is triggering a full walk of the directory. Dropping that plus moving to 1.10.3 _may_ be a temporary workaround while we address the root cause.

**Comment by alvesvaren** [comment] 2023-09-11 07:33
Tried with your json file, but it didn't seem to help, still stuck running `turbo db:generate`:
```
2023-09-11T09:28:41.257+0200 [DEBUG] turborepo_lib::shim: Global turbo version: 1.10.3
2023-09-11T09:28:41.258+0200 [DEBUG] turborepo_lib::shim: No local turbo binary found at: /home/alve/dev/projectname/node_modules/turbo-linux-64/bin/turbo
2023-09-11T09:28:41.258+0200 [DEBUG] turborepo_lib::shim: No local turbo binary found at: /home/alve/dev/projectname/node_modules/turbo/node_modules/turbo-linux-64/bin/turbo
2023-09-11T09:28:41.258+0200 [DEBUG] turborepo_lib::shim: Repository Root: /home/alve/dev/projectname
╭────────────────────────────────────────────────────────────────────────╮
│                                                                        │
│                  Update available v1.10.3 ≫ v1.10.13                   │
│    Changelog: https://github.com/vercel/turbo/releases/tag/v1.10.13    │
│               Run "npx @turbo/codemod update" to update                │
│                                                                        │
│      Follow @turborepo for updates: https://twitter.com/turborepo      │
╰────────────────────────────────────────────────────────────────────────╯
2023-09-11T09:28:41.258+0200 [DEBUG] turborepo_lib::shim: Running command as global turbo
2023-09-11T09:28:41.258+0200 [TRACE] log: registering event source with poller: token=Token(2147483649), interests=READABLE
2023-09-11T09:28:41.259+0200 [DEBUG] turborepo_lib::cli: pkg_inference_root set to "apps/composer"
2023-09-11T09:28:41.260+0200 [TRACE] turborepo_lib::execution_state: Found pnpm as package manager
2023-09-11T09:28:41.260+0200 [DEBUG] turbo: Found go binary at "/home/alve/.local/share/pnpm/global/5/.pnpm/turbo@1.10.3/node_modules/turbo/bin/go-turbo"
2023-09-11T09:28:41.260+0200 [TRACE] turbo: Invoking go binary with {"api_client_config":{"token":null,"team_id":null,"team_slug":null,"api_url":"https://vercel.com/api","use_preflight":false,"timeout":20},"package_manager":"pnpm","cli_args":{"api":null,"color":false,"cpu_profile":null,"cwd":"/home/alve/dev/projectname","heap":null,"login":null,"no_color":false,"preflight":false,"remote_cache_timeout":null,"team":null,"token":null,"trace":null,"verbosity":3,"test_run":false,"command":{"Run":{"cache_dir":null,"cache_workers":10,"concurrency":null,"continue_execution":false,"dry_run":null,"single_package":false,"filter":[],"force":null,"framework_inference":true,"global_deps":[],"graph":null,"env_mode":"Infer","ignore":[],"include_dependencies":false,"no_cache":false,"no_daemon":true,"no_deps":false,"output_logs":null,"only":false,"parallel":false,"pkg_inference_root":"apps/web","profile":null,"remote_only":false,"scope":[],"since":null,"summarize":null,"log_prefix":null,"tasks":["db:generate"],"pass_through_args":[],"experimental_space_id":null}}}}
2023-09-11T09:28:41.263+0200 [DEBUG] turbo: build tag: rust
2023-09-11T09:28:41.285+0200 [DEBUG] turbo: Using apps/web as a basis for selecting packages
2023-09-11T09:28:41.285+0200 [DEBUG] turbo: global hash env vars: vars=[]
2023-09-11T09:28:41.285+0200 [DEBUG] turbo: global hash: value=beb986baeb38a1b8
2023-09-11T09:28:41.285+0200 [DEBUG] turbo: local cache folder: path=""
```

This was with 1.10.3. Also tried removing "globalDotEnv" but no difference.

**Comment by alvesvaren** [comment] 2023-09-11 07:37
I also got this a few times when running the commands:
```
2023-09-11T09:35:30.975+0200 [DEBUG] turbo.TurbodClient: starting turbod binary /home/alve/.local/share/pnpm/global/5/.pnpm/turbo@1.10.3/node_modules/turbo/bin/turbo
2023-09-11T09:35:31.976+0200 [DEBUG] turbo.TurbodClient: starting turbod binary /home/alve/.local/share/pnpm/global/5/.pnpm/turbo@1.10.3/node_modules/turbo/bin/turbo
2023-09-11T09:35:32.976+0200 [DEBUG] turbo.TurbodClient: starting turbod binary /home/alve/.local/share/pnpm/global/5/.pnpm/turbo@1.10.3/node_modules/turbo/bin/turbo
2023-09-11T09:35:33.976+0200 [WARN]  turbo: :
  warning=
  | failed to contact turbod. Continuing in standalone mode: connection to turbo daemon process failed.
  |     To quickly resolve the issue, try running:
  |     - $ turbo daemon clean
  | 
  |     To debug further - please ensure the following:
  |     - the process identified by the pid in the file at /tmp/turbod/5d0b08731af479bc/turbod.pid is not running, and remove /tmp/turbod/5d0b08731af479bc/turbod.pid
  |     - check the logs at /home/alve/.local/share/turborepo/logs/5d0b08731af479bc-semanttic-composer-mono.log
  |     - the unix domain socket at /tmp/turbod/5d0b08731af479bc/turbod.sock has been removed
  | 
  |     You can also run without the daemon process by passing --no-daemon
  
 WARNING  failed to contact turbod. Continuing in standalone mode: connection to turbo daemon process failed.
        To quickly resolve the issue, try running:
        - $ turbo daemon clean

        To debug further - please ensure the following:
        - the process identified by the pid in the file at /tmp/turbod/5d0b08731af479bc/turbod.pid is not running, and remove /tmp/turbod/5d0b08731af479bc/turbod.pid
        - check the logs at /home/alve/.local/share/turborepo/logs/5d0b08731af479bc-semanttic-composer-mono.log
        - the unix domain socket at /tmp/turbod/5d0b08731af479bc/turbod.sock has been removed

        You can also run without the daemon process by passing --no-daemon
  ```
  
None of the specified .pid-files exist and running `turbo daemon clean` doesn't fix it, however running with --no-daemon works as it did before (gets stuck)

**Comment by consoleaf** [comment] 2023-09-29 08:51
Hi! I have a similar issue (Turbo just hangs), and after a manual "bisect" over recent versions, for me the issue is introduced in v1.10.2. Please let me know if I can help investigate this further if needed

**Comment by mpereira** [comment] 2023-10-03 01:57
I'm also seeing this, on macOS.

```
$ ./node_modules/turbo-darwin-arm64/bin/turbo -vvv run build --filter=<app>
2023-10-03T03:53:34.790+0200 [DEBUG] turborepo_lib::shim: Global turbo version: 1.10.14
2023-10-03T03:53:34.798+0200 [DEBUG] turborepo_lib::shim: Local turbo path: <REDACTED>/node_modules/turbo-darwin-arm64/bin/turbo
2023-10-03T03:53:34.798+0200 [DEBUG] turborepo_lib::shim: Local turbo version: 1.10.14
2023-10-03T03:53:34.798+0200 [DEBUG] turborepo_lib::shim: Repository Root: <REDACTED>
2023-10-03T03:53:34.798+0200 [DEBUG] turborepo_lib::shim: Running local turbo binary in <REDACTED>/node_modules/turbo-darwin-arm64/bin/turbo

2023-10-03T03:53:34.798+0200 [DEBUG] turborepo_lib::shim: supports_skip_infer_and_single_package true
2023-10-03T03:53:34.801+0200 [DEBUG] turborepo_lib::shim: Global turbo version: 1.10.14
2023-10-03T03:53:34.804+0200 [DEBUG] turborepo_lib::cli: pkg_inference_root set to ""
2023-10-03T03:53:34.806+0200 [TRACE] turborepo_lib::execution_state: Found npm as package manager
2023-10-03T03:53:34.807+0200 [DEBUG] turbo: Found go binary at "<REDACTED>/node_modules/turbo-darwin-arm64/bin/go-turbo"
2023-10-03T03:53:34.824+0200 [TRACE] turbo: Invoking go binary with {"api_client_config":{"token":null,"team_id":null,"team_slug":null,"api_url":"https://vercel.com/api","use_preflight":false,"timeout":20},"spaces_api_client_config":{"token":null,"team_id":null,"team_slug":null,"api_url":"https://vercel.com/api","use_preflight":false,"timeout":20},"package_manager":"npm","cli_args":{"api":null,"color":false,"cpu_profile":null,"cwd":"<REDACTED>","heap":null,"login":null,"no_color":false,"preflight":false,"remote_cache_timeout":null,"team":null,"token":null,"trace":null,"verbosity":3,"test_run":false,"command":{"Run":{"cache_dir":null,"cache_workers":10,"concurrency":null,"continue_execution":false,"dry_run":null,"single_package":false,"filter":["<REDACTED>"],"force":null,"framework_inference":true,"global_deps":[],"graph":null,"env_mode":"Infer","ignore":[],"include_dependencies":false,"no_cache":false,"no_daemon":false,"no_deps":false,"output_logs":null,"log_order":"auto","only":false,"parallel":false,"pkg_inference_root":"","profile":null,"remote_only":false,"scope":[],"since":null,"summarize":null,"log_prefix":"auto","tasks":["build"],"pass_through_args":[],"experimental_space_id":null,"experimental_rust_codepath":false}}}}
2023-10-03T03:53:34.889+0200 [DEBUG] turbo: build tag: rust
2023-10-03T03:53:34.914+0200 [DEBUG] turbo: running in daemon mode
2023-10-03T03:53:34.917+0200 [DEBUG] turbo: global hash env vars: vars=[]
2023-10-03T03:53:34.926+0200 [DEBUG] turbo: global hash: value=374b21a612331788
2023-10-03T03:53:34.926+0200 [DEBUG] turbo: local cache folder: path=""
<...hangs...>
```

**Comment by gsoltis** [comment] 2023-10-04 21:06
@alvesvaren Do you have multiple workspaces with the `db:generate` script defined?  Is there a particular workspace that exhibits the behavior when you run `turbo db:generate`? Or does it happen when you try it with any of them?

**Comment by alvesvaren** [comment] 2023-10-10 08:47
It's just one package that has that script defined. It hangs when I run any pipeline, not just db:generate, for example when running `turbo build`.

We have refactored a lot and created a new turborepo, which fixed it in our project, but the old turborepo is still broken

**Comment by gsoltis** [comment] 2023-10-10 20:14
Ok, I'm going to close this as it seems like you have a working setup. Happy to reopen if you've got something from the old setup that we can repro though. It sounds like there's either some large directory tree that's being traversed, or some filesystem oddity.

**Closed by gsoltis** 2023-10-10 20:14 UTC
Labels: kind: bug, needs: reproduction, linear: turbo, owned-by: turborepo
