### ISSUE TITLE
Devcontainer node startup will automatically interrupt child process

### ISSUE THREAD

**Issue by As-wangyu** [vercel/turbo#7427] opened 2024-02-20 03:38 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

none

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Windows

### Which canary version will you have in your reproduction?

1.12.4

### Describe the Bug

Start the node in the development container environment. After successful startup, a message "turbo repo_lib:: process:: child: child process exited normally" will be reported in the log
![微信图片_20240220100538](https://github.com/vercel/turbo/assets/57214174/5ce622ae-1ca5-442f-ba38-badde5bb98f2)

### Expected Behavior

Will not automatically interrupt in the development container environment

### To Reproduce

Start the node in the development container environment. After successful startup, a message "turbo repo_lib:: process:: child: child process exited normally" will be reported in the log
![微信图片_20240220100538](https://github.com/vercel/turbo/assets/57214174/5ce622ae-1ca5-442f-ba38-badde5bb98f2)

**Comment by anthonyshew** [comment] 2024-02-20 03:47
Please provide a reproduction.

**Comment by As-wangyu** [comment] 2024-02-20 06:25
> Please provide a reproduction.

[Uploading frontend.zip…]()
After the code enters development container mode, executing pnpm dev can reproduce the problem

**Comment by chris-olszewski** [comment] 2024-02-20 16:55
This is a dupe of #7279. 

Vite shuts down immediately if `stdin` is closed and we close `stdin` for all non-persistent tasks so the tasks don't wait on input they'll never receive. If you mark your task with [`"persistent": true`](https://turbo.build/repo/docs/reference/configuration#persistent), then `stdin` will be kept open.

**Closed by chris-olszewski** 2024-02-20 16:55 UTC
Labels: kind: bug, needs: triage, owned-by: turborepo

**Comment by As-wangyu** [comment] 2024-02-22 01:27
> Contributor

Thank you very much for your answer
