### ISSUE TITLE
[turborepo] Unrelated projects getting built because of dependsOn

### ISSUE THREAD

**Issue by dstoyanoff** [vercel/turbo#2988] opened 2022-12-13 11:46 UTC
### What version of Turborepo are you using?

1.6.3

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Mac

### Describe the Bug

I have a monorepo using yarn workspaces (yarn v1). At the root package json I have the usual commands:
```
    "build": "turbo run build",
    "test": "turbo run test",
    "deploy:dev": "turbo run deploy:dev"
```
The issue is with the 3rd command. I have `deploy:dev` defined in only one package in the repo and this is the config in `turbo.json`:

```
{
  "$schema": "https://turbo.build/schema.json",
  "pipeline": {
    "build": {
      "inputs": ["src/**/*.tsx", "src/**/*.ts"],
      "outputs": [".next/**", "dist/**"]
    },
    "test": {
      "dependsOn": ["build"],
      "inputs": ["src/**/*.tsx", "src/**/*.ts"],
      "outputs": []
    },
    "deploy:dev": {
      "dependsOn": ["build"],
      "inputs": ["src/**/*.tsx", "src/**/*.ts"],
      "outputs": []
    }
  }
}
```

When I execute `yarn deploy:dev`, all my packages' build command is called and only after that the `deploy:dev`. This app does not have any dependency on another app, but just on libs (not buildable, so not included in turbo). If I switch to `^build`, nothing gets executed before the deploy. Is this a bug or am I doing something wrong?

### Expected Behavior

Only the current package should get build.

### To Reproduce

-

**Comment by dobesv** [comment] 2023-01-18 06:04
`turbo` supports "virtual" pipelines so even if the pipeline does not have a matching script on a package it still uses it to decide what to run.

So for example, it'll try to run `deploy:dev` on each package.  It sees that `deploy:dev` depends on `build` so it runs that first.

This can come in handy sometimes but sometimes it's confusing.  Probably be nice if this behavior could be controlled better.

If you want to avoid running it for every package you can tell turbo which packages you want, e.g. `turbo run --filter=mypackage... deploy:dev`

You can also define targets for a single package, like `"package#deploy:dev": { "dependsOn": ... }`

**Comment by ccremer** [comment] 2023-04-22 14:15
I was also stumbling upon a similar issue. In my case I was using the `--filter` option, but I was using it incorrectly.
In case someone wraps their head around this ;)

wrong:
`turbo --filter='my-package' run e2e`
correct:
`turbo run --filter='my-package' e2e`

**Comment by arlyon** [comment] 2024-03-11 18:51
I am going to close this issue due to age. We have rewritten turbo entirely so older issues are likely irrelevant. It seems like the behaviour you are describing is working as intended now. Depending on `build` will run all the build tasks before this one, while `^build` will run the build task of this package and its dependencies.

**Closed by arlyon** 2024-03-11 18:51 UTC
Labels: kind: bug, owned-by: turborepo
