### ISSUE TITLE
[turborepo] Typescript Error: Internal package not found, (ts 2307), but is clearly installed and working.  

### ISSUE THREAD

**Issue by williamlmao** [vercel/turbo#3856] opened 2023-02-17 05:28 UTC
### What version of Turborepo are you using?

^1.6.3

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

I have a ui library in packages/ui and then a docs site in apps/docs. Every now and then, I get this typescript error. 

```
Cannot find module 'chimera-tw' or its corresponding type declartions. ts(2307)
```
![SCR-20230217-ik](https://user-images.githubusercontent.com/55903529/219556294-eba34eba-4b10-438a-a443-628c12cf2e3f.png)
![SCR-20230217-he](https://user-images.githubusercontent.com/55903529/219556291-2aa4cdc1-d426-45c7-8b76-e3dff1d1337f.png)

**Some weird things about this error:** 
- In the two screenshots above, nothing has changed with the codebase. I simply restarted the ts server, took a screen shot. Then ran `pnpm run dev`, the error came back, and I took another screen shot.
- Sometimes the error will briefly go away on its own.
- Build works fine. Dev works fine. The package is clearly installed, I can see it in node modules and components import just fine. 
- Maybe not related to this error, but import cost can't seem to calculate the cost of the internal package. I am assumign this has to do with the symlink. 

**I have tried the following, but it keeps coming back:** 
- `pnpm run clean`, then pnpm install 
- deleting node modules and package.lock and then reinstalling
- restarting vs code

### Expected Behavior

Importing an internal package to behave normally without error

### To Reproduce

`git clone https://github.com/williamlmao/chimera-tw.git`
`pnpm run dev`

### Reproduction Repo

https://github.com/williamlmao/chimera-tw

**Comment by williamlmao** [comment] 2023-02-19 02:02
Update: published the UI package on NPM and have had no issues importing it into other repos. This issue only occurs within the turborepo.

**Comment by nathanhammond** [comment] 2023-03-14 08:35
Intermittent failures like this are not going to be related to Turborepo: we don't do anything for integration into package managers, editors, or TypeScript. Even when executing scripts we just immediately defer to the scripts as you have them defined.

This is likely an intermediate state in your editor that is failing, triggered by trying to monitor the state on disk while things are changing during a build.

I'm closing this because there's nothing obvious that we can do on our side to make this experience better. If you figure out how to configure your editor in a way that this experience improves, let us know!

**Closed by nathanhammond** 2023-03-14 08:35 UTC
Labels: kind: bug, area: turborepo, needs: triage

**Comment by leonard-henriquez** [comment] 2023-03-20 15:16
@nathanhammond any idea if the issue is due to Typescript or VS Code ?

**Comment by groyDoorvest** [comment] 2024-11-19 15:31
@williamlmao did you find the cause of your issue? I seeing the same thing locally. Command+click on the dependancy finds it properly, but eslint is saying the import is not found
