### ISSUE TITLE
[turbopack] Cannot find module 'next/dist/server/node-polyfill-fetch'

### ISSUE THREAD

**Issue by minkgkyaw9899** [vercel/turbo#4994] opened 2023-05-17 07:18 UTC
### What version of Turborepo are you using?

1.9.6

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Linux

### Describe the Bug

Error: Cannot find module 'next/dist/server/node-polyfill-fetch'

How to solve this issues, I deleted the node_modules folder,  ran pnpm install, pnpm dev and the error is still there
My OS is Ubuntu 22.10

### Expected Behavior

i want to run `next dev --turbo` command without error

### To Reproduce

full error 

Error: Cannot find module 'next/dist/server/node-polyfill-fetch'

Debug info:
- Error: Cannot find module 'next/dist/server/node-polyfill-fetch'
      [at /home/black/dev/personal/multi-vendors-eshop/apps/web-client/.next/server/app/chunks/ssr/[next]_polyfill_app-polyfills.ts_7a8048._.js:14:15]
      [at Object.<anonymous> (/home/black/dev/personal/multi-vendors-eshop/apps/web-client/.next/server/app/chunks/ssr/[next]_polyfill_app-polyfills.ts_7a8048._.js:17:3)]
      [at [next]/polyfill/app-polyfills.ts (ecmascript, ssr) (/home/black/dev/personal/multi-vendors-eshop/apps/web-client/.next/server/app/chunks/ssr/[next]_polyfill_app-polyfills.ts_7a8048._.js:35:3)]
      [at /home/black/dev/personal/multi-vendors-eshop/apps/web-client/.next/server/app/chunks/ssr/[next]_entry_app-renderer.tsx_5392c9._.js:496:21]
      [at runModuleExecutionHooks (/home/black/dev/personal/multi-vendors-eshop/apps/web-client/.next/server/app/chunks/ssr/[next]_entry_app-renderer.tsx_5392c9._.js:542:3)]
      [at instantiateModule (/home/black/dev/personal/multi-vendors-eshop/apps/web-client/.next/server/app/chunks/ssr/[next]_entry_app-renderer.tsx_5392c9._.js:494:3)]
      [at getOrInstantiateModuleFromParent (/home/black/dev/personal/multi-vendors-eshop/apps/web-client/.next/server/app/chunks/ssr/[next]_entry_app-renderer.tsx_5392c9._.js:587:10)]
      [at esmImport (/home/black/dev/personal/multi-vendors-eshop/apps/web-client/.next/server/app/chunks/ssr/[next]_entry_app-renderer.tsx_5392c9._.js:217:18)]
      [at /home/black/dev/personal/multi-vendors-eshop/apps/web-client/.next/server/app/chunks/ssr/[next]_entry_app-renderer.tsx_5caf99._.js:27:109]
      [at [next]/entry/app-renderer.tsx/(COMPONENT_0)/[project]/src/app/page.tsx (ecmascript, client chunks)/(COMPONENT_1)/[project]/src/app/layout.tsx (ecmascript, client chunks)/(METADATA_2)/[project]/src/app/favicon.ico/(IMAGE)/[project]/src/app/favicon.ico (static) (structured image object, ecmascript)/(BOOTSTRAP)/[next]/entry/app/hydrate.tsx (ecmascript, chunk group files) (ecmascript, ssr) (/home/black/dev/personal/multi-vendors-eshop/apps/web-client/.next/server/app/chunks/ssr/[next]_entry_app-renderer.tsx_5caf99._.js:313:3)]
      [at /home/black/dev/personal/multi-vendors-eshop/apps/web-client/.next/server/app/chunks/ssr/[next]_entry_app-renderer.tsx_5392c9._.js:496:21]
      [at runModuleExecutionHooks (/home/black/dev/personal/multi-vendors-eshop/apps/web-client/.next/server/app/chunks/ssr/[next]_entry_app-renderer.tsx_5392c9._.js:542:3)]
      [at instantiateModule (/home/black/dev/personal/multi-vendors-eshop/apps/web-client/.next/server/app/chunks/ssr/[next]_entry_app-renderer.tsx_5392c9._.js:494:3)]
      [at getOrInstantiateRuntimeModule (/home/black/dev/personal/multi-vendors-eshop/apps/web-client/.next/server/app/chunks/ssr/[next]_entry_app-renderer.tsx_5392c9._.js:1433:10)]
      [at Object.registerChunk (/home/black/dev/personal/multi-vendors-eshop/apps/web-client/.next/server/app/chunks/ssr/[next]_entry_app-renderer.tsx_5392c9._.js:1538:11)]
      [at registerChunk (/home/black/dev/personal/multi-vendors-eshop/apps/web-client/.next/server/app/chunks/ssr/[next]_entry_app-renderer.tsx_5392c9._.js:1497:18)]
      [at <anonymous>]
      [at /home/black/dev/personal/multi-vendors-eshop/apps/web-client/.next/server/app/chunks/ssr/[next]_entry_app-renderer.tsx_5392c9._.js:1587:18]
      [at Object.<anonymous> (/home/black/dev/personal/multi-vendors-eshop/apps/web-client/.next/server/app/chunks/ssr/[next]_entry_app-renderer.tsx_5392c9._.js:1588:3)]
      [at Module._compile (node:internal/modules/cjs/loader:1254:14)]
      [at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)]
      [at Module.load (node:internal/modules/cjs/loader:1117:32)]
      [at Module._load (node:internal/modules/cjs/loader:958:12)]
      [at Module.require (node:internal/modules/cjs/loader:1141:19)]
      [at require (node:internal/modules/cjs/helpers:110:18)]
      [at Object.<anonymous> (/home/black/dev/personal/multi-vendors-eshop/apps/web-client/.next/server/app/chunks/ssr/[next]_entry_app-renderer.tsx_20d435._.js:18:1)]
      [at Module._compile (node:internal/modules/cjs/loader:1254:14)]
      [at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)]
      [at Module.load (node:internal/modules/cjs/loader:1117:32)]
      [at Module._load (node:internal/modules/cjs/loader:958:12)]
      [at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)]
      [at node:internal/main/run_main_module:23:47]

Status: exit status: 0

**Comment by NicholasLYang** [comment] 2023-05-17 17:50
Hi @minkgkyaw9899, this seems to be a turbopack issue, as `next dev --turbo` runs next with turbopack. I'll change the label accordingly if that's indeed the case.

**Comment by padmaia** [comment] 2023-09-20 22:52
This one should have been fixed with Next.js v13.4+. If you are still experiencing issues, please open an issue with a reproduction in the Next.js repo.

**Closed by padmaia** 2023-09-20 22:52 UTC
Labels: kind: bug, needs: triage, owned-by: web-tooling
