### ISSUE TITLE
[turborepo] Arbitrary workspace task keys overwrite root task keys of the same name

### ISSUE THREAD

**Issue by jdjkelly** [vercel/turbo#5847] opened 2023-08-31 14:09 UTC
### What version of Turborepo are you using?

1.10.13

### What package manager are you using / does the bug impact?

Yarn v2/v3 (node_modules linker only)

### What operating system are you using?

Mac

### Describe the Bug

Arbitrary workspace task keys unexpectedly overwrite root task behaviors. 

For example:

```
{
  "$schema": "https://turbo.build/schema.json",
  "globalEnv": ["NODE_ENV"],
  "pipeline": {
    "build": {
      "dependsOn": ["^build"]
    },
    "test": {
      "dependsOn": ["^build"]
    },
    "jobs#test": {
      "dependsOn": ["db#test"]
    },
}
```

Inspecting the pipeline graph will show that `jobs#test` won't build its dependencies. 

### Expected Behavior

Although this behavior makes sense - arbitrary workspace tasks declaring a key simply overwrite the root task key of the same name - the expected behavior for me at least was that the arbitrary workspace task was extending all of the same behaviors as the root task.

I expected that `^build` would be merged into the arbirtary workspace task's `dependsOn` key.

### To Reproduce

Assuming a workspace named jobs and one named db, where db is a dependency of db:

```
{
  "$schema": "https://turbo.build/schema.json",
  "globalEnv": ["NODE_ENV"],
  "pipeline": {
    "build": {
      "dependsOn": ["^build"]
    },
    "test": {
      "dependsOn": ["^build"]
    },
    "jobs#test": {
      "dependsOn": ["db#test"]
    },
}
```

Running `turbo test --filter=jobs` will skip building db.

**Comment by chris-olszewski** [comment] 2023-08-31 18:58
I understand the desire that the `dependsOn` field should append instead of overwrite the default task definition, but then we need to complicate task configuration further with different methods of merging vs overwriting fields. While we don't have any immediate plans, we do want to extend workspace level configuration and I could see this being a feature discussed there.

One thing I'll point out is that workspace tasks do not inherit any task definition from the non-workspace tasks. If you want some inheritance you should be using [workspace level configuration](https://turbo.build/repo/docs/core-concepts/monorepos/configuring-workspaces). This will still require you to list all of the task dependencies (`["db#test", "^build"]`), but any other fields that you don't override will be inherited from the root task definition.

Is there any parts of the [workspace tasks](https://turbo.build/repo/docs/core-concepts/monorepos/task-dependencies#from-arbitrary-workspaces) or [Configuring Workspaces](https://turbo.build/repo/docs/core-concepts/monorepos/configuring-workspaces) doc pages that could be tweaked to make the behavior we chose clearer?

**Comment by mehulkar** [comment] 2023-11-05 03:50
Hey there, @chris-olszewski is right. The overwriting of tasks with the `workspace#task` syntax in the root turbo.json is by design and we probably cannot change it at this point. Workspace configurations is probably what you're looking for. These docs compare the two: https://turbo.build/repo/docs/core-concepts/monorepos/configuring-workspaces#comparison-to-workspace-specific-tasks

**Closed by mehulkar** 2023-11-05 03:50 UTC
Labels: area: docs, owned-by: turborepo

**Comment by boompikachu** [comment] 2024-01-25 11:01
> This will still require you to list all of the task dependencies (`["db#test", "^build"]`), but any other fields that you don't override will be inherited from the root task definition.

Is there a way to inherit the `dependsOn` field from root to the workspace? Something like [...root.dependsOn, "^build"]?

**Comment by mehulkar** [comment] 2024-01-26 20:37
@boompikachu there is not. there's a more specific version of that conversation happening in https://github.com/vercel/turbo/issues/6798. 

Keep in mind that comments on closed issues will likely get missed. I generally recommend opening a new issue and referencing a closed issue instead!
