### ISSUE TITLE
unable to pipe outputs from command: Windows stdio in console mode does not support writing non-UTF-8 byte sequences

### ISSUE THREAD

**Issue by VagrantDaniel** [vercel/turbo#7075] opened 2024-01-23 02:38 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

https://github.com/vercel/turbo/tree/main/examples

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Windows

### Which canary version will you have in your reproduction?

latest

### Describe the Bug

when I exec command "turbo dev" in terminal,I find this issue:
'next'  ERROR  unable to pipe outputs from command: Windows stdio in console mode does not support writing non-UTF-8 byte sequences
Oops! Turbo has crashed.

### Expected Behavior

run "turbo dev" smoothly

### To Reproduce

![image](https://github.com/vercel/turbo/assets/26088772/cb03f863-0a16-4999-b858-7cbfe2c449f3)

**Comment by mehulkar** [comment] 2024-01-23 16:30
Does this reproduce without `turbo`?  Can you `cd apps/web` and try running `pnpm dev` (or whatever package manager you are using)?

**Comment by fendyk** [comment] 2024-02-07 10:03
For me, this happens if I did not install dependencies correctly. Can you check all your `package.json` files and look for any missing packages?

**Comment by yannianC** [comment] 2024-03-25 03:37
I have the same problem, how to solve it

**Comment by chris-olszewski** [comment] 2024-03-25 20:31
@yannianC Can you confirm that the underlying task produces valid UTF8? (i.e. run the script without `turbo` and verify you get the same error)

**Comment by xoxosos** [comment] 2024-04-03 10:01
![image](https://github.com/vercel/turbo/assets/85667817/036dd8b0-801a-464d-9c5a-1abf719e4efa)
 How to solve it ,pls？

**Comment by seeibt** [comment] 2024-04-23 11:52
same problem here

**Comment by xoxosos** [comment] 2024-04-24 07:11
> same problem here

It seems that only windows has this error.

**Comment by chris-olszewski** [comment] 2024-04-26 00:00
@xoxosos @seeibt 

A few questions:
 - Can you verify if that the underlying script is producing valid UTF-8 as it's output? If so could you provide the output that's getting produces by the underlying task when run without `turbo`?
 -  Is this happening consistently? If it is happening consistently, then if you could provide a reproduction repository that would help greatly.

**Comment by MateusZ36** [comment] 2024-04-30 15:04
One thing worked for me:

Check the box "beta use unicode utf-8 for worldwide language support" located at:

Time & Language -> Language -> "Administrative Language Settings"

**Comment by hdw1219** [comment] 2024-04-30 19:24
> One thing worked for me:
> 
> Check the box "beta use unicode utf-8 for worldwide language support" located at:
> 
> Time & Language -> Language -> "Administrative Language Settings"

Working for me on win 10!

**Comment by bigliuliu** [comment] 2024-06-14 05:03
> One thing worked for me:
> 
> Check the box "beta use unicode utf-8 for worldwide language support" located at:
> 
> Time & Language -> Language -> "Administrative Language Settings"
worked for me ! thank you so much !

**Comment by chris-olszewski** [comment] 2024-06-17 18:06
Closing as a work around has been found there hasn't been any reproduction provided or information that is actionable on our end.

If you encounter this and the workaround does not work, then please only reopen if you can provide a reproduction.

**Closed by chris-olszewski** 2024-06-17 18:06 UTC
Labels: kind: bug, area: windows, needs: author input, owned-by: turborepo

**Comment by komali2** [comment] 2024-10-22 05:51
I use turbo locally and don't have any checkbox options. Piping output of turbo commands crashes with 

```
Oops! Turbo has crashed.

A report has been written to /tmp/report-f665f29e-1b8f-420c-9e96-c000cf7c0a18.toml

Please open an issue at https://github.com/vercel/turborepo/issues/new/choose and include this file
```

The file:

```
"name" = "turbo"
"operating_system" = "Manjaro 24.1.1 (Xahea) [64-bit]"
"crate_version" = "2.1.2"
"explanation" = """
file 'library/std/src/io/stdio.rs' at line 1118
"""
"cause" = "failed printing to stdout: Broken pipe (os error 32)"
"method" = "Panic"
"backtrace" = """

   0:  0x10c58b2 - <unresolved>
   1:  0x10c9b5f - <unresolved>
   2:   0xe98c5d - <unresolved>
   3:   0xf84aab - <unresolved>
   4:   0xf7e6ce - <unresolved>
   5:  0x14a0e96 - <unresolved>
   6:  0x149f41b - <unresolved>
   7:   0x489cdc - <unresolved>
   8:   0x4891c3 - <unresolved>
   9:   0x48a194 - <unresolved>"""

```

**Comment by butterdoge** [comment] 2025-03-18 01:40
I have similar problem but my error was caused by using 'XXX=xxx' (env) in package.json in Windows System, It was fixed by using 'cross-env NODE_ENV=....' instead. I hope this is helpful for some people.

![Image](https://github.com/user-attachments/assets/60619a02-f700-475e-a8ce-4c7d71616161)

**Comment by umershaikh123** [comment] 2025-04-30 23:51
in my case , the issue was adding @import "tailwindcss"; in global.css file which was in tailwind latest docs
