### ISSUE TITLE
pnpm's dependenciesMeta.*.injected can't re-sync 

### ISSUE THREAD

**Issue by NullVoxPopuli** [vercel/turbo#2306] opened 2022-10-22 21:45 UTC
### What version of Turborepo are you using?

1.6.1

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Linux

### Describe the Bug

When using pnpm`s `dependenciesMeta.*.injected` feature (to make deep peers work), rebuilding the libraries to get the `dist` folder back requires "re-syncing" via `pnpm install` (which takes ~1s)

See this related issue on the pnpm repo: https://github.com/pnpm/pnpm/issues/4965#issuecomment-1287926075

### Expected Behavior

This is more a bug with `pnpm`, I think, and I don't know what turbo could do differently -- I'm mostly reporting for SEO / audit-trail purposes (so feel free to close this issue, if there is nothing turbo can do). As a work-around I thought of without `turbo` would no longer work _with_ `turbo` -- and that work around is to add `pnpm i; ` as a prefix to every script -- quite obnoxious, and the only real solution is to probably fix the issue in pnpm (which.. I'm not sure even how to approach the problem of re-syncing -- does pnpm need a background daemon that does the re-syncing? I'm not sure).

### To Reproduce

I have a sample / repro here: https://github.com/CrowdStrike/ember-headless-table/pull/44
It's gone through a number of iterations, but demonstrates:
 - cache working
 - but injected dependency is not detected by downsteam projects in the monorepo

**Comment by weyert** [comment] 2022-10-23 01:25
I am never really sure when you are supposed to use `dependenciesMeta.*.injected`. I currently use `workspace:*` as the version of my internal packages and it appears that turbo correctly build everything in order so it works.

Why do you need to inject the dependency?

**Comment by NullVoxPopuli** [comment] 2022-10-23 01:42
You need to inject a dependency when that dependency is in your monorepo, and that dependency declares peers that the consumers of the dependency is supposed to declare.

Otherwise peers don't resolve correctly

**Comment by nathanhammond** [comment] 2022-10-23 15:09
A possibly better workaround: create a root task called `resync`, make `build: //#resync, ^build`, and the mess is contained in one nice neat spot that you can easily delete if pnpm gets clever.

For bonus points this addresses merge-caused `node_modules` out of sync issues at the same time so maybe not worthwhile to delete.

***

We're not planning to do anything with this (other than recommend the most-elegant of workarounds) so I will close this. 🤷‍♂️ Thank you for filing the issue; it really helps to see what people are encountering.

**Comment by nathanhammond** [comment] 2022-10-23 15:59
After further discussion, I discovered that this is a request to run things at the leaf nodes, not at the root: after we have already acquired all of the information necessary to know if we would need to do this.

We should definitely patch up this papercut; we are actually even better positioned to do this.

**Comment by nathanhammond** [comment] 2022-10-24 01:05
Test.

**Comment by weyert** [comment] 2022-10-25 23:17
Looks like I am having a similar issue now after importing some package heavy project in my monorepo playground. 

@NullVoxPopuli  Did you had luck with @nathanhammond suggestion?

**Comment by nathanhammond** [comment] 2022-10-26 10:36
@weyert My pitch doesn't work.

**Comment by GiancarlosIO** [comment] 2022-10-28 16:18
In case someone needs this, there is an issue in pnpm with a reproduction repo that we can use to test solutions:
- https://github.com/pnpm/pnpm/issues/5479

**Comment by NullVoxPopuli** [comment] 2022-10-28 16:30
To be clear though, that fix also causes the behavior reported and linked in the original post in this thread.

**Comment by NullVoxPopuli** [comment] 2023-02-16 18:48
@simonihmig came up with a way to make this work over at: https://github.com/CrowdStrike/ember-headless-form/pull/52

It requires this util: https://github.com/CrowdStrike/ember-headless-form/pull/52/files#diff-cba6a6cd1877ea907fa4d3c06bdd8548011bc52b603638c9e8334870e53aca39

does it make sense for turborepo to adopt? or maybe it could be a util for pnpm -- since pnpm is already written in js/ts

**Comment by NullVoxPopuli** [comment] 2023-06-22 16:41
Here is a work-around if folks run in to this: https://github.com/NullVoxPopuli/pnpm-sync-dependencies-meta-injected

**Comment by mehulkar** [comment] 2024-03-11 19:12
> I'm mostly reporting for SEO / audit-trail purposes (so feel free to close this issue, if there is nothing turbo can do)

Closing this out as the related pnpm discussion also suggests that it's not a turborepo-specific problem.

**Closed by mehulkar** 2024-03-11 19:12 UTC
Labels: needs: triage, owned-by: turborepo

**Comment by NullVoxPopuli** [comment] 2024-03-11 19:19
> also suggests that it's not a turborepo-specific problem

there is probably a meta issue here (or somewhere) where folks may want to run something that _isn't_ cached before running a regular task (that could be cached).


for example:

`turbo build`
- for each workspace
  - run: build
    - regardless of cache hit/miss: run "X" after "build" is finished -- in this case, it'd be the sync util
