### ISSUE TITLE
New UI does not display summarization

### ISSUE THREAD

**Issue by MickL** [vercel/turbo#8501] opened 2024-06-15 10:23 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

-

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Mac

### Which canary version will you have in your reproduction?

2.0.4-canary.4

### Describe the Bug

When using `"ui": "stream"` i get a nice summarization of how many tasks were run, how many were cached and how long it took:

<img width="272" alt="Bildschirmfoto 2024-06-15 um 12 20 24" src="https://github.com/vercel/turbo/assets/5103210/8e45a6c8-3696-41bd-abca-fb7f5000705a">

Unfortunately with the new UI I dont see that anymore:

<img width="816" alt="Bildschirmfoto 2024-06-15 um 12 21 48" src="https://github.com/vercel/turbo/assets/5103210/f19590c3-2aec-4265-b34e-3ba725b46e0f">

Sorry if this issue already exists, I dont know what search terms to look for

### Expected Behavior

-

### To Reproduce

-

**Comment by anthonyshew** [comment] 2024-06-15 13:27
Duplicate of #8290!

I see your note. No worries! Upvote there, though, so we capture your interest. 👍

**Closed** 2024-06-15 13:27 UTC
Labels: kind: bug, needs: triage, owned-by: turborepo
