### ISSUE TITLE
[turborepo] children processes remain running when terminal is forcefully terminated.

### ISSUE THREAD

**Issue by yongholeeme** [vercel/turbo#5601] opened 2023-07-25 05:16 UTC
### What version of Turborepo are you using?

1.10.9

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

When the terminal is forcefully terminated, the children processes started by `go-turbo` are not terminated and remain running.

| Before running process | Running `pnpm run dev` | When the process is terminated by `CTRL + C` | When the terminal is forcefully terminated |
| :---: | :---: | :---: | :---: |
| <img width="1232" alt="Screenshot 2023-07-25 at 2 12 19 PM" src="https://github.com/vercel/turbo/assets/28642472/ae137b72-af3a-429c-86c0-b82bdf5cd3b5"> | <img width="1232" alt="Screenshot 2023-07-25 at 2 12 31 PM" src="https://github.com/vercel/turbo/assets/28642472/761960a8-32d6-4e8e-9672-52a006eabafb"> | <img width="1232" alt="Screenshot 2023-07-25 at 2 12 43 PM" src="https://github.com/vercel/turbo/assets/28642472/a9c561c6-5c58-453e-a038-599e0247c1b4"> | <img width="1232" alt="Screenshot 2023-07-25 at 2 13 15 PM" src="https://github.com/vercel/turbo/assets/28642472/9d1076e9-5c5d-4222-915b-9c4652a09fa4"> |

### Expected Behavior

Although the terminal is forcefully terminated, the children processes are terminated.

### To Reproduce

I can reproduce the issue using `pnpm dlx create-turbo@latest`, then execute `pnpm run dev` and forcefully terminate the terminal.

**Comment by tecoad** [comment] 2023-09-10 17:27
+1

**Comment by anthonyshew** [comment] 2023-12-06 04:19
If you could provide a reproduction for this, it would be of great help!

**Comment by arlyon** [comment] 2024-01-10 17:18
I am going to close this since as of 1.11 we have replaced all our child management code with a new rust implementation. Our handling is much better. If that is not the case, a repository to reproduce the issue using a recent >1.11 turbo version would be much appreciated.

All the best

Alex

**Closed by arlyon** 2024-01-10 17:18 UTC
Labels: kind: bug, needs: reproduction, owned-by: turborepo

**Comment by hamza512b** [comment] 2024-01-23 20:20
@arlyon I am facing the same issue. Here is reproduction: https://github.com/hamza512b/ctrl-c-turbo-reproduction/
