### ISSUE TITLE
Support colored output from original CLI

### ISSUE THREAD

**Issue by charkour** [vercel/turbo#223] opened 2021-12-13 03:36 UTC
### Describe the feature you'd like to request

Show original CLI colors in the output.

![](https://user-images.githubusercontent.com/4060187/145733177-98d75d05-49d9-4fdd-9362-a9c808493a78.png)

### Describe the solution you'd like

I would like to be able to have a `--colors` flag when running turbo to enable colors of the CLI output, including the output from the sub packages/apps. `turbo` would likely set the environment variable `FORCE_COLOR=1` before running commands. 

### Describe alternatives you've considered

Manually setting the monorepo's environment variable to `FORCE_COLOR=1`. This [enables color](https://github.com/chalk/chalk) when packages, like Next.js, use the npm package [`chalk`](https://www.npmjs.com/package/chalk)

**Comment by charkour** [comment] 2021-12-13 03:37
I would be willing to make a PR for this if applicable. Thanks!

**Comment by jaredpalmer** [comment] 2021-12-13 03:44
Go for it.

**Comment by jaredpalmer** [comment] 2021-12-13 03:46
Start here: https://github.com/vercel/turborepo/blob/155c5c3451f1e5ef26034fc9eeb99b40bb98b838/cli/internal/run/run.go#L716

**Comment by charkour** [comment] 2021-12-13 03:47
Thanks! I'll work on it tomorrow night.

**Comment by jaredpalmer** [comment] 2021-12-13 14:04
@charkour Are you in the [Discord](https://turborepo.org/discord)? If not, join us!

**Comment by charkour** [comment] 2021-12-14 02:49
I had a little time to try implementing this and found that the `FORCE_COLOR` environment variable needs to be set in the working directory where the command is executed (for example `docs`). Setting it after line 487 doesn't correctly force the color. 

I'll work on this more tomorrow. Let me know if you have any ideas. Go is a new language to me.

**Comment by charkour** [comment] 2021-12-16 11:30
I am making good progress on this.

**Comment by paul-vd** [comment] 2022-01-15 15:12
Is there any update on this? 🎅🎄🎁

**Comment by charkour** [comment] 2022-01-15 18:50
If you're using node, you can set FORCE_COLOR=1 in your environment variables. The PR hasn't been reviewed.

**Comment by narutosstudent** [comment] 2022-07-28 04:57
@charkour Has this been implemented yet?

Seems like a neat thing to have.

**Comment by charkour** [comment] 2022-07-28 12:39
Hey @narutosstudent, I don't believe this has been implemented yet. My original PR was closed because I had incorrectly made this assumption about node environments being the only use case for turborepo. 

For a workaround, I'd recommend using `FORCE_COLOR=1` in your environment variables if you are using a node environment.

**Comment by sebaplaza** [comment] 2022-09-15 08:03
I'm having problems in my local terminal (i'm using tilix on linux) to show colors automatically, i think the TTY detection is not working as it should. Other utils are showing colors without any problem.

@jaredpalmer could be a problem with this line ?

https://github.com/sebaplaza/turborepo/blob/main/cli/internal/ui/ui.go#L17-L18

**Comment by janvennemann** [comment] 2022-09-23 08:28
> @charkour Yea that's what I'm currently using, but it seems like quite a dirty solution, For example, if you have 10 packages with each of them having roughly ~4 commands ![image](https://user-images.githubusercontent.com/39598117/155180882-58160b19-efdb-4474-98bb-deece1870b94.png) This would mean that you need to make at least 40 changes to enable colors.
> 
> I think it would be much better to use `--colors`, or considering the [comment in your PR](https://github.com/vercel/turborepo/pull/359#issuecomment-998378858), the flag could be something like `--node-colors` instead, and eventually a unified `--colors` flag depending on the decisions. but yea the feature in your PR would be most welcoming. That would avoid having to set the `FORCE_COLOR=1` in ~40 different places 😅

FYI, you don't have to put `FORCE_COLOR` into every package, only before the `turbo run` command in your top level `package.json`. For example, this worked for me to get colors working with `vitest`:

```json
{
  "scripts": {
    "test": "FORCE_COLOR=1 turbo run test"
  },
}
```

And the actual `package.json` for the package only includes

```json
  "scripts": {
    "test": "vitest"
  },
```

**Comment by scamden** [comment] 2023-01-07 01:01
just another piece of info here that this also seems to apply to running turbo itseld which is not a good look. 

aka: `turbo typecheck:all` (which is `"typecheck:all": "turbo run typecheck --continue"` in root `package.json`) works but is completely white which makes it nearly impossible to discern the output from different packages.

**Comment by connorjs** [comment] 2023-03-09 00:20
> no spinners, colors, and other terminal progress animation/indicators.

I wanted to cite this from the closed-as-duplicate #2251 issue. Can we change the title of this to `Support output from original CLI (colors, spinner, etc)`? I occasionally search for `spinner` and hope to more quickly find this one to check on progress. (I have also subscribed this time 😉.)

`FORCE_COLOR=1` does not seem to help with spinners or other animation.

**Comment by dbousamra** [comment] 2023-05-03 03:34
Any updates on this?

**Comment by finnatsea** [comment] 2023-05-10 16:02
Just want to voice my support for adding this. It is extremely important for dev ergonomics and accessibility.

**Comment by ZeldOcarina** [comment] 2023-05-25 12:39
> Just want to voice my support for adding this. It is extremely important for dev ergonomics and accessibility.

@finnatsea just add FORCE_COLOR=1 as an env variable and you'll have that! :)

**Comment by wesleytodd** [comment] 2023-05-27 18:14
`FORCE_COLOR=1` Is not working for me, and based on the responses here since the first mention of that solution, it is also not working for others. My guess if folks recommending it are not clear on what is being requested. This request if to the original cli output from the task to maintain it's colors.  This usually will mean the child process' need to be run in a TTY, and my educated guess (I read some of the code here) is that this env var does nothing to effect how the process is spawned. So unless whatever tools are run in the task process also respect `FORCE_COLOR` then they will not think they should display colors.

If this was a JS package, we could use `node-pty` and even the most rudimentary tools would likely follow suite and display colors. Since this is not JS, I have no idea if there are any good libraries for this. But I would like to say that until this feature is added, the UX of running turbo in anything but CI is significantly worse than it could be.

An example:

https://github.com/tapjs/tap-mocha-reporter/blob/f4b1acea21f723a68ea5be2ec321a1a0412c0cea/lib/reporters/base.js#L5

This package for parsing tap output uses `TAP_COLORS` as it's override, but will respect if the stdin/out is TTY. If I manually set this in my `package.json` script, turbo will maintain the colors with or without `FORCE_COLOR` being set. But that means that EVERY single consumer needs to know what options are available in each tool to force colors, and it means the normal detection libraries need to do is overridden. This can cause issues in CI systems which don't understand colors (jenkins used to be like this).

**Comment by datner** [comment] 2023-06-06 11:13
Why isn't this the default? I know that some maintainers consider this a low on the list nice-to-have, but I could not disagree more. This is so pronounced that [nx even have a section about how much this sucks and is a reason to choose nx instead.](https://nx.dev/more-concepts/turbo-and-nx#11.-transparency)..

I am sure there is some hidden complexity around this, but thats not a reason to abandon this for almost 2 years.

If it is required and some maintainer is willing, I will gladly 1:1 to understand how to implement it, and make a PR

**Comment by wesleytodd** [comment] 2023-06-06 14:57
> Not sure it seems a very complex explanation but it is working for me: ![image](https://user-images.githubusercontent.com/42982095/243373289-ee5754cb-7520-4b6b-82fb-8b2ff9e46160.png)

@ZeldOcarina This is because whatever is running in your task is doing one of two things:

1. ignoring that it is not a `TTY` and ouputing ansi color escape codes anyway (which is generally not considered good)
2. respecting `FORCE_COLOR` to turn them on. which is fine, but not all tools do this.

What my comment above was about is having turbo trick the task process into thinking it is running in a `TTY` shell which would set the correct defaults for *almost all tools in the node.js ecosystem*.

**Comment by billyzkid** [comment] 2023-07-06 21:38
After waiting over a year, we're moving to nx/lerna solely because of this. We even overlooked the failing daemon issues on Windows (ended up just disabling it). But eventually it was determined that colorized lint/format/test/build/* output is too critical for development and none of the workarounds attempted/suggested were satisfactory.

**Comment by wesleytodd** [comment] 2023-07-06 23:44
@billyzkid In case this update helps you, I think I was able to get colors out of all the tools I was using by wrapping the call to `turbo` in a pty via `node-pty`. I think one of the reasons this is confusing folks is that there are many layers at work. I know nothing of your setup, but I think that no one in this thread has (including myself) posted a reduced test case for where *turbo* specifically is breaking the colors. And seeing as I was able to get colors in my tool which parses the turbo log output and transforms it into a web ui with colors in the logs, I am pretty sure at this point turbo is not the *cause* but is only making the reason harder to debug.

**Comment by Adrien5902** [comment] 2023-10-08 21:32
![image](https://github.com/vercel/turbo/assets/81705101/62c678d0-4ac9-4733-a294-717876ebbe7d)
![image](https://github.com/vercel/turbo/assets/81705101/c3afc87a-1e5d-4c10-8956-fd5b11735f1a)
Using concurrently, colors from concurrently won't show in terminal when starting from turbo

**Comment by Adrien5902** [comment] 2023-10-11 16:52
@wesleytodd thanks for answering, you must be right, I don't know why vite has colors while concurrently doesn't but it does not matter the issue is probably with concurrently. I resumed working on this old project which used concurrently and I moved to a monorepo to have server side and client side split. But it'll be even better if I split electron and vite in two different packages anyway. So I won't have the need for concurrently anymore.

**Comment by anthonyshew** [comment] 2024-01-17 06:41
An update for those following this issue: We're aiming to land this feature in Turborepo 1.12!

**Comment by gruckion** [comment] 2024-01-29 14:54
Will it support the emojis (assumption that these are emojis and not just a coloured cross, but the question still stands).

<img width="750" alt="image" src="https://github.com/vercel/turbo/assets/4559650/78874717-9c96-430e-938b-863918a14bf3">

Jest has the tick and cross when running the tests.

<img width="720" alt="image" src="https://github.com/vercel/turbo/assets/4559650/0141329f-6629-4dcc-b6d9-719221801f21">

**Comment by finnatsea** [comment] 2024-01-29 23:53
Can we get this on the roadmap? Also considering switching to nx basically for this single reason.

**Comment by wesleytodd** [comment] 2024-01-29 23:58
@finnatsea did you see two comments up? https://github.com/vercel/turbo/issues/223#issuecomment-1895099649

**Comment by anthonyshew** [comment] 2024-01-30 01:19
@finnatsea I went back in time to stop you from switching before you even considered it!

https://github.com/vercel/turbo/issues/223#issuecomment-1895099649

**Comment by anthonyshew** [comment] 2024-02-01 20:02
Good news, everyone! This feature is now supported as of 1.12. Upgrade today!

Release notes: https://turbo.build/blog/turbo-1-12-0

**Closed by anthonyshew** 2024-02-01 20:02 UTC
Labels: area: ergonomics, area: logging, owned-by: turborepo

**Comment by wesleytodd** [comment] 2024-02-01 21:17
@anthonyshew mind linking the PR or commit?

**Comment by kieran-osgood** [comment] 2024-05-25 13:22
Looking through the PR, is this is on by default and non-user configurable?
I have a test task for a CLI app that is testing ANSI strings for formatting which fail through turbo due to parsing to the color outputs.
