### ISSUE TITLE
[turborepo] turbod cannot be started due to permission denied for directory

### ISSUE THREAD

**Issue by draconisNoctis** [vercel/turbo#3092] opened 2022-12-20 14:22 UTC
### What version of Turborepo are you using?

1.6.3

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Linux

### Describe the Bug

When I start the turbo daemon with `turbo daemon start`, I'm getting the following error:
```
connection to turbo daemon process failed. Please ensure the following:
        - the process identified by the pid in the file at /tmp/turbod/6875c08de545a292/turbod.pid is not running, and remove /tmp/turbod/6875c08de545a292/turbod.pid
        - check the logs at /home/dracon/.local/share/turborepo/logs/6875c08de545a292-HeatingOnline-Light.log
        - the unix domain socket at /tmp/turbod/6875c08de545a292/turbod.sock has been removed
        You can also run without the daemon process by passing --no-daemon
```

The log files are giving me the following reason for that:
```
2022-12-20T15:01:27.651+0100 [ERROR] turbod: error watching /path/to/project: failed adding watch to /path/to/project/.mysql-data/sys: permission denied
```

The referenced path is a mounted docker volume and is not accessible by the current user.

### Expected Behavior

Thread such directories/files as a warning instead of an error. Or provide an option/configuration to ignore such directories.

### To Reproduce

- create an empty turborepo `npx create-turbo@latest`
- create a directory with a file `mkdir this-is-the-problem && touch this-is-the-problem/.keep`
- change access and owner of the directory `chmod 0770 this-is-the-problem  && sudo chown 0:0 this-is-the-problem`
- start the turbo daemon `turbo daemon start`

**Comment by chris-olszewski** [comment] 2023-01-05 19:25
I'm unable to reproduce on Mac so this appears to be an issue with just the `fsnotify` based filewatcher. I think it makes sense for the watcher to only warn when it doesn't have permission to read a file in the repo. Caveat being, that this file/dir shouldn't be listed in the outputs/inputs section of your `turbo.json` as Turbo won't be able to read or cache the file. 

@gsoltis does this make sense to you?

**Comment by sergio-ferreira-jscrambler** [comment] 2023-01-23 14:47
I'm having the same issue with version 1.7.0, Linux, and pnpm.

`2023-01-23T12:24:37.837Z [ERROR] turbod: error watching <folder>: failed adding watch to /<folder>/.data/postgres: permission denied`

**Comment by notaphplover** [comment] 2023-03-14 13:18
Same with version 1.8.3. Seems to be a regression, it was already fixed in the past on https://github.com/vercel/turbo/issues/997

**Comment by yanickrochon** [comment] 2023-07-27 12:51
I've been looking for a way to add a pattern of files to ignore, like `.gitignore` or `.npmignore`. There should be a `.turboignore` to list files and folders which **should not be watched**

**Comment by anthonyshew** [comment] 2024-02-05 05:50
It's been awhile without any activity on this issue. Additionally, we've made a lot of changes towards stability for the daemon so I'm hoping that this has been cleared up in those updates. If you're still seeing this problem, please open up a fresh issue!

**Closed by anthonyshew** 2024-02-05 05:50 UTC
Labels: kind: bug, owned-by: turborepo
