### ISSUE TITLE
[Turbopack] weird node_modules import issue

### ISSUE THREAD

**Issue by westlakem** [vercel/turbo#6483] opened 2023-11-16 13:41 UTC
### What version of Turbopack are you using?

unsure, NextJS v 14.0.2

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Windows

### Describe the Bug

import code (my global.scss file):
![image](https://github.com/vercel/turbo/assets/4505074/30611148-b33f-4608-9acf-827f6beb2a6d)

node_modules directory: 
![image](https://github.com/vercel/turbo/assets/4505074/a29ee427-1d57-4228-9770-b60644ba31dd)

Error message:
![image](https://github.com/vercel/turbo/assets/4505074/52e87957-a9f5-498d-a6f5-f00ccc41d0a6)

### Expected Behavior

It should import and be used like it does when I don't use Turbopack, and the website should render.

![image](https://github.com/vercel/turbo/assets/4505074/30de6945-369d-45c6-878d-8f5477559d58)

### To Reproduce

install bootstrap-icons and try to use them in a scss project

**Comment by chris-olszewski** [comment] 2023-11-17 17:28
Hi, just confirming I'm understanding:
In the workspace directory: `pnpm run dev` works as expected, but `turbo run dev` results in a failure?

You can get the version of Turborepo that you're using with `turbo --version`. Due to the nature of this issue, I probably won't be able to help without a reproduction repo. If you could provide one that would be very beneficial.

**Comment by westlakem** [comment] 2023-11-17 17:51
> Hi, just confirming I'm understanding: In the workspace directory: `pnpm run dev` works as expected, but `turbo run dev` results in a failure?
> 
> You can get the version of Turborepo that you're using with `turbo --version`. Due to the nature of this issue, I probably won't be able to help without a reproduction repo. If you could provide one that would be very beneficial.

`pnpm run dev --turbo` is the command that doesn't work.  Unfortunately `turbo` isn't listed in my dependency tree, and running `turbo` from the command line results in `bash: turbo: command not found`. Unfortunately this is for a corporate application and I only recently tried running turbo on the app.  I'm going to be honest with you, I don't know when I'm going to find the time to create a repo to reproduce the issue.  Maybe a new project with bootstrap only would cause the issue?

**Comment by chris-olszewski** [comment] 2023-11-17 18:23
Ah gotcha, this is an issue with turbopack. I'll label it as such and alert the team.

**Comment by timneutkens** [comment] 2024-02-09 13:23
Dug a bit into this as it wasn't clear what the exact cause of the issue was.

Minimal reproduction: https://github.com/timneutkens/sass-resolve-issue

The underlying issue is that all `url()`s are resolved relative to the root file that started the Sass compilation. This means that when you try to reference a relative file it's always resolved relative to the entrypoint file, not the current file being compiled. That is a bug that we'll have to investigate.

**Comment by ForsakenHarmony** [comment] 2024-02-15 01:08
Might be the same / similar issue as https://github.com/vercel/next.js/issues/60088

**Comment by timneutkens** [comment] 2024-03-05 14:21
Next.js with Turbopack is now passing all tests we have for Sass support, including importing external packages 🙌

Please give it a try using npm install next@canary and let me know if you're running into anything else.

**Comment by ForsakenHarmony** [comment] 2024-03-11 20:55
Closing for now as it should be fixed, feel free to create a new issue in the next.js repo

**Closed by ForsakenHarmony** 2024-03-11 20:55 UTC
Labels: kind: bug, owned-by: turbopack
