### ISSUE TITLE
[turborepo] Turborepo 1.7.0 hangs on Ctrl+C on Windows 11

### ISSUE THREAD

**Issue by bencun** [vercel/turbo#3427] opened 2023-01-22 15:41 UTC
### What version of Turborepo are you using?

**1.8.3, 1.7.0, works properly on 1.6.3**

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Windows 11

### Describe the Bug

When I spin up my project using `pnpm run dev` (one Next.js package, one Payload CMS package, regardless of whether I run both of those or only either one of them using `--filter`) and try stopping the running command with Ctrl+C the terminal window hangs and I have to close it by clicking the close button or via Alt+F4.

It seems like it stops the running processes properly but Turbo hangs since the resources get freed properly (e.g. ports the apps are running on).

The next time I run `pnpm run dev` I get this:

```
WARNING  failed to contact turbod. Continuing in standalone mode: connection to turbo daemon process failed. Please ensure the following:
        - the process identified by the pid in the file at C:\Users\Bencun\AppData\Local\Temp\turbod\f9f4614d197fa42f\turbod.pid is not running, and remove C:\Users\<username>\AppData\Local\Temp\turbod\f9f4614d197fa42f\turbod.pid
        - check the logs at C:\Users\<username>\AppData\Local\turborepo\logs\f9f4614d197fa42f-cms-monorepo.log
        - the unix domain socket at C:\Users\<username>\AppData\Local\Temp\turbod\f9f4614d197fa42f\turbod.sock has been removed
        You can also run without the daemon process by passing --no-daemon
```

...everything runs fine but Ctrl+C causes Turbo to hang again.

The logfile in the provided path is empty.

If I delete the files at `\AppData\Local\Temp\turbod` the next start of `dev` command produces no error message but Ctrl+C hangs turbo again.

I'm on Windows 11 22H2 and I'm using Powershell.
I've also tested this on macOS Ventura od 2019 Intel MBP 16" and there are no issues whatsoever on that platform.

### Expected Behavior

Turbo exits gracefully.

### To Reproduce

Run a pnpm + Turbo 1.7.0 monorepo locally on a Windows 11 machine.
Run the `kitchen-sink` example with Turborepo 1.7.0 - so make sure to remove the pnpm lockfile first.

### Reproduction Repo

Check above.

**Comment by Crassmof** [comment] 2023-01-22 21:17
I am getting the same warning running pnpm and Turbo 1.70 on Windows 10, but Ctrl + C works fine

**Comment by homanp** [comment] 2023-01-23 11:18
Getting the same warning on `macOS Monterey 12.6`. Running `npm run dev` cause the app to freeze.

**Comment by kevva** [comment] 2023-01-23 11:47
Also getting the same on macOS. `1.6.3` doesn't work either.

**Comment by e2goon** [comment] 2023-01-26 20:15
Same issue `1.7.0`

**Comment by gsoltis** [comment] 2023-01-27 22:34
The daemon warning should be unrelated. You can pass `--no-daemon` to silence it while we verify the Ctrl+C issue

We're currently having trouble reproducing this issue, so I think we need more details to try to match the behavior.
@bencun can you verify that this is an issue with `1.7.0` and whether a downgrade to `1.6` fixes it?

@kevva and @homanp Can you describe your scenario a bit more? Version and command you're running (assuming kitchen sink example) and what happens when you hit Ctrl+C?

**Comment by bencun** [comment] 2023-01-27 22:44
Yes, I can confirm that both issues are nonexistent on 1.6.3 for me.

**Comment by lean-dev** [comment] 2023-01-30 09:51
Yes, me to confirm this issue as well (Windows 11). 
  
```
npx degit vercel/turbo/examples/kitchen-sink kitchen-sink
cd kitchen-sink
pnpm install
git init . && git add . && git commit -m "Init"
pnpm dev
```

Some details:
- No problems with version 1.6.3 (kitchen sink)

But after upgrading to 1.7.0:

```
pnpm update turbo
pnpm dev
```

- If running in Powershell (Version 5 and Version 7): after Ctrl+C the console input is somewhat broken (need to hit keys twice, every second key is absorbed). Output of any command sometimes hangs, sometimes work. Can't narrow that.

- **If running in Command Line: need to exit two batch jobs. But everything fine afterwards.**

Issue is not related to Windows Terminal, is present as well if i start the powershell with windows console host.

**Comment by exneval** [comment] 2023-02-03 03:34
I can confirm the issue as well with Windows 11

**Comment by irg1008** [comment] 2023-02-03 11:44
Yeah both issues happening in v.1.7.2. Can we start looking into turbo to fix it?

**Comment by irg1008** [comment] 2023-02-03 11:47
For the moment, if you are using vscode, create a .launch.json and run the packages/apps from the UI.

Example:
```json
    {
      "name": "Full-Stack",
      "type": "node-terminal",
      "request": "launch",
      "command": "turbo dev --filter=client... --filter=server...",
      "serverReadyAction": {
        "action": "debugWithChrome",
        "pattern": "started server on .+, url: (https?://.+)",
        "uriFormat": "%s",
        "killOnServerStop": true
      }
    }
```

You can kill and relaunch it faster
It doesn't solve anything but just in case it's useful to someone

**Comment by p7gg** [comment] 2023-02-06 11:49
Same thing is happening for me... The issue seems to happen whenever I try to `ctrl + c` persisting task, such as dev or storybook...

Tried adding the `persistent` key to the `turbo.json` but it didn't help.

**Comment by joostmeijles** [comment] 2023-02-13 16:43
Same issue here. Powershell no longer responds after a CTRL+C when NextJS / Storybook was running using Turborepo.

Is there a workaround for it?

**Comment by nathanhammond** [comment] 2023-02-14 10:54
Finally have a hypothesis! Has anybody happened to see a prompt that says `Terminate batch job (Y/N)?` when pressing `^C`?

**Comment by 413n** [comment] 2023-02-14 12:51
@nathanhammond Yes exactly! In my case then I need to kill the terminal and start a new one because it gets stuck on that prompt.

**Comment by joostmeijles** [comment] 2023-02-14 12:53
> @nathanhammond Yes exactly! In my case then I need to kill the terminal and start a new one because it gets stuck on that prompt.

Same behavior here.

**Comment by lean-dev** [comment] 2023-02-14 13:26
> Finally have a hypothesis! Has anybody happened to see a prompt that says `Terminate batch job (Y/N)?` when pressing `^C`?

Yes! And if I answer this on the now interactive terminal with y (of course need to type any key twice), it seems to stop this batch. And everything is working fine again.

**Comment by antokhio** [comment] 2023-02-28 07:17
same here 1.7.2

**Comment by Ahmadh26** [comment] 2023-03-06 10:16
still happening with 1.8.3
if you ctrl+c then press `y` then `enter` twice the terminal seems to respond again
attached a picture to demonstrate
![image](https://user-images.githubusercontent.com/57562297/223081935-c7389cba-9174-451b-b645-8ac31f8cea3a.png)

**Comment by AleksandarDev** [comment] 2023-03-07 17:30
On project: `pnpm dlx create-turbo@latest`

Running `pnpm dev` and then at any point hitting CTRL+C doesn't fully terminate app (looks like it's terminated but terminal is unresponseive for following commands).

I get "Terminate batch job (Y/N)?" but terminal doesn't wait for input.
Hitting enter couple of times sometimes displays "Terminate batch job..." again but still unable to input as I am immediately presented with terminal next command prompt.

OS: Windows 11 Version 10.0.22624
Turbo: 1.8.3
Terminals:
- Command Prompt
- Windows Powershell (the one that is installed with with windows)
- Powershell 7.3.2 and 7.3.3

**Comment by coldino** [comment] 2023-03-10 14:41
I decided to test this a little more to hopefully find something that might help.

I've reproduced the issue in the following additional cases with turbo 1.8.3:

- On Windows 10 22H2 19045.2604
- Using `bash` from within:
  * Git Bash prompt from Git for Windows
  * Windows Terminal
  * VSCode's integrated terminal
- Using `cmd` from within:
  * Standard command prompt
  * Windows Terminal
  * VSCode's integrated terminal
- Using `powershell` from within:
  * Standard PowerShell terminal
  * Windows Terminal
  * VSCode's integrated terminal

There are no good outcomes in any combinations.

In all cases `Terminate batch job (Y/N)?` appears repeatdly alongside the normal shell prompt. If you type `y<enter>` you can the recover the terminal to a usable state, but in many other cases the terminal locks up. It seems likely another process is still active and taking input from the shell.

Now for the most important finding! ***Even after successfully recovering the terminal it seems the task itself is still running.*** For example in my case the development server port was still in use until the terminal was completely closed. This is more than a terminal interaction annoyance.

**Comment by coldino** [comment] 2023-03-10 15:23
@arlyon I can confirm that turbo and go-turbo are *not* running, but the task it launched is. In my case this means I can see a node process at least partially running vite dev still remaining.

For something more visual here are some screenshots from Process Explorer.

We go from this while running:
![image](https://user-images.githubusercontent.com/28345893/224353218-8eb8da3c-bfaf-4a02-aa3a-4b0167e9f9e5.png)

To this after Ctrl-C:
![image](https://user-images.githubusercontent.com/28345893/224354118-7e1bfdd5-e7a0-4124-ab1c-8d2ab9ca5f8b.png)

To this after typing `y<enter>`:
![image](https://user-images.githubusercontent.com/28345893/224354160-26e7e983-7827-44df-b31d-dfc3173c646c.png)

The remaining node process is `vite dev`.
The lonely cmd.exe process is `turbo.CMD` with the command-line I used.

**Comment by arlyon** [comment] 2023-03-10 16:50
I have a fix for this. The problem is doubly stacked ctrl C handlers, which cancel eachother out. It should be available in the next release. Will post a PR link when it is ready :)

**Closed** 2023-03-15 21:25 UTC
Labels: kind: bug, area: turborepo
