### ISSUE TITLE
[turborepo] Turbo build works in individual packages but not at workspace : "\pnpm.cmd": file does not exist

### ISSUE THREAD

**Issue by stevebeauge** [vercel/turbo#5976] opened 2023-09-18 10:14 UTC
### What version of Turborepo are you using?

1.10.14

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Windows

### Describe the Bug

I'm trying to migrate a NX monorepo with 20 packages to turbo repo.

The repo contains "applications" (webpack 4 based - sic!), "packages" (shared by apps) and "tools" with shared config or compilation utils.

However, turbo fails to build my workspace:

Running `pnpm turbo build` at workspace root fails with:

> `@mycorp/somelib#build: exec: "C:\\pathto\\packages\\somelib\\node_modules\\.bin\\pnpm.cmd": file does not exist`

The same error is emitted for every package without internal dependency (other packages are logically not tried to be built).

The `pnpm.cmd` is not present at the specified path, but is present at the workspace level (which is expected, I guess, regarding pnpm workspace feature).

However, if I try to build the package individually, it works as expected

````
cd C:\pathto\packages\somelib
pnpm turbo build
````

Once the build is OK from the package, next builds will be (thanks to the cache I guess)

If it can help, here's the `--summary` output: 
[2VZ7t7AVZrgwKmST7N4JxTO2mda.json.txt](https://github.com/vercel/turbo/files/12646648/2VZ7t7AVZrgwKmST7N4JxTO2mda.json.txt)

### Expected Behavior

Should build the whole monorepo from root

### To Reproduce

````powershell
cd somewhere
git clone https://github.com/stevebeauge/repro-issue-with-pnpm-turbo
cd repro-issue-with-pnpm-turbo
pnpm i
pnpm turbo build
````

💥 Fails with:

````
• Packages in scope: @mycorp/somelib
• Running build in 1 packages
• Remote caching disabled
@mycorp/somelib:build: cache miss, executing 28de37d323a7d811
@mycorp/somelib:build: ERROR: command finished with error: exec: "C:\\temp\\repro-issue-with-pnpm-turbo\\packages\\somelib\\node_modules\\.bin\\pnpm.cmd": file does not exist
@mycorp/somelib#build: exec: "C:\\temp\\repro-issue-with-pnpm-turbo\\packages\\somelib\\node_modules\\.bin\\pnpm.cmd": file does not exist

 Tasks:    0 successful, 1 total
Cached:    0 cached, 1 total
  Time:    555ms

 ERROR  run failed: command  exited (1)
````

Then

````powershell
cd .\packages\somelib\
pnpm turbo build
````

✔ This time, OK with this output:

````
• Packages in scope: @mycorp/somelib
• Running build in 1 packages
• Remote caching disabled
@mycorp/somelib:build: cache miss, executing 28de37d323a7d811
@mycorp/somelib:build:
@mycorp/somelib:build: > @mycorp/somelib@0.9.0 build C:\temp\repro-issue-with-pnpm-turbo\packages\somelib
@mycorp/somelib:build: > tsc --build --pretty -v
@mycorp/somelib:build:
@mycorp/somelib:build: [12:07:13] Projects in this build:
@mycorp/somelib:build:     * tsconfig.json
@mycorp/somelib:build:
@mycorp/somelib:build: [12:07:13] Project 'tsconfig.json' is out of date because output file 'lib/index.js' does not exist
@mycorp/somelib:build:
@mycorp/somelib:build: [12:07:13] Building project 'C:/temp/repro-issue-with-pnpm-turbo/packages/somelib/tsconfig.json'...
@mycorp/somelib:build:

 Tasks:    1 successful, 1 total
Cached:    0 cached, 1 total
  Time:    2.675s
````

### Reproduction Repo

https://github.com/stevebeauge/repro-issue-with-pnpm-turbo

**Comment by stevebeauge** [comment] 2023-09-18 13:29
I also tested in WSL 2. Nearly same error:

````
• Packages in scope: @mycorp/somelib
• Running build in 1 packages
• Remote caching disabled
@mycorp/somelib:build: cache miss, executing 28de37d323a7d811
@mycorp/somelib:build: ERROR: command finished with error: fork/exec node_modules/.bin/pnpm: no such file or directory
@mycorp/somelib#build: fork/exec node_modules/.bin/pnpm: no such file or directory

 Tasks:    0 successful, 1 total
Cached:    0 cached, 1 total
  Time:    28ms
````

**Comment by nathanhammond** [comment] 2023-09-20 05:54
Hey @stevebeauge! I'm not able to reproduce with my Windows setup, so I _suspect_ that this is a "unique-to-your-setup" problem.

Let me give you a pointer into the codebase so you know what is happening:
https://github.com/vercel/turbo/blob/73f87a610850be2093a52ab32c4fbc58d7d276dd/cli/internal/run/real_run.go#L458-L459

- We use `pnpm run` in order to execute the script that is in `package.json`.
- We run that in the individual package directory.
- We _don't_ append `.cmd` or do anything to attempt to locate the executable.
- We expect for it to be on `PATH` already.

Your report is that, when attempting to run `pnpm run <script-name>`, it is failing. That when you directly invoke `pnpm turbo build` at the correct path it is located, but when we do it, it does not.

I _hypothesize_ that this issue is `corepack` or your `pnpm` installation method. Can you tell me more about that?

**Comment by stevebeauge** [comment] 2023-09-20 09:13
My setup is a classic W10x64.

I installed node 20 using nvs.
I installed pnpm using `npm -g i pnpm`

turbo is *not* installed globally.

Here are some tests I made (removing node_modules\.cache between each test):

* installing turbo globally then run `turbo build` : compile successfully ✔
* still with turbo installed globally, running `pnpm turbo build`: does not compile 💥
* (w/o turbo globally installed) in the workspace's package.json, I setup a script `"build-all" : "turbo build"` : ✔this compiles
* (w/o turbo globally installed) created a new monorepo using `pnpm dlx create-turbo@latest` then `pnpm turbo build` : ✔works. I have not been able to spot the difference with my repo

My env `PNPM_HOME` is `C:\Users\steve\AppData\Local\pnpm`, which is also in my `PATH`

Versions:
* node : 20.5.1
* pnpm : 8.7.5

**Comment by stevebeauge** [comment] 2023-09-21 13:18
Also tried on stackblitz : https://stackblitz.com/edit/github-uu3jov in order to eliminate "local" issues.

Same behavior : `Error: Cannot find module '/home/projects/github-uu3jov/packages/somelib/node_modules/.bin/pnpm'`

**Comment by nathanhammond** [comment] 2023-09-25 02:19
Maybe you have a binary collision?
https://developer.stackblitz.com/platform/webcontainers/turbo-package-manager

```
~/projects/github-uu3jov 5s
❯ turbo
warn Starting on January 1, 2024, turbo will no longer be supported and will be removed. We now offer built-in support for npm, pnpm, and yarn v1. For additional information, check out https://turbo.sh.

warn preInstall No description field
warn preInstall No repository field
warn preInstall No license field
┌ [1/4] 🔍  Resolving dependencies
└ Completed in 2.422s
┌ [2/4] 🚚  Fetching dependencies
│ info pruneDeps Excluding 4 dependencies. For more information use `--verbose`.
└ Completed in 1.944s
┌ [3/4] 🔗  Linking dependencies
└ 𐄂 Failed
Error: ENOTDIR: not a directory, mkdir
'/home/projects/github-uu3jov/node_modules/rimraf'

Code: ENOTDIR

error Command failed with exit code 1
```

**Comment by stevebeauge** [comment] 2023-09-25 07:17
Hello @nathanhammond.

I'm not to understand your last comment (since I do not use turbo package manager).

That said, I've been able to narrow the issue. In my workspace's package.json, I declared `pnpm` as a dev dependency. I suspect this interfere with turbo's resolution of pnpm command.

Removing this dependency (relying on `"engines": { "pnpm" : ">=8.7.0" }` instead) seems to unblock the issue.

I'm not sure, however, if turbo should support this scenario or if the setup is weird.

**Comment by arlyon** [comment] 2023-09-25 12:14
Glad you could resolve the issue. I have never seen a repo with this myself in the wild, the `engines` field is the standard way of expressing this. I am surprised pnpm doesn't warn you when relying on itself...

I am going to close this now, but thank you for opening anyways, and posting your solution since it helps others who may have repos with the same setup.

**Closed by arlyon** 2023-09-25 12:14 UTC
Labels: kind: bug, needs: triage, owned-by: turborepo
