### ISSUE TITLE
[turbopack]  Error when console logging in NextJS 13

### ISSUE THREAD

**Issue by benmarg** [vercel/turbo#2717] opened 2022-11-16 00:17 UTC
### What version of Turbopack are you using?

v1.6.3

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Mac

### Describe the Bug

After spinning up a NextJS 13 repo and setting the --turbo flag to the dev script, turbo works as expected, except for any attempts to console log in your app. For example with 

<img width="750" alt="Screen Shot 2022-11-15 at 3 44 54 PM" src="https://user-images.githubusercontent.com/14111627/202051691-79b4e1c9-1c08-4c95-be78-645bb8605a0d.png">

You'd expect several console logs, however both the terminal in which you npm run dev and the chrome terminal don't log anything. Swapping back to default, the console logs show up in the terminal

### Expected Behavior

Console log shows up in the terminal. 

### To Reproduce

Create-next-app@latest, swap the dev script to "dev": " next dev --turbo", make a page and call a console log from that page.

Behavior: 
<img width="1728" alt="Screen_Shot_2022-11-15_at_3 57 30_PM" src="https://user-images.githubusercontent.com/14111627/202052141-2a7d89b0-e224-48be-8920-7a9fe5b8860f.png">

<img width="384" alt="Screen_Shot_2022-11-15_at_3 57 13_PM" src="https://user-images.githubusercontent.com/14111627/202052189-0f19c50f-7c5c-436d-90cd-aa633130914a.png">

Expected behavior: 

<img width="579" alt="Screen Shot 2022-11-15 at 4 15 15 PM" src="https://user-images.githubusercontent.com/14111627/202052226-92aa5d3f-de0a-4ad4-9180-debe17f4971b.png">

**Comment by theonlydaleking** [comment] 2023-01-27 00:51
FWIW, `console.log()` will work with 

`turbo run dev` (But i think caching is disabled?) 

but it will not work currently with 

`next dev --turbo`

**Comment by briangershon** [comment] 2023-02-06 02:58
Duplicate of #3155

**Comment by padmaia** [comment] 2023-03-20 20:17
This one should be fixed in Next.js 13.2.0

**Closed** 2023-03-20 20:17 UTC
Labels: kind: bug, area: turbopack

**Comment by FrancescoSaverioZuppichini** [comment] 2023-07-13 20:31
same here, cannot see api logs

**Comment by jvcjunior** [comment] 2023-10-05 21:39
Same here yet!!

**Comment by suyanksaraswat** [comment] 2024-06-04 20:00
any update on this?
