### ISSUE TITLE
Package scripts are ran in the wrong packages during task execution

### ISSUE THREAD

**Issue by vladfrangu** [vercel/turbo#1801] opened 2022-08-29 13:47 UTC
### What version of Turborepo are you using?

1.4.3

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Mac

### Describe the Bug

We've encountered this issue several times in our repository (https://github.com/apify/crawlee) where even on a fresh install turborepo runs the wrong script in the wrong package.

Sometimes, running a clean install + removing all .turbo folders fixes the issue, but that is not always the case. Sometimes it takes several attempts, and even using `--force` doesn't always solve it. This can cause issues when locally developing as running build scripts can end up not working, slowing us down.

I also don't know if there's any way to debug why this happens (or make turborepo give more in-depth information), or if its a package manager issue. Sometimes even running it again makes it solve itself but after a while it repeats.

### Expected Behavior

Turborepo should execute the scripts in the right package, and not somehow run the same script across two different packages that have different build scripts for example.

### To Reproduce

I don't have exact reproduction samples, but its easy to encounter on https://github.com/apify/crawlee even after a fresh install with `npm ci`.

A fresh clone, npm ci, and npm run build throws an error because the scripts are ran in the wrong package.

Sometimes I've also encountered this just by updating dependencies or changing git branches.

**Comment by mehulkar** [comment] 2023-12-09 07:03
Are you still running into this @vladfrangu? I see you're on the latest version of turbo in your repo now. Can you say which tasks you're running to reproduce and what you mean by "run in the wrong package"?

**Comment by vladfrangu** [comment] 2023-12-09 10:33
Hey! To be honest, I've completely forgot about this issue ever since we moved to yarn as our package manager.

I'd have to try to replicate this again by moving the monorepo to npm, but even then it was super intermittent and inconsistent.

To clarify what I meant by that "run in the wrong package", our build scripts across our packages include some extra node scripts after the main build. Not all packages have the same extras in their build scripts, but what we were seeing is that turbo was trying to run the same one build script across several packages (each having different build scripts) which caused crashes. 

More concretely, if package A had `build: tsc && node ../something.js` and package B had `build: tsc && node ../something.js && node ../somethingelse.js`, sometimes turbo would run package B's script in package A, or vice versa (note that we've only encountered this on npm, and have had no issues since moving to yarn)

**Comment by mehulkar** [comment] 2023-12-11 20:25
Interesting, thanks for the report. I am going to guess this has something to do with how `npm` resolved relative imports? Since it doesn't reproduce with `yarn` and I haven't seen any other bug reports around this, I'm going to close this down!

**Closed by mehulkar** 2023-12-11 20:25 UTC
Labels: kind: bug, needs: reproduction, needs: author input, owned-by: turborepo
