### ISSUE TITLE
[turborepo] Creating a new repo eslint fails

### ISSUE THREAD

**Issue by macutko** [vercel/turbo#4348] opened 2023-03-27 07:44 UTC
### What version of Turborepo are you using?

latest

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Linux

### Describe the Bug

When I follow the tutorial to create a monorepo, the IDE then complains that eslint fails and it cannot read the custom config. In the details it reads

Error: Cannot find module 'next/babel'

### Expected Behavior

To work out of the box

### To Reproduce

Follow the guide to create a monorepo

**Comment by macutko** [comment] 2023-03-27 12:51
I was just watching a video about turbo repo and this guy answered it and briefly mentions how to fix it! I need to try this. Anyways, it would be nice to have this in the docs (or did I miss it?) .

https://youtube.com/clip/UgkxZ_00GQz6JhVmDJgWj5jaYE-QPW51tuuS

**Comment by macutko** [comment] 2023-03-27 15:46
I tried installing next globally and now it complians 

`SyntaxError: Failed to load plugin 'turbo' declared in '.eslintrc.js » eslint-config-custom » eslint-config-turbo': Unexpected token '?'`

**Comment by j-panasiuk** [comment] 2023-03-30 08:52
Encountered the same problem.
I follow installation instructions for a new monorepo and the `lint` command fails when using *pnpm* (works fine with npm). Same thing happens with cloned example repos.

```
ui:lint: Oops! Something went wrong! :(
ui:lint: 
ui:lint: ESLint: 7.32.0
ui:lint: 
ui:lint: Error: Cannot read config file: .../packages/eslint-config-custom/index.js
ui:lint: Error: Cannot find module 'next/babel'
```

**Comment by wentaoxu415** [comment] 2023-04-01 06:52
Encountered the same problem.

Looks like `next/babel` module is accessible only if you have installed `next` package, which is currently not declared as a dependency in any `package.json`.

Meanwhile, #4160 PR has introduced the `next/babel` dependency. Once this change is reverted, the issue goes away.

**Comment by anthonyshew** [comment] 2023-04-02 19:24
Looks like we're playing whack-a-mole with ESLint, specifically in a `pnpm` repo. The configuration works great in a `yarn` repo in my experiments.

Checking my VSCode extension logs, I found a "can't resolve `next/babel`", leading me to comment out
```
 presets: [require.resolve("next/babel")],
```
from `eslint-config-custom`. My gut is that `pnpm`'s module resolution strictness is the culprit here since `next/babel` isn't installed to the `eslint-config-custom` workspace, 

Of course, this brings back the error that @tknickman resolved in #4160:
<img width="959" alt="CleanShot 2023-04-02 at 11 57 55@2x" src="https://user-images.githubusercontent.com/35677084/229373137-e8319f48-00d9-46ba-8b3f-51d861442ffc.png">

But I do get my linting errors back now and ESLint isn't crashing:
<img width="1019" alt="CleanShot 2023-04-02 at 11 58 45@2x" src="https://user-images.githubusercontent.com/35677084/229373185-260a4c39-eb05-409e-92a8-fa6041e699b0.png">

Last part of my experimentation: If I install `next` to `eslint-config-custom` with the preset uncommented, everyone is happy. This isn't a real solution to this problem - but it does confirm the module resolution hypothesis.

**Comment by kirkstrobeck** [comment] 2023-04-23 13:21
Easy to reproduce

1. `pnpm dlx create-turbo@latest`
2. open VS Code
3. See eslint output panel

**Comment by frankda** [comment] 2023-05-04 12:29
> Encountered the same problem.
> 
> Looks like `next/babel` module is accessible only if you have installed `next` package, which is currently not declared as a dependency in any `package.json`.
> 
> Meanwhile, #4160 PR has introduced the `next/babel` dependency. Once this change is reverted, the issue goes away.

What @wentaoxu415 said makes sense. For me, get rid of it by installing `next` in `eslint-config-custom` by running `pnpm add next --filter eslint-config-custom` in root directory

**Comment by vanvilecks** [comment] 2023-06-29 11:13
how do I end up correcting this error?

```
Cannot read config file: /Users/vanvilecks/projects/foo/bar/packages/eslint-config/index.js
Error: Cannot find module 'next/babel'
Require stack:
- /Users/vanvilecks/projects/foo/bar/packages/eslint-config/index.js
- /Users/vanvilecks/projects/foo/bar/node_modules/@eslint/eslintrc/dist/eslintrc.cjs
- /Users/vanvilecks/projects/foo/bar/node_modules/eslint/lib/cli-engine/cli-engine.js
- /Users/vanvilecks/projects/foo/bar/node_modules/eslint/lib/eslint/eslint.js
- /Users/vanvilecks/projects/foo/bar/node_modules/eslint/lib/eslint/index.js
- /Users/vanvilecks/projects/foo/bar/node_modules/eslint/lib/api.js
- /Users/vanvilecks/projects/foo/bar/apps/web/node_modules/next/dist/lib/eslint/runLintCheck.js
- /Users/vanvilecks/projects/foo/bar/apps/web/node_modules/next/dist/cli/next-lint.js
- /Users/vanvilecks/projects/foo/bar/apps/web/node_modules/next/dist/lib/commands.js
- /Users/vanvilecks/projects/foo/bar/apps/web/node_modules/next/dist/bin/next
Referenced from: /Users/vanvilecks/projects/foo/bar/apps/web/.eslintrc.js

```

custom eslint-config

```JS
module.exports = {
  extends: ["next", "turbo", "prettier"],
  rules: {
    "@next/next/no-html-link-for-pages": "off",
  },
  parserOptions: {
    babelOptions: {
      presets: [require.resolve("next/babel")],
    },
  },
};
```

But if you set next to eslint-custom, then the following error is shown:

```BASH
Failed to load parser './parser.js' declared in '.eslintrc.js » @bar/eslint-config » eslint-config-next': Cannot find module 'next/dist/compiled/babel/eslint-parser'
Require stack:
- /Users/vanvilecks/projects/foo/bar/node_modules/eslint-config-next/parser.js
- /Users/vanvilecks/projects/foo/bar/node_modules/@eslint/eslintrc/dist/eslintrc.cjs
```
couldn't find any other way to run eslint in a package. This way doesn't work, help fix it please

**Comment by thevuong** [comment] 2023-08-22 03:42
If you use `pnpm`.
In the root directory of the project you create a file `.npmrc` with its contents and reinstall the project.

```
public-hoist-pattern[]=next
```

**Comment by filipekiss** [comment] 2023-08-22 12:42
> If you use `pnpm`. In the root directory of the project you create a file `.npmrc`
> 
> ```
> public-hoist-pattern[]=next
> ```
> 
> and reinstall the project.

I changed this and nothing else and it worked. Hoisting is the easiest solution here. Thanks @thevuong

**Comment by tknickman** [comment] 2023-08-22 15:06
This should be fixed in https://github.com/vercel/turbo/pull/5775 (without the need to manually hoist)

You can test this now via:

```
npx create-turbo@latest -e https://github.com/vercel/turbo/tree/tomknickman/turbo-1233-fix-basic-example-lint -p examples/basic
```

**Closed** 2023-08-22 16:39 UTC
Labels: kind: bug, needs: triage

**Comment by tknickman** [comment] 2023-08-22 17:16
Now available via `npx create-turbo@latest`
