### ISSUE TITLE
[turbopack] Non matching path (conversation) provided for /(routes)/conversation

### ISSUE THREAD

**Issue by salmansheri** [vercel/turbo#5589] opened 2023-07-22 10:48 UTC
### What version of Next.js are you using Turbopack in?

13.4.11

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Windows

### Describe the Bug

Non matching path (conversation) provided for /(routes)/conversation

### Expected Behavior

Starting dev server

### To Reproduce

dev server is not starting

### Reproduction Repo

https://github.com/salmansheri/ai-saas

**Comment by AmeenJalali** [comment] 2023-07-24 04:56
Have the same problem after upgrade next.js to v13.4.12.

**Comment by salmansheri** [comment] 2023-07-24 14:17
yes 

Non matching path (dashboard) provided for /(routes)/dashboard

Debug info:
- Execution of <NodeRenderContentSource as GetContentSourceContent>::get failed
- Non matching path (dashboard) provided for /(routes)/dashboard

**Comment by timneutkens** [comment] 2024-02-09 11:17
This is likely fixed, since you didn't provide a minimal reproduction I'm unable to run the provided reproduction, can you try again with `npm install next@canary`? I'll close the issue for now as there hasn't been activity for many months, if it still doesn't work let me know and we can re-open the issue. Thanks!

**Closed by timneutkens** 2024-02-09 11:17 UTC
Labels: kind: bug, needs: triage, owned-by: turbopack
