### ISSUE TITLE
[Turborepo] Permanently disable turbod

### ISSUE THREAD

**Issue by CreativeTechGuy** [vercel/turbo#5971] opened 2023-09-17 04:42 UTC
### Which project is this feature idea for?

Turborepo

### Describe the feature you'd like to request

It seems that every time turbo runs a command, it tries to start the daemon if it's not already running. I'm not a fan of things running on my computer in the background outside of my control. It should be up to the user if they want the slight performance boost of a daemon (which may or may not be noticeable depending on the computer and project), or if they want to have something run for 4 hours after having last run a turbo command.

It also makes it much more annoying to clean a project (delete all regeneratable files: node_modules, dist, coverage, .turbo, etc) since node_modules includes files which cannot be deleted since they are currently running.

### Describe the solution you'd like

It'd be great to have some way, possibly a `turbo.json` setting, which is the equivalent of running every command with `--no-daemon`.

### Describe alternatives you've considered

The existing `--no-daemon` flag requires you to add it to every command run. If I never want the daemon to start, then I need to remember to add that flag to every command forever.

<sub>[TURBO-1387](https://linear.app/vercel/issue/TURBO-1387/[turborepo]-permanently-disable-turbod)</sub>

**Comment by arlyon** [comment] 2023-09-25 11:23
Hey!

I think this would be a reasonable opt-out setting to include either per-repo or systemwide. I will bring it up today and come back to you about timelines.

Cheers

Alex

**Comment by mehulkar** [comment] 2023-10-20 19:19
Closing as dupe of #3455

**Closed by mehulkar** 2023-10-20 19:19 UTC
Labels: story, linear: turbo, owned-by: turborepo
