### ISSUE TITLE
[turborepo] : Why do I set up a great effect?

### ISSUE THREAD

**Issue by blockmood** [vercel/turbo#5259] opened 2023-06-09 09:43 UTC
### What version of Turborepo are you using?

latest

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

![1686303765389](https://github.com/vercel/turbo/assets/22879524/819a0246-fc90-48ed-a7f4-3700ad05dd6c)
![1686303841316](https://github.com/vercel/turbo/assets/22879524/f4578f70-75f5-406c-b7be-b311e12140ae)

### Expected Behavior

no error

### To Reproduce

![1686303765389](https://github.com/vercel/turbo/assets/22879524/bb8d9982-d012-47c5-b25d-e1cd69ff944b)

**Comment by tknickman** [comment] 2023-06-12 13:25
This looks like an issue with pnpm workspaces setup and not turbo.  

However, we could help nail down this issue pretty quickly if you could provide a small reproduction. 

That being said, there are a few things to check:

1. Have you installed `math-helpers` in your consuming app ([docs](https://turbo.build/repo/docs/handbook/sharing-code/internal-packages#3-import-the-package))? 
2. Are you using the `workspace:` syntax as required by pnpm?
3. Are you exporting the add function from your packages `index.ts`?
4. Since this package isn't being built, are including this internal package in `transpileModules` of your `next.config.js` ([docs](https://turbo.build/repo/docs/handbook/sharing-code/internal-packages#6-configuring-your-app))?


I'm going to close this as it isn't a problem with `turbo`, but hopefully something there helps!

**Closed by tknickman** 2023-06-12 13:25 UTC
Labels: kind: bug, area: turborepo, needs: triage
