### ISSUE TITLE
Turbo run start on Azure Linux App Service returns 'Cannot find module '../node-platform'' error

### ISSUE THREAD

**Issue by HQ92** [vercel/turbo#1806] opened 2022-08-30 14:30 UTC
### What version of Turborepo are you using?

1.4.3

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Linux

### Describe the Bug

I am trying to run a pruned turborepo app on an Azure Linux App Service. When the server tries to start the app using 'yarn run start' I receive an error where turbo tries to import node-platform but this fails. I can see that node-platform.js exists within the folder 'node_modules/turbo/', but the binary for turbo is being called from 'node_modules/.bin/turbo'.

<img width="726" alt="image" src="https://user-images.githubusercontent.com/9061823/187464325-05f08908-b15f-4ca8-b2e1-14efeb48d404.png">

### Expected Behavior

I would expect the app service to start as it does on a local system.

### To Reproduce

1. Simple turborepo setup with a react app.
2. Github action to install, build and deploy to Azure.
3. Azure App service that does not try to build app, just tries to run it using the yarn version included in yarnrc and .yarn.

I am using Node 16 and Yarn 1.22.19. Turbo 1.4.3.

**Comment by HQ92** [comment] 2022-08-30 16:15
The only way I've found around it is by specifying the full path for the turbo module. So instead of 'turbo run start', 'node ./node_modules/turbo/bin/turbo run start' works.

**Comment by anthonyshew** [comment] 2024-02-05 04:59
Seeing that this issue is quite old. I know we've changed some of the things we do to detect the binary's installation since then so I'll close this. If you're still seeing this problem, please open up a fresh issue with a reproduction with the latest canary!

**Closed by anthonyshew** 2024-02-05 04:59 UTC
Labels: needs: triage, owned-by: turborepo
