### ISSUE TITLE
[Turbopack] tsconfig is not parseable: invalid JSON

### ISSUE THREAD

**Issue by anhdd-kuro** [vercel/turbo#2489] opened 2022-10-29 14:36 UTC
### What version of Turbopack are you using?

nextjs 13.0.0

### What package manager are you using / does the bug impact?

Yarn v2/v3 (node_modules linker only)

### What operating system are you using?

Mac

### Describe the Bug

`next dev` started normally but when run `next dev --turbopack` the "tsconfig is not parseable" error occur
my tsconfig.json

### Expected Behavior

Parse Tsconfig normally

### To Reproduce

My tsconfig.json
The problem is line paths "@/*": { ["src/*"] }

```json
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "@/*": ["src/*"],
    },
    "target": "es6",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "types": ["vitest/globals", "@testing-library/jest-dom", "vite-plugin-svgr/client"]
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx"],
  "exclude": ["node_modules"]
}
```

**Comment by a-coruble** [comment] 2022-10-29 16:07
I believe there was an issue with TSConfig trailing commas ([link](https://github.com/vercel/turbo/issues/2412)) that was fixed by changing the JSON parsing in [this PR](https://github.com/vercel/turbo/pull/2429). I'm wondering if this fixes your issue?

**Comment by jridgewell** [comment] 2022-10-29 17:41
Hi @anhdd-kuro! I agree with @a-coruble here, this was caused by the trailing comma directly after the `["src/*"],` in the `path` field. It is fixed by https://github.com/vercel/turbo/pull/2429, and should be part of the next Next canary.

**Closed** 2022-10-29 17:41 UTC
Labels: kind: bug, area: turbopack
