### ISSUE TITLE
Docs: Typo for TURBO_PREFLIGHT env?

### ISSUE THREAD

**Issue by EloB** [vercel/turbo#7752] opened 2024-03-18 12:27 UTC
### What is the improvement or update you wish to see?

I wasn't able to get `TURBO_PREFLIGHT` working.

Is this a typo in the documentation?
https://github.com/vercel/turbo/blob/39bb0bd20b5bbb608a633a50236b4ffad8759061/docs/pages/repo/docs/reference/command-line-reference/run.mdx#L415

I saw this looking in the code.
https://github.com/vercel/turbo/blob/39bb0bd20b5bbb608a633a50236b4ffad8759061/crates/turborepo-lib/src/config.rs#L131

### Is there any context that might help us understand?

I think the above is pretty clear but I've created a self hosted solution and using that to bypass limitations. So I manually had to use `--preflight` everywhere.
https://github.com/EloB/turborepo-remote-cache-lambda

**Comment by anthonyshew** [comment] 2024-03-18 13:51
Closing as duplicate of #7753

**Closed by anthonyshew** 2024-03-18 13:51 UTC
