### ISSUE TITLE
[turborepo] pnpm: cannot find module 'turbo'

### ISSUE THREAD

**Issue by nhducit** [vercel/turbo#3317] opened 2023-01-14 15:52 UTC
### What version of Turborepo are you using?

1.7.0

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

cannot install turborepo with pnpm in docker
```
#22 56.30 .../.pnpm/turbo@1.7.0/node_modules/turbo postinstall: [turbo] Failed to find package "turbo-linux-arm64" on the file system
...
Error: Cannot find module 'turbo'
```

### Expected Behavior

pnpm install turbo without error

### To Reproduce

check this repro repo at these branches
- yarn
https://github.com/nhducit/turbo-pnpm-bug/tree/main
- pnpm
https://github.com/nhducit/turbo-pnpm-bug/tree/pnpm
- pnpm via npm
https://github.com/nhducit/turbo-pnpm-bug/tree/pnpm-via-npm

## yarn
- clone the with-docker example https://github.com/vercel/turbo/tree/main/examples/with-docker
- docker build success
- [repro repo](https://github.com/nhducit/turbo-pnpm-bug)

## pnpm via curl/wget
- migrate the project to pnpm
- docker build failed at the pnpm installation step and got this error message. check the full build log [here](https://github.com/nhducit/turbo-pnpm-bug/blob/pnpm/build.log)
- [repro repo](https://github.com/nhducit/turbo-pnpm-bug/tree/pnpm)
```
#22 56.30 .../.pnpm/turbo@1.7.0/node_modules/turbo postinstall: [turbo] Failed to find package "turbo-linux-arm64" on the file system
#22 56.31 .../.pnpm/turbo@1.7.0/node_modules/turbo postinstall: This can happen if you use the "--no-optional" flag. The "optionalDependencies"
#22 56.31 .../.pnpm/turbo@1.7.0/node_modules/turbo postinstall: package.json feature is used by turbo to install the correct binary executable
#22 56.31 .../.pnpm/turbo@1.7.0/node_modules/turbo postinstall: for your current platform. This install script will now attempt to work around
#22 56.31 .../.pnpm/turbo@1.7.0/node_modules/turbo postinstall: this. If that fails, you need to remove the "--no-optional" flag to use turbo.
#22 56.31 .../.pnpm/turbo@1.7.0/node_modules/turbo postinstall: node:internal/modules/cjs/loader:1039
#22 56.31 .../.pnpm/turbo@1.7.0/node_modules/turbo postinstall:   const err = new Error(message);
#22 56.31 .../.pnpm/turbo@1.7.0/node_modules/turbo postinstall:               ^
#22 56.31 .../.pnpm/turbo@1.7.0/node_modules/turbo postinstall: Error: Cannot find module 'turbo'
#22 56.31 .../.pnpm/turbo@1.7.0/node_modules/turbo postinstall: Require stack:
```

## install pnpm via npm
- docker build pnpm installation step success and got another error but I think it's not related to turbo anymore
- [repro repo](https://github.com/nhducit/turbo-pnpm-bug/tree/pnpm-via-npm)

### Reproduction Repo

https://github.com/nhducit/turbo-pnpm-bug/tree/main

## Related error 
https://github.com/vercel/turbo/issues/2959
https://github.com/vercel/turbo/issues/824

## Suggestion
After we fixed this bug, let's add an example that uses docker + pnpm like the current [with-docker](https://github.com/vercel/turbo/tree/main/examples/with-docker) example

**Comment by bibblebabl** [comment] 2023-01-18 17:41
I suppose this can also be fixed by adding another example with `pnpm` in `with-docker`. I have already mentioned this several times, but I also had problems with using prune.

**Comment by tknickman** [comment] 2023-01-19 18:51
Hey @nhducit, thanks for the report. it looks like there's an issue with pnpm deciding which optional dependencies to install. When on alpine ARM64, it's installing [turbo-linux-64](https://www.npmjs.com/package/turbo-linux-64) when it should be installing [turbo-linux-arm64](https://www.npmjs.com/package/turbo-linux-arm64). 

This can be fixed for now by installing turbo using the [pnpm `--force` option](https://pnpm.io/cli/install#--force). According to the docs this will "Install all optionalDependencies even they don\'t satisfy the current environment(cpu, os, arch)".

I just tested this with your reproduction repo and it's able build successfully. 

Also it's worth noting you only need to use `--force` for turbo here, so I would recommend using global turbo everywhere (uninstall it as a dependency in your app, and install it once globally using `--force`)

I'm taking a deeper look into why this is happening to see if we can get a fix together either on our end or with pnpm.

**Comment by tknickman** [comment] 2023-01-19 21:20
Hey @nhducit this issue is coming from the install method you're using pnpm. 

You're installing via wget for Alpine as [recommended in the docs](https://pnpm.io/installation#on-alpine-linux), however, you can also just install via `npm` as this is installed on alpine by default.

When installing `pnpm` with `npm`, the `turbo` install works fine. Here's an example Dockerfile:

```
FROM node:18-alpine AS builder

# Update
RUN apk add --no-cache libc6-compat
RUN apk update

# Install pnpm
RUN npm install -g pnpm

# Configure pnpm global
ENV PNPM_HOME=/pnpm-test/.pnpm
ENV PATH=$PATH:$PNPM_HOME

# Set working directory
WORKDIR /pnpm-test

# Install, and run turbo
RUN pnpm install turbo@latest --global
CMD turbo --version
```

I'll file an issue on the pnpm side to track this. But hopefully this unblocks you for now

**Closed by tknickman** 2023-01-19 21:20 UTC
Labels: kind: bug, area: turborepo

**Comment by tknickman** [comment] 2023-01-20 14:24
Looks like pnpm just put up a PR to resolve this issue: https://github.com/pnpm/get.pnpm.io/pull/30
