### ISSUE TITLE
A task that does not have `persistent: true` can not be scrolled.

### ISSUE THREAD

**Issue by MickL** [vercel/turbo#8426] opened 2024-06-11 14:51 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

-

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Mac

### Which canary version will you have in your reproduction?

2.0.3

### Describe the Bug

A task that does not have `persistent: true` can not be scrolled. This is because first the user needs to enter the task by pressing enter before it can be scrolled. Otherwise scrolling affects the sidebar.

Suggested solution:

Dont scroll the sidebar with the mousewheel / trackpad

- Scroll activated tasks without the need to "enter" it first

### Expected Behavior

-

### To Reproduce

-

**Comment by MickL** [comment] 2024-06-11 14:52
_Offtopic: I took me about one hour to write #8419 and you just closed it AND locked the conversation on it. Why dont you create new issues out of it instead of giving me another hour of work?_

**Comment by chris-olszewski** [comment] 2024-06-11 19:35
I'm able to scroll non-`persistent` tasks without hitting enter to interact with the task.

https://github.com/vercel/turbo/assets/4131117/fae1d695-1712-413c-be9c-9c39ddc3f707



Can you provide a reproduction or some additional details on your machine? e.g. term,shell,OS

**Comment by MickL** [comment] 2024-06-11 20:13
I just tried iTerm and it seems to work. This might be specific to Webstorm: When I scroll it toggles throught the items in the sidebar

**Comment by anthonyshew** [comment] 2024-06-11 21:14
Should we close in favor of #8427?

**Comment by MickL** [comment] 2024-06-11 21:56
I dont think they are related too much? This one is about that scrolling goes through the sidebar items instead of the current task, #8427 is about that scrolling is buggy. Maybe they are fixed with the same thing tho.

**Comment by anthonyshew** [comment] 2024-06-11 22:20
Ah, I see, I missed that this was about the sidebar. Separate issue indeed!

**Comment by chris-olszewski** [comment] 2024-06-12 21:27
Closing in favor of #8427 as this is caused by Webstorm changing scroll actions into arrow keys not anything on our end. See https://github.com/vercel/turbo/issues/8427#issuecomment-2161678562 for more details

**Closed by chris-olszewski** 2024-06-12 21:27 UTC
Labels: kind: bug, owned-by: turborepo
