### ISSUE TITLE
[turborepo] Heroku build failing on v1.7

### ISSUE THREAD

**Issue by pete-willard** [vercel/turbo#3598] opened 2023-02-02 11:27 UTC
### What version of Turborepo are you using?

1.7.2

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Linux

### Describe the Bug

After updating to 1.7.2 I'm unable to build my app on Heroku (Heroku-22 stack).

`thread 'main' panicked at 'Failed to execute turbo.: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', crates/turborepo/src/main.rs:50:10`

Full stacktrace: https://pastebin.com/v67Z624V

### Expected Behavior

Builds should pass like on v1.6.3 which I'm downgrading to for now.

### To Reproduce

Attempt to build a node app with turbo v1.7.2 on Heroku

**Comment by chris-olszewski** [comment] 2023-02-02 21:32
It looks like one of our executables isn't getting the correct permissions set. Are you doing anything out of the ordinary with how you're installing turbo?

**Comment by pete-willard** [comment] 2023-02-03 08:39
Nope, Turbo is added as a project dependency and is installed along with the rest via PNPM. No tweaks were applied whatsoever. Everything installs fine, here's the [complete build log](https://pastebin.com/HGpsLWTj). Rolling back to 1.6.3 helped immediately without any other changes to the environment.

**Comment by chris-olszewski** [comment] 2023-02-06 20:55
Could you get me the build log with `-vv` passed to the turbo command? I'm guessing that [the buildpack](https://github.com/TheSecurityDev/heroku-buildpack-nodejs-pnpm) is doing something that we're not expecting and I'm hoping those logs will give a better picture of where the binaries are on disk.

**Comment by nicotu01** [comment] 2023-02-14 06:49
Hello, I am encountering the same error.
Here are my logs with `-vv` option : 
```
[DEBUG] turborepo_lib::shim: Global turbo version: 1.7.4
[DEBUG] turborepo_lib::shim: Local turbo version: 1.7.4
[DEBUG] turborepo_lib::shim: Running local turbo binary in /home/xxx/project/node_modules/.bin/turbo

[DEBUG] turborepo_lib::shim: supports_skip_infer_and_single_package true
thread 'main' panicked at 'Failed to execute turbo.: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', crates/turborepo/src/main.rs:50:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
 ELIFECYCLE  Command failed with exit code 101.
 ELIFECYCLE  Command failed with exit code 1.
 ```

**Comment by nicotu01** [comment] 2023-02-14 07:07
Dowgrade to turbo@1.6.x works for me : `pnpm i -D -w turbo@1.6.x`

**Comment by pete-willard** [comment] 2023-02-14 08:19
Sorry for the delayed response Chris. I've just bumped to 1.7.4 and triggered a build - which passed. I've then retried on the same branch and it crashed again. Here's the new log: https://pastebin.com/ZBBWqHU2

**Comment by gsoltis** [comment] 2023-02-16 23:43
Odd that it only happened the second time. Do you know if heroku does anything with file permissions of binaries in `node_modules`?

**Comment by emko** [comment] 2023-02-22 22:12
same issue with 1.8.2

**Comment by yuritomanek** [comment] 2023-02-24 13:25
I was having the same issue with 1.8.2, downgraded to 1.8.1 and it works again. 🤷

**Comment by sneko** [comment] 2023-03-06 13:59
Using `v1.6.3` for a month is my solution.

@chris-olszewski are you aware of an executable change Vercel did between `v1.6.x` and `v1.7.x`? I tried to look at the diff betwen those tags but they are too many things and I don't know well how `turbo` is structured :D 

Thank you,

**Comment by wujekbogdan** [comment] 2023-03-07 11:24
I'm experiencing the same issue with turbo `1.8.3`. It runs fine locally, but fails when I run it in a Docker container. I'm using the `node:18.14.2-alpine3.16` image.

In my case downgrading to `v.1.6.3` doesn't solve the problem.

**Comment by wujekbogdan** [comment] 2023-03-10 08:14
It turns out the error is caused by the missing `libc6-compat` library (depending on your distro the package might have a different name).

This isn't a problem with turbo, it's a consequence of using Rust. Its binaries depend on this lib.

**Comment by nathanhammond** [comment] 2023-03-14 16:35
This could possibly be fixed by #4123.

**Comment by pete-willard** [comment] 2023-03-21 07:51
I've test ran 1.8.4-canary.6 and it indeed seems to be working. Will confirm after the stable version hits. Thanks!

**Comment by nathanhammond** [comment] 2023-03-21 09:46
I would appreciate if anybody who is experiencing this issue can update to 1.8.5 to see if that addresses their problems.

The change from 4123 is a _bit_ disconnected from what is likely the root cause so I'm not 100% certain that it is a general fix.

I will note that, if this works for @pete-willard I will be closing this issue, locking it, and requesting that everybody else post new issues so we can differentiate the root cause.

**Comment by emko** [comment] 2023-03-21 18:04
> I would appreciate if anybody who is experiencing this issue can update to 1.8.5 to see if that addresses their problems.
> 
> The change from 4123 is a _bit_ disconnected from what is likely the root cause so I'm not 100% certain that it is a general fix.
> 
> I will note that, if this works for @pete-willard I will be closing this issue, locking it, and requesting that everybody else post new issues so we can differentiate the root cause.

just tested 1.8.5 seems to have fix this issue for me

**Comment by nathanhammond** [comment] 2023-03-22 08:29
Since @pete-willard reports that it worked on a `canary` & @emko notes that it works on `latest` I'm going to preemptively close, and lock after I hear back. 👍

**Closed by nathanhammond** 2023-03-22 08:29 UTC
Labels: kind: bug, needs: author input, area: turborepo

**Comment by pete-willard** [comment] 2023-04-12 13:17
Apologies for the delayed response, Nathan. We haven't had an issue since updating. Go ahead and lock.
