### ISSUE TITLE
new TUI doesnt allow pointer events

### ISSUE THREAD

**Issue by Huilensolis** [vercel/turbo#8478] opened 2024-06-13 18:53 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

not necesary for this issue, just create a monorepo and run a task

### What package manager are you using / does the bug impact?

npm, pnpm, Yarn v2/v3/v4 (node_modules linker only)

### What operating system are you using?

Linux

### Which canary version will you have in your reproduction?

2.0.2

### Describe the Bug

If you have a monorepo with turborepo and next js, when you run `turbo dev`, you can't click the port that next js exposes for development, which makes it annoying.

same with errors: if your server throws an error, you cant select it with your mouse and paste it on google to search its solution.

### Expected Behavior

- [ ] allow text selection
- [ ] allow click links

### To Reproduce

create a monorepo
create a script

run `turbo <script>`
try to select text

**Comment by anthonyshew** [comment] 2024-06-13 18:55
Thanks for the report! Duplicate of #8372. Please upvote there so we can capture your interest on it. 👍

**Closed by anthonyshew** 2024-06-13 18:55 UTC
Labels: kind: bug, needs: triage, owned-by: turborepo
