### ISSUE TITLE
[turborepo] Full paths in outputs do not copy artefacts from cache.

### ISSUE THREAD

**Issue by JanKaifer** [vercel/turbo#3185] opened 2023-01-05 14:16 UTC
### What version of Turborepo are you using?

1.6.3

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Linux

### Describe the Bug

When using full path in `outputs` (like "/home/user/code/repo/file") it won't recreate that file on cache hit. It works correctly when specifying just `"file"`.

### Expected Behavior

It should matter if I use fell path or relative path.

### To Reproduce

Clone the repo and try to change the outputs path from relative to absolute (use absolute path that works on your machine).

1. Then run `turbo run test-cp` to create cache.
2. remove `test.out`
3. run `turbo run test-cp` - it should be a cache hit but it won't re-create `test.out`.

### Reproduction Repo

https://github.com/JanKaifer/turbo-outputs-full-path-repro

**Comment by gsoltis** [comment] 2023-01-11 22:33
This is the intended behavior. Turborepo is designed to be able to share cache artifacts among teammates, which means that artifacts need to be expressed in relation to the repository, not in absolute terms on a particular machine.

**Comment by JanKaifer** [comment] 2023-01-12 09:22
Hey, we were trying to create the `turbo.json` programmatically.
I couldn't use local paths because I the inputs were at `/tmp/[long-hash1]-inputs` and outputs were at `/home/user/dev/project/file.tgz`. 

I haven't found anything in the docs or a warning in the command line.
It would save me a lot of time if turbo told me `hey I'm ignoring this because it's not a relative path`.

**Comment by gsoltis** [comment] 2023-01-18 17:32
Thanks for the feedback! I'm going to close this issue, as this is not a bug, but I've filed a ticket to investigate adding a warning or error, and to update our docs to reflect that we expect relative paths in `turbo.json`.

I think you're right, that would definitely help guide users towards the intended setup.

**Closed by gsoltis** 2023-01-18 17:32 UTC
Labels: kind: bug, area: turborepo
