### ISSUE TITLE
[turbopack] Running a NextJs app by using the --turbo flag in the TurboRepo monorepo, causes Error: Next.js package not found

### ISSUE THREAD

**Issue by amerllica** [vercel/turbo#6178] opened 2023-10-15 13:50 UTC
### What version of Turborepo are you using?

1.10.15

### What package manager are you using / does the bug impact?

npm, Yarn v1

### What operating system are you using?

Mac

### Describe the Bug

A fresh install of `TurboRepo` and running the NextJs app by using the `--turbo` flag causes this error:

```
Error: Next.js package not found
```
<details>
  <summary>Full LOG</summary>
  Debug info:
- Execution of get_next_package failed
- Next.js package not found
at withErrorCause (/Users/MacBookPro_ProjectsDirectory/test-next-turborepo/node_modules/next/dist/build/swc/index.js:391:19)
at async EndpointImpl.writeToDisk (/Users/MacBookPro_ProjectsDirectory/test-next-turborepo/node_modules/next/dist/build/swc/index.js:581:20)
at async Object.ensurePage (/Users/MacBookPro_ProjectsDirectory/test-next-turborepo/node_modules/next/dist/server/lib/router-utils/setup-dev.js:922:79)
at async Object.ensurePage (/Users/MacBookPro_ProjectsDirectory/test-next-turborepo/node_modules/next/dist/server/lib/router-server.js:87:24)
at async DevServer.ensurePage (/Users/MacBookPro_ProjectsDirectory/test-next-turborepo/node_modules/next/dist/server/dev/next-dev-server.js:510:9)
at async Object.ensure (/Users/MacBookPro_ProjectsDirectory/test-next-turborepo/node_modules/next/dist/server/dev/next-dev-server.js:163:17)
at async DevRouteMatcherManager.matchAll (/Users/MacBookPro_ProjectsDirectory/test-next-turborepo/node_modules/next/dist/server/future/route-matcher-managers/dev-route-matcher-manager.js:94:13)
at async DevRouteMatcherManager.match (/Users/MacBookPro_ProjectsDirectory/test-next-turborepo/node_modules/next/dist/server/future/route-matcher-managers/default-route-matcher-manager.js:159:26)
at async DevServer.handleCatchallRenderRequest (/Users/MacBookPro_ProjectsDirectory/test-next-turborepo/node_modules/next/dist/server/next-server.js:567:27)
at async DevServer.handleRequestImpl (/Users/MacBookPro_ProjectsDirectory/test-next-turborepo/node_modules/next/dist/server/base-server.js:728:17) {
[cause]: [Error: Next.js package not found

Debug info:
- Execution of get_next_package failed
- Next.js package not found] {
code: 'GenericFailure'
}
}
Error: expected next/dist/client/next-dev-turbopack.js to resolve to a module

Debug info:
- Execution of PageEndpoint::client_chunks failed
- expected next/dist/client/next-dev-turbopack.js to resolve to a module
at withErrorCause (/Users/MacBookPro_ProjectsDirectory/test-next-turborepo/node_modules/next/dist/build/swc/index.js:391:19)
at async EndpointImpl.writeToDisk (/Users/MacBookPro_ProjectsDirectory/test-next-turborepo/node_modules/next/dist/build/swc/index.js:581:20)
at async Object.ensurePage (/Users/MacBookPro_ProjectsDirectory/test-next-turborepo/node_modules/next/dist/server/lib/router-utils/setup-dev.js:790:77)
at async Object.ensurePage (/Users/MacBookPro_ProjectsDirectory/test-next-turborepo/node_modules/next/dist/server/lib/router-server.js:87:24)
at async DevServer.ensurePage (/Users/MacBookPro_ProjectsDirectory/test-next-turborepo/node_modules/next/dist/server/dev/next-dev-server.js:510:9)
at async DevServer.findPageComponents (/Users/MacBookPro_ProjectsDirectory/test-next-turborepo/node_modules/next/dist/server/dev/next-dev-server.js:526:17)
at async DevServer.renderErrorToResponseImpl (/Users/MacBookPro_ProjectsDirectory/test-next-turborepo/node_modules/next/dist/server/base-server.js:1804:26)
at async pipe.req.req (/Users/MacBookPro_ProjectsDirectory/test-next-turborepo/node_modules/next/dist/server/base-server.js:1732:30)
at async DevServer.pipeImpl (/Users/MacBookPro_ProjectsDirectory/test-next-turborepo/node_modules/next/dist/server/base-server.js:826:25)
at async DevServer.handleCatchallRenderRequest (/Users/MacBookPro_ProjectsDirectory/test-next-turborepo/node_modules/next/dist/server/next-server.js:638:17)
at async DevServer.handleRequestImpl (/Users/MacBookPro_ProjectsDirectory/test-next-turborepo/node_modules/next/dist/server/base-server.js:728:17) {
[cause]: [Error: expected next/dist/client/next-dev-turbopack.js to resolve to a module

Debug info:
- Execution of PageEndpoint::client_chunks failed
- expected next/dist/client/next-dev-turbopack.js to resolve to a module] {
code: 'GenericFailure'
}
}
Error: Next.js package not found

Debug info:
- Execution of get_next_package failed
- Next.js package not found
at withErrorCause (/Users/MacBookPro_ProjectsDirectory/test-next-turborepo/node_modules/next/dist/build/swc/index.js:391:19)
at async EndpointImpl.writeToDisk (/Users/MacBookPro_ProjectsDirectory/test-next-turborepo/node_modules/next/dist/build/swc/index.js:581:20)
at async Object.ensurePage (/Users/MacBookPro_ProjectsDirectory/test-next-turborepo/node_modules/next/dist/server/lib/router-utils/setup-dev.js:922:79)
at async Object.ensurePage (/Users/MacBookPro_ProjectsDirectory/test-next-turborepo/node_modules/next/dist/server/lib/router-server.js:87:24)
at async DevServer.ensurePage (/Users/MacBookPro_ProjectsDirectory/test-next-turborepo/node_modules/next/dist/server/dev/next-dev-server.js:510:9)
at async Object.ensure (/Users/MacBookPro_ProjectsDirectory/test-next-turborepo/node_modules/next/dist/server/dev/next-dev-server.js:163:17)
at async DevRouteMatcherManager.matchAll (/Users/MacBookPro_ProjectsDirectory/test-next-turborepo/node_modules/next/dist/server/future/route-matcher-managers/dev-route-matcher-manager.js:94:13)
at async DevRouteMatcherManager.match (/Users/MacBookPro_ProjectsDirectory/test-next-turborepo/node_modules/next/dist/server/future/route-matcher-managers/default-route-matcher-manager.js:159:26)
at async DevServer.handleCatchallRenderRequest (/Users/MacBookPro_ProjectsDirectory/test-next-turborepo/node_modules/next/dist/server/next-server.js:567:27)
at async DevServer.handleRequestImpl (/Users/MacBookPro_ProjectsDirectory/test-next-turborepo/node_modules/next/dist/server/base-server.js:728:17) {
[cause]: [Error: Next.js package not found

Debug info:
- Execution of get_next_package failed
- Next.js package not found] {
code: 'GenericFailure'
}
}
Error: expected next/dist/client/next-dev-turbopack.js to resolve to a module

Debug info:
- Execution of PageEndpoint::client_chunks failed
- expected next/dist/client/next-dev-turbopack.js to resolve to a module
at withErrorCause (/Users/MacBookPro_ProjectsDirectory/test-next-turborepo/node_modules/next/dist/build/swc/index.js:391:19)
at async EndpointImpl.writeToDisk (/Users/MacBookPro_ProjectsDirectory/test-next-turborepo/node_modules/next/dist/build/swc/index.js:581:20)
at async Object.ensurePage (/Users/MacBookPro_ProjectsDirectory/test-next-turborepo/node_modules/next/dist/server/lib/router-utils/setup-dev.js:790:77)
at async Object.ensurePage (/Users/MacBookPro_ProjectsDirectory/test-next-turborepo/node_modules/next/dist/server/lib/router-server.js:87:24)
at async DevServer.ensurePage (/Users/MacBookPro_ProjectsDirectory/test-next-turborepo/node_modules/next/dist/server/dev/next-dev-server.js:510:9)
at async DevServer.findPageComponents (/Users/MacBookPro_ProjectsDirectory/test-next-turborepo/node_modules/next/dist/server/dev/next-dev-server.js:526:17)
at async DevServer.renderErrorToResponseImpl (/Users/MacBookPro_ProjectsDirectory/test-next-turborepo/node_modules/next/dist/server/base-server.js:1804:26)
at async pipe.req.req (/Users/MacBookPro_ProjectsDirectory/test-next-turborepo/node_modules/next/dist/server/base-server.js:1732:30)
at async DevServer.pipeImpl (/Users/MacBookPro_ProjectsDirectory/test-next-turborepo/node_modules/next/dist/server/base-server.js:826:25) {
[cause]: [Error: expected next/dist/client/next-dev-turbopack.js to resolve to a module

Debug info:
- Execution of PageEndpoint::client_chunks failed
- expected next/dist/client/next-dev-turbopack.js to resolve to a module] {
code: 'GenericFailure'
}
}
Error: expected next/dist/client/next-dev-turbopack.js to resolve to a module

Debug info:
- Execution of PageEndpoint::client_chunks failed
- expected next/dist/client/next-dev-turbopack.js to resolve to a module
at withErrorCause (/Users/MacBookPro_ProjectsDirectory/test-next-turborepo/node_modules/next/dist/build/swc/index.js:391:19)
at async EndpointImpl.writeToDisk (/Users/MacBookPro_ProjectsDirectory/test-next-turborepo/node_modules/next/dist/build/swc/index.js:581:20)
at async Object.ensurePage (/Users/MacBookPro_ProjectsDirectory/test-next-turborepo/node_modules/next/dist/server/lib/router-utils/setup-dev.js:790:77)
at async Object.getFallbackErrorComponents (/Users/MacBookPro_ProjectsDirectory/test-next-turborepo/node_modules/next/dist/server/lib/router-server.js:99:17)
at async DevServer.getFallbackErrorComponents (/Users/MacBookPro_ProjectsDirectory/test-next-turborepo/node_modules/next/dist/server/dev/next-dev-server.js:553:9)
at async DevServer.renderErrorToResponseImpl (/Users/MacBookPro_ProjectsDirectory/test-next-turborepo/node_modules/next/dist/server/base-server.js:1875:40)
at async pipe.req.req (/Users/MacBookPro_ProjectsDirectory/test-next-turborepo/node_modules/next/dist/server/base-server.js:1732:30)
at async DevServer.pipeImpl (/Users/MacBookPro_ProjectsDirectory/test-next-turborepo/node_modules/next/dist/server/base-server.js:826:25) {
[cause]: [Error: expected next/dist/client/next-dev-turbopack.js to resolve to a module

Debug info:
- Execution of PageEndpoint::client_chunks failed
- expected next/dist/client/next-dev-turbopack.js to resolve to a module] {
code: 'GenericFailure'
}
}
⨯ Error: Next.js package not found

Debug info:
- Execution of get_next_package failed
- Next.js package not found
at withErrorCause (/Users/MacBookPro_ProjectsDirectory/test-next-turborepo/node_modules/next/dist/build/swc/index.js:391:19)
at async EndpointImpl.writeToDisk (/Users/MacBookPro_ProjectsDirectory/test-next-turborepo/node_modules/next/dist/build/swc/index.js:581:20)
at async Object.ensurePage (/Users/MacBookPro_ProjectsDirectory/test-next-turborepo/node_modules/next/dist/server/lib/router-utils/setup-dev.js:946:79)
at async Object.ensurePage (/Users/MacBookPro_ProjectsDirectory/test-next-turborepo/node_modules/next/dist/server/lib/router-server.js:87:24)
at async DevServer.ensurePage (/Users/MacBookPro_ProjectsDirectory/test-next-turborepo/node_modules/next/dist/server/dev/next-dev-server.js:510:9)
at async Object.ensure (/Users/MacBookPro_ProjectsDirectory/test-next-turborepo/node_modules/next/dist/server/dev/next-dev-server.js:163:17)
at async DevRouteMatcherManager.matchAll (/Users/MacBookPro_ProjectsDirectory/test-next-turborepo/node_modules/next/dist/server/future/route-matcher-managers/dev-route-matcher-manager.js:94:13)
at async DevRouteMatcherManager.match (/Users/MacBookPro_ProjectsDirectory/test-next-turborepo/node_modules/next/dist/server/future/route-matcher-managers/default-route-matcher-manager.js:159:26)
at async DevServer.handleCatchallRenderRequest (/Users/MacBookPro_ProjectsDirectory/test-next-turborepo/node_modules/next/dist/server/next-server.js:567:27)
at async DevServer.handleRequestImpl (/Users/MacBookPro_ProjectsDirectory/test-next-turborepo/node_modules/next/dist/server/base-server.js:728:17) {
[cause]: [Error: Next.js package not found

Debug info:
- Execution of get_next_package failed
- Next.js package not found] {
code: 'GenericFailure'
}
}
</details>

But without using the `--turbo` flag it works properly.

### Expected Behavior

Dev build and run the project

### To Reproduce

1. Fresh install of TurboRepo monorepo
2. Run the web NextJs app by using the `--turbo` flag
3. Open the `http://localhost:3000` on your browser
4. `Internal Server Error`
5. Check out the terminal

**Comment by timneutkens** [comment] 2024-02-09 09:06
Since the reproduction steps assume we can run code that is not provided (which we can't if it's not shared) we can't verify if it's fixed or not. Can you try using `npm install next@canary` with `--turbo`? Thanks!

**Comment by timneutkens** [comment] 2024-03-05 14:28
Closing this issue as it can't be investigated further.

**Closed by timneutkens** 2024-03-05 14:28 UTC
Labels: kind: bug, owned-by: turbopack
