### ISSUE TITLE
[turbopack] Error parsing node module tsconfig file - extends doesn't resolve correctly

### ISSUE THREAD

**Issue by B4rsekerDev** [vercel/turbo#2973] opened 2022-12-12 05:11 UTC
### What version of Turbopack are you using?

included in Next 13.0.6

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

I am getting an error while I am trying to use apollo client in client-side component in Next 13.0.6 using Turbopack. 

After I run: 
``` next dev --turbo --show-all ```

I receive:
```
error - [typescript] node_modules/.pnpm/ts-invariant@0.10.3/node_modules/ts-invariant/tsconfig.json
[0]   An issue occurred while parsing a tsconfig.json file.
[0]   extends doesn't resolve correctly
[0] 
[0] warning - [analyze]
[0]   node_modules/.pnpm/@apollo+client@3.7.2_gdcq4dv6opitr3wbfwyjmanyra/node_modules/@apollo/client/cache/inmemory/types.js
[0]     unexpected export *
[0]     export * used with module [project-with-next]/node_modules/.pnpm/@apollo+client@3.7.2_gdcq4dv6opitr3wbfwyjmanyra/node_modules/@apollo/client/cache/inmemory/types.js which has no exports
[0]     Typescript only: Did you want to import only types with `export type * from "..."`?
[0] 
[0]   node_modules/.pnpm/@apollo+client@3.7.2_gdcq4dv6opitr3wbfwyjmanyra/node_modules/@apollo/client/core/types.js
[0]     unexpected export *
[0]     export * used with module [project-with-next]/node_modules/.pnpm/@apollo+client@3.7.2_gdcq4dv6opitr3wbfwyjmanyra/node_modules/@apollo/client/core/types.js which has no exports
[0]     Typescript only: Did you want to import only types with `export type * from "..."`?
[0] 
[0]   node_modules/.pnpm/@apollo+client@3.7.2_gdcq4dv6opitr3wbfwyjmanyra/node_modules/@apollo/client/link/core/types.js
[0]     unexpected export *
[0]     export * used with module [project-with-next]/node_modules/.pnpm/@apollo+client@3.7.2_gdcq4dv6opitr3wbfwyjmanyra/node_modules/@apollo/client/link/core/types.js which has no exports
[0]     Typescript only: Did you want to import only types with `export type * from "..."`?
[0] 
[0]   node_modules/.pnpm/@apollo+client@3.7.2_gdcq4dv6opitr3wbfwyjmanyra/node_modules/@apollo/client/react/types/types.js
[0]     unexpected export *
[0]     export * used with module [project-with-next]/node_modules/.pnpm/@apollo+client@3.7.2_gdcq4dv6opitr3wbfwyjmanyra/node_modules/@apollo/client/react/types/types.js which has no exports
[0]     Typescript only: Did you want to import only types with `export type * from "..."`?
[0] 
[0]   node_modules/.pnpm/@apollo+client@3.7.2_gdcq4dv6opitr3wbfwyjmanyra/node_modules/@apollo/client/utilities/types/IsStrictlyAny.js
[0]     unexpected export *
[0]     export * used with module [project-with-next]/node_modules/.pnpm/@apollo+client@3.7.2_gdcq4dv6opitr3wbfwyjmanyra/node_modules/@apollo/client/utilities/types/IsStrictlyAny.js which has no exports
[0]     Typescript only: Did you want to import only types with `export type * from "..."`?

```

### Expected Behavior

I should be able to run mutations against Graphql API server

### To Reproduce

I used a combination of @apollo/client and codegen to generate mutations used in client side components:

1. Add @apollo/client graphql and codegen:
``` pnpm add @apollo/client graphql && pnpm add -D @graphql-codegen/cli```

2. Setup codegen (apollo + react):
``` pnpm graphql-code-generator init ```

3. Make mutation (app/auth/login/login.graphql):
```
mutation Login($email: String!, $password: String!) {
    login(input: { email: $email, password: $password }) {
        token
    }
}
```

4. Run codegen
``` pnpm codegen ```

5. Use generated mutation inside component (app/auth/login/page.tsx):
```
"use client"
const DEFAULT = { name: string, email: string }

function LoginPage() {
const [credentials] = React.useState<{ name: string, email: string }>(DEFAULT)

const [login] = useLoginMutation()

const submit = () => (login({
variables: credentials
}))

return <button>submit</button>
}
```

Now, after loading the page the error should occur and compilation should fail.

**Comment by productdevbook** [comment] 2022-12-14 05:16
same problem

**Comment by padmaia** [comment] 2023-03-20 21:44
Duplicate of #2682

**Closed by padmaia** 2023-03-20 21:44 UTC
Labels: kind: bug, area: turbopack
