### ISSUE TITLE
[turborepo] turbo prune `${APP_NAME}` --docker doesn't generate `out/full/` directory

### ISSUE THREAD

**Issue by AshtonYoon** [vercel/turbo#6457] opened 2023-11-15 08:39 UTC
### What version of Turborepo are you using?

1.10.14

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

Hello

I wanted to build a app as a docker image, I faced an error.

Here's my part of a Dockerfile

``` Dockerfile
...

FROM base AS builder
RUN apk add --no-cache libc6-compat
RUN apk update

WORKDIR /app
RUN pnpm add --global turbo
COPY . .
RUN turbo prune ${APP_NAME} --docker

FROM base AS installer
RUN apk add --no-cache libc6-compat
RUN apk update
WORKDIR /app

COPY .gitignore .gitignore
COPY --from=builder /app/out/json/ .
COPY --from=builder /app/out/pnpm-lock.yaml ./pnpm-lock.yaml
RUN pnpm install

COPY --from=builder /app/out/full/ .
COPY turbo.json turbo.json

RUN pnpm turbo run build --filter=${APP_NAME}...

...

CMD PORT=3001 node apps/themoney/server.js
```

build with a command `docker-compose -f docker-compose.yml build`
That showing a error message below.

``` docker
=> ERROR [${APP_NAME} installer  8/10] COPY --from=builder /app/out/full/ .  
```
```
failed to solve: cannot copy to non-directory: /var/lib/docker/overlay2/jyeh57zocu3oubs242uhygyyv/merged/app/apps/${APP_NAME}/node_modules/${MY_PACKAGE}
```

**BUT I removed the flag `--docker` in `turbo prune`. and changed `COPY --from=builder /app/out/full/ .` to `COPY --from=builder /app/out/ .`**

**It was worked clearly**

### Expected Behavior

Build a docker image

❌ (failed to build)
```
turbo prune ${APP_NAME} --docker
```
``` Dockerfile
COPY --from=builder /app/out/full/ .
```

✅ (success to build)
```
turbo prune ${APP_NAME}
```
``` Dockerfile
COPY --from=builder /app/out/ .
```

### To Reproduce

https://github.com/AshtonYoon/turbo-prune-docker-reproduce

sample repoduce repo,

clone and run

```
docker compose build
```
<img width="1166" alt="image" src="https://github.com/vercel/turbo/assets/16028154/a53b6d83-b83c-4be2-b4ac-29a243e70e95">

you can see a error message like this

thank you for reading

### Reproduction Repo

https://github.com/AshtonYoon/turbo-prune-docker-reproduce

**Comment by thomasvargiu** [comment] 2023-11-15 10:34
Duplicate of:
- #5462
- #1997

See https://github.com/vercel/turbo/issues/1997#issuecomment-1273565773 to resolve:

Add `**/node_modules` to your `.dockerignore`.

**Comment by chris-olszewski** [comment] 2023-11-15 16:06
Closing in favor of #1997

**Closed by chris-olszewski** 2023-11-15 16:06 UTC
Labels: kind: bug, needs: triage, owned-by: turborepo

**Comment by AshtonYoon** [comment] 2023-11-16 01:13
I has solved by https://github.com/vercel/turbo/issues/1997#issuecomment-1273565773.

Thank you for fast responding!!
