### ISSUE TITLE
[Turbopack] Yarn PnP installs

### ISSUE THREAD

**Issue by arcanis** [vercel/turbo#2369] opened 2022-10-26 10:47 UTC
### Which project is this feature idea for?

Turbopack

*(note: I saw #693, and specifically https://github.com/vercel/turbo/issues/693#issuecomment-1278886166, but that issue was about Turborepo, not Turbopack. I checked with @sokra who confirmed that the goal is for Turbopack to eventually support everything Webpack supports, hence this issue specifically about Turbopack)*

### Describe the feature you'd like to request

Turbopack isn't compatible with Yarn PnP installs, unlike both Webpack and Esbuild. There are two reasons for this:

- Turbopack doesn't implement the PnP resolution (the formal spec is [here](https://yarnpkg.com/advanced/pnp-spec), Esbuild followed it in their [implementation](https://github.com/evanw/esbuild/pull/2451))
- Turbopack doesn't support accessing files from zip archives (see the ["Package Locations" section](https://yarnpkg.com/advanced/pnp-spec#package-locations) of the spec)

### Reproduction

```
yarn create next-app my-app && cd my-app
yarn set version canary
yarn config set nodeLinker pnp
yarn install
yarn next dev
```

### Describe the solution you'd like

Two options:

- Implement the zip fs logic within Turbopack, and make it take into account the `.pnp.data.json` data file as per spec

    - It'd be useful if someone familiar with the Turbopack codebase could share some pointers showing where we can find the relevant sections, and what would be the potential problems

- Allow Node plugins to handle specific file loading and resolution (like Webpack plugins; but then it'd be slower than necessary, and wouldn't be supported natively as it currently is in other bundlers)

### Describe alternatives you've considered

In the meantime users can workaround this problem by reverting to the node-modules linker, but they don't get the PnP benefits anymore (fast installs, ghost dependency protection, semantic erroring, ...), which is often a blocker.

```
yarn config set nodeLinker node-modules
```

**Comment by IhsenBouallegue** [comment] 2023-09-19 18:52
Any updates? This would be pretty awesome, but I assume it's a huge undertaking.

**Comment by arcanis** [comment] 2023-09-19 20:19
Not directly related to Turbopack, but I implemented the PnP resolution algorithm (whose specs are [here](https://yarnpkg.com/advanced/pnp-spec)) as a Rust package, see [here](https://github.com/arcanis/pnp-rust). It's still a bit experimental, but I'm more than open to merge PRs and make it compatible with Turbopack.

**Comment by robertwt7** [comment] 2023-11-24 04:39
Yarn 4 is great, I don't know why vercel doesn't want to implement the PnP resolution. It'll help us a lot in the CI build time and the only package that's not supported right now in my repo is turbo

**Comment by ForsakenHarmony** [comment] 2024-02-14 23:56
Closing as a duplicate of https://github.com/vercel/next.js/issues/42651

**Closed by ForsakenHarmony** 2024-02-14 23:56 UTC
Labels: story, owned-by: turbopack
