### ISSUE TITLE
[turborepo] turbo prune creates a turbo.json that turns off remote caching

### ISSUE THREAD

**Issue by NigelBreslaw** [vercel/turbo#5414] opened 2023-06-28 18:40 UTC
### What version of Turborepo are you using?

1.10.6

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Linux

### Describe the Bug

turbo prune is creating a turbo.json with the following '"remoteCache":{"enabled":true}'. This has the effect of disabling remote caching. I can work around it by moving the projects root turbo.json into the 'full' folder.

I'm using a custom remote cache, not the vercel one.

### Expected Behavior

Prune does not create a turbo.json that stops remote caching

### To Reproduce

n/a

<sub>[TURBO-1501](https://linear.app/vercel/issue/TURBO-1501/[turborepo]-turbo-prune-creates-a-turbojson-that-turns-off-remote)</sub>

**Comment by NicholasLYang** [comment] 2023-06-29 15:21
Hi, thanks for the issue. Just to clarify, prune is creating a turbo json with the enabled field set to true? Because that seems like it should enable remote caching, not disable it. That seems like a potential bug if that's the case.

**Comment by NigelBreslaw** [comment] 2023-06-29 15:23
That's right. But the schema doesn't show enable as a property. Only "signature".

**Comment by NicholasLYang** [comment] 2023-06-29 23:02
Gotcha. Prune is in the middle of being ported to Rust, but I'll tag @chris-olszewski who's our prune expert.

**Comment by chris-olszewski** [comment] 2023-06-30 00:33
Hi @NigelBreslaw, does your root `turbo.json` have a `remoteCache.enabled` set? If that isn't set than turbo defaults to true which is why prune is populating this field in the pruned `turbo.json`. Can you test if remote caching works for `turbo run` on a non-pruned project? Does setting `remoteCache.enabled` to `false` result in your desired behavior?

I do notice that the PR that added the `enable` field to our code didn't update the schema so I'll do that.

**Comment by Klaitos** [comment] 2023-07-04 09:41
We also observed this issue last week,
We forced 
```
    "remoteCache": {
        "enabled": true
    }
```
in turbo.json, the remote caching works after that.

**Comment by Klaitos** [comment] 2023-07-04 10:48
But when we set in turbo.json
```
  "remoteCache": {
        "enabled": true
    }
```
basic tasks which doesn't use `prune`, like `turbo run lint` are unable to use remote caching 😢

**Comment by mehulkar** [comment] 2023-07-06 06:19
Not sure what the problem is exactly, but this config was introduced by me here https://github.com/vercel/turbo/pull/5305

**Comment by chris-olszewski** [comment] 2023-07-20 19:45
Can people experiencing this issue please try out `turbo@1.10.10-canary-0` and see if that solves the problem for them? #5531 made the pruning of `turbo.json` far less invasive and now the only changes should be removing invalid tasks and stripping comments.

**Comment by mehulkar** [comment] 2023-10-20 04:28
- `turbo prune` is adding a `remoteCache.enabled` field to `turbo.json`  and setting it to `true`.

   I cannot actually reproduce this. If the original `turbo.json` has `remoteCache.enabled` configured, it gets copied over correctly. We have an existing test, but I've added a couple more here: https://github.com/vercel/turbo/pull/6226

- Setting `remoteCache.enabled = true` ⚠️ disables ⚠️ remote caching

    I _think_ I was able to reproduce this, but I am not sure. My guess is the reason is the config was not ported over to Rust and is defaulting to false

**Comment by chris-olszewski** [comment] 2024-02-26 19:43
Closing as I'm almost certain this is fixed now with changes to our config parsing.

If you encounter this issue on `1.12.4` or later, please reopen with a reproduction repo.

**Closed by chris-olszewski** 2024-02-26 19:43 UTC
Labels: kind: bug, linear: turbo, owned-by: turborepo
