### ISSUE TITLE
[turborepo] non-monorepo project turbo remote cache on docker build always missed 

### ISSUE THREAD

**Issue by zigang93** [vercel/turbo#2901] opened 2022-12-01 19:02 UTC
### What version of Turborepo are you using?

1.6.3

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

reproduce repo: https://github.com/zigang93/next-with-docker-turbo

run `pnpm i` before start

1. enable turbo remote cache with vercel  `npx turbo login` and `npx turbo link`
2. run docker build command with full plain log: `PROGRESS_NO_TRUNC=1 docker build --no-cache --progress plain -t next-js .`
3. re-run agian, the cache missed.. can notice that hash is always different when each `PROGRESS_NO_TRUNC=1 docker build --progress plain -t next-js .` command run..

but, I can get remote cache from `pnpm build:turbo` 

### Expected Behavior

should be able to remote cache on docker build 

### To Reproduce

reproduce repo: https://github.com/zigang93/next-with-docker-turbo

run `pnpm i` before start

1. enable turbo remote cache with vercel  `npx turbo login` and `npx turbo link`
2. run docker build command with full plain log: `PROGRESS_NO_TRUNC=1 docker build --no-cache --progress plain -t next-js .`
3. re-run agian, the cache missed.. can notice that hash is always different when each `PROGRESS_NO_TRUNC=1 docker build --progress plain -t next-js .` command run..

### Reproduction Repo

https://github.com/zigang93/next-with-docker-turbo

**Comment by anthonyshew** [comment] 2022-12-01 21:38
I believe the issue here is that your Docker container itself isn't logged in. Instead, your host machine is - but your host machine isn't the one doing the building! 

Since turbo is executing inside of a container (that isn't logged in), it's expected that the build will miss cache because, from the perspective of the container, there is no cache. 

You'll want to login from inside the container using the Turbo CLI's `--token` and `--team` flags. [You can find some documentation on those flags here](https://turbo.build/repo/docs/reference/command-line-reference#--token).

**Comment by zigang93** [comment] 2022-12-01 23:35
> I believe the issue here is that your Docker container itself isn't logged in. Instead, your host machine is - but your host machine isn't the one doing the building!
> 
> Since turbo is executing inside of a container (that isn't logged in), it's expected that the build will miss cache because, from the perspective of the container, there is no cache.
> 
> Two options from [the documentation](https://turbo.build/repo/docs/reference/command-line-reference#--token):
> 
> * Using environment variables, set `TURBO_TEAM` and `TURBO_TOKEN` for your container and Docker build stage
> * Turbo CLI's `--token` and `--team` flags

<img width="608" alt="Screenshot 2022-12-02 at 7 32 00 AM" src="https://user-images.githubusercontent.com/11520821/205181208-12d88795-e7f4-4b52-962a-9826a3fddad9.png">

Hi, I had tried with your both suggestion, still not working as expected. 
TURBO_TOKEN is my vercel personal access token.
TURBO_TEAM is refer to my .turbo config.json `teamid` key

I also updated my docker build command with `no-cache` to avoid any docker build cache

**Comment by anthonyshew** [comment] 2022-12-02 00:16
Sounds like you grabbed your TURBO_TOKEN correctly. Your team ID should be coming from here:
_(If you are on your personal account, the field will say "Your ID")_
![CleanShot 2022-12-01 at 17 12 11@2x](https://user-images.githubusercontent.com/35677084/205185707-0f248cfb-022a-450b-8d13-53cf67b3d0c3.png)

If that doesn't work, are you seeing errors or just still missing cache?

**Comment by zigang93** [comment] 2022-12-02 00:38
> Sounds like you grabbed your TURBO_TOKEN correctly. Your team ID should be coming from here: _(If you are on your personal account, the field will say "Your ID")_ ![CleanShot 2022-12-01 at 17 12 11@2x](https://user-images.githubusercontent.com/35677084/205185707-0f248cfb-022a-450b-8d13-53cf67b3d0c3.png)
> 
> If that doesn't work, are you seeing errors or just still missing cache?

yea, it is same as from my .turbo/config.json

I just found out that if I am using --token flag into my `pnpm build:turbo`, remote caching will not working properly in my non docker environment..

**Comment by zigang93** [comment] 2022-12-02 00:42
<img width="946" alt="Screenshot 2022-12-02 at 8 40 14 AM" src="https://user-images.githubusercontent.com/11520821/205188707-d43e6522-a024-41b9-b785-0b06629aea61.png">
I created a token from vercel setting with name "Github Action Token".. 
as you can see the last active time is never.. which mean TOKEN is not used by remote cache.. 

I believe that manual generate token is not valid for remote cache...
I also not sure why turbo token after login is not show at `.turbo/config.json`

**Comment by zigang93** [comment] 2022-12-02 00:54
my current debug step:

package.json with `"build:turbo: "turbo build --remote-only --team=\"xxxxx\" --token=\"xxxxx\""`

1. run `pnpm build:turbo`
2. delete `.next` folder
3. re-run `pnpm build:turbo`

result: cache missed


package.json with `"build:turbo: "turbo build`

1. run `pnpm build:turbo`
2. delete `.next` folder
3. re-run `pnpm build:turbo`

result: hit cache

**Comment by zigang93** [comment] 2022-12-02 01:02
this is how I am creating my token:

<img width="525" alt="Screenshot 2022-12-02 at 9 01 41 AM" src="https://user-images.githubusercontent.com/11520821/205191330-a5c24e09-24c8-4df7-87f5-b9a7e7ea5f3a.png">

**Comment by anthonyshew** [comment] 2022-12-02 23:39
Just got a chance to look at your reproduction repo! It looks like there aren't any workspaces set up for the project so Turborepo won't be able to do its work.

[Here's a starter](https://github.com/vercel/turbo/tree/main/examples/basic) to practice with!

**Comment by anthonyshew** [comment] 2022-12-03 18:27
One quick note: I was wrong that the value for `--team` is a Team ID. [The docs here](https://turbo.build/repo/docs/reference/command-line-reference#--team) identify that you'll need your _slug_ instead. My bad!

Just to keep you updated, I am indeed reproducing the behaviors you are seein and with the latest version of `turbo`. Still working at it.

**Comment by anthonyshew** [comment] 2022-12-20 00:04
One thing to note: I was wrong about `TURBO_TEAM` needing to be an ID. Instead, it needs to be your team's _slug_.

However, even with that change (using team slug), I'm still seeing cache misses. I'm definitely not seeing the behavior I'm expecting.

@nathanhammond @tknickman, any idea what's going on here?

**Comment by zigang93** [comment] 2023-02-13 23:34
@anthonyshew any update??

**Comment by matsko** [comment] 2023-03-30 07:38
I'm also experiencing this issue. Turbo in Docker always has a cache miss.

**Comment by diXrom** [comment] 2023-11-17 04:29
any news?

**Comment by anthonyshew** [comment] 2023-11-29 18:44
Hey, folks! Using latest, it looks like this bug(?) is now fixed for me:

First run:
![CleanShot 2023-11-29 at 11 34 09@2x](https://github.com/vercel/turbo/assets/35677084/0907b0c7-a7d4-44f0-9fb9-8ffbf09507e2)

Second run:
![CleanShot 2023-11-29 at 11 34 43@2x](https://github.com/vercel/turbo/assets/35677084/5ffdcb47-f070-4ec3-bb24-e592b44a073c)

Will reiterate on the key concepts to know when working on Docker + Turbo + non-monorepo and correct some of the mistakes that I made earlier in this thread (sorry, wasn't on core team yet and thought I was being helpful). 😬

- Your Docker builder stage must have access to the Remote Cache. This can be done using environment variables.
Edits to the reproduction that I made to get to success:
![CleanShot 2023-11-29 at 11 38 18@2x](https://github.com/vercel/turbo/assets/35677084/f7d3ef1e-8465-4d09-ad18-ab4fafb81c70)
- The `TURBO_TEAM` variable is a slug, not an ID. If you're using Vercel, you can find this in your dashboard.
- Make sure you're on the latest version of `turbo`.

I apologize for this taking as long as it did to get closed out and properly explained. Hope this helps!

**Closed by anthonyshew** 2023-11-29 18:44 UTC
Labels: kind: bug, owned-by: turborepo
