### ISSUE TITLE
turbo-ignore exit code 1

### ISSUE THREAD

**Issue by ntang86** [vercel/turbo#6105] opened 2023-10-05 14:52 UTC
### What version of Turborepo are you using?

1.10.14

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

[turbo-ignore](https://linear.app/vercel/issue/TURBO-ignore) returns an exit code 1 when I need to proceed to a deployment, and exit code 0 if not change need to be made. 

I read the documentation and this is apparently intended, but I fail to understand the logic here, is turbo-ignore suppose to run in a CI/CD system? If yes, this is making really hard to integrate to any CI/CD since it's produced an exit code 1 when I need to deploy something.

### Expected Behavior

Produce code 0 in both case 

### To Reproduce

npx turbo-ignore --fallback=HEAD^

<sub>[TURBO-1424](https://linear.app/vercel/issue/TURBO-1424/turbo-ignore-exit-code-1)</sub>

**Comment by chris-olszewski** [comment] 2023-10-05 16:18
`turbo-ignore` is meant to be used as an ignored build step on Vercel. From the [docs](https://vercel.com/docs/projects/overview#ignored-build-step):

> When your deployment enters the BUILDING state, the command you've entered in the Ignored Build Step section will be run. The command will always exit with either code 1 or 0:
>
>    - If the command exits with code 1, the build continues as normal
>    - If the command exits with code 0, the build is immediately aborted, and the deployment state is set to CANCELED

In the CI where [remote caching](https://turbo.build/repo/docs/core-concepts/remote-caching) is enabled scenario where you just want to run tests or make sure artifacts get built, then you can just invoke `turbo` directly and rely on hitting the remote cache if nothing relevant has changed. 

For actual deployments, suggestions change depending on what capabilities your platform provides. On Vercel, the suggestion would be to use `turbo-ignore` to abort any deployments that were caused by commits that don't effect a site.

Closing, but feel free to reopen with more specifics so I can give better guidance.

**Closed by chris-olszewski** 2023-10-05 16:18 UTC
Labels: kind: bug, needs: triage, linear: turbo, owned-by: turborepo
