### ISSUE TITLE
[turborepo] Plain design-system example clone throwing "Could not resolve" errors

### ISSUE THREAD

**Issue by renet** [vercel/turbo#6099] opened 2023-10-04 21:37 UTC
### What version of Turborepo are you using?

1.10.14

### What package manager are you using / does the bug impact?

pnpm 8.6.10

### What operating system are you using?

Mac, Sonoma 14.0 (23A344)

### Describe the Bug

After checking out the design-system example and running `pnpm I` inside, running `pnpm dev` on the project root results in several errors, when turbo tries to start storybook, that seem to be related to `@storybook/addon-essentials`. Console says:

```
@acme/docs:dev: @storybook/cli v7.4.0
@acme/docs:dev: 
@acme/docs:dev: info => Starting manager..
@acme/docs:dev: ✘ [ERROR] Could not resolve "@storybook/addon-actions/manager"
@acme/docs:dev: 
@acme/docs:dev:     ../../node_modules/.pnpm/@storybook+addon-essentials@7.4.0_react-dom@18.2.0_react@18.2.0/node_modules/@storybook/addon-essentials/dist/actions/manager.mjs:1:14:
@acme/docs:dev:       1 │ export * from '@storybook/addon-actions/manager';
@acme/docs:dev:         ╵               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
@acme/docs:dev: 
@acme/docs:dev:   The Yarn Plug'n'Play manifest forbids importing "@storybook/addon-actions" here because it's not listed as a dependency of this package:
@acme/docs:dev: 
@acme/docs:dev:     ../../../../../.pnp.cjs:45:33:
@acme/docs:dev:       45 │           "packageDependencies": [
@acme/docs:dev:          ╵                                  ^
@acme/docs:dev: 
@acme/docs:dev:   You can mark the path "@storybook/addon-actions/manager" as external to exclude it from the bundle, which will remove this error.
@acme/docs:dev: 
@acme/docs:dev: ✘ [ERROR] Could not resolve "@storybook/addon-measure/manager"
@acme/docs:dev: 
@acme/docs:dev:     ../../node_modules/.pnpm/@storybook+addon-essentials@7.4.0_react-dom@18.2.0_react@18.2.0/node_modules/@storybook/addon-essentials/dist/measure/manager.mjs:1:14:
@acme/docs:dev:       1 │ export * from '@storybook/addon-measure/manager';
@acme/docs:dev:         ╵               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
@acme/docs:dev: 
@acme/docs:dev:   The Yarn Plug'n'Play manifest forbids importing "@storybook/addon-measure" here because it's not listed as a dependency of this package:
@acme/docs:dev: 
@acme/docs:dev:     ../../../../../.pnp.cjs:45:33:
@acme/docs:dev:       45 │           "packageDependencies": [
@acme/docs:dev:          ╵                                  ^
@acme/docs:dev: 
@acme/docs:dev:   You can mark the path "@storybook/addon-measure/manager" as external to exclude it from the bundle, which will remove this error.
@acme/docs:dev: 
@acme/docs:dev: ✘ [ERROR] Could not resolve "@storybook/addon-outline/manager"
@acme/docs:dev: 
@acme/docs:dev:     ../../node_modules/.pnpm/@storybook+addon-essentials@7.4.0_react-dom@18.2.0_react@18.2.0/node_modules/@storybook/addon-essentials/dist/outline/manager.mjs:1:14:
@acme/docs:dev:       1 │ export * from '@storybook/addon-outline/manager';
@acme/docs:dev:         ╵               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
@acme/docs:dev: 
@acme/docs:dev:   The Yarn Plug'n'Play manifest forbids importing "@storybook/addon-outline" here because it's not listed as a dependency of this package:
@acme/docs:dev: 
@acme/docs:dev:     ../../../../../.pnp.cjs:45:33:
@acme/docs:dev:       45 │           "packageDependencies": [
@acme/docs:dev:          ╵                                  ^
@acme/docs:dev: 
@acme/docs:dev:   You can mark the path "@storybook/addon-outline/manager" as external to exclude it from the bundle, which will remove this error.
@acme/docs:dev: 
@acme/docs:dev: ✘ [ERROR] Could not resolve "@storybook/addon-backgrounds/manager"
@acme/docs:dev: 
@acme/docs:dev:     ../../node_modules/.pnpm/@storybook+addon-essentials@7.4.0_react-dom@18.2.0_react@18.2.0/node_modules/@storybook/addon-essentials/dist/backgrounds/manager.mjs:1:14:
@acme/docs:dev:       1 │ export * from '@storybook/addon-backgrounds/manager';
@acme/docs:dev:         ╵               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
@acme/docs:dev: 
@acme/docs:dev:   The Yarn Plug'n'Play manifest forbids importing "@storybook/addon-backgrounds" here because it's not listed as a dependency of this package:
@acme/docs:dev: 
@acme/docs:dev:     ../../../../../.pnp.cjs:45:33:
@acme/docs:dev:       45 │           "packageDependencies": [
@acme/docs:dev:          ╵                                  ^
@acme/docs:dev: 
@acme/docs:dev:   You can mark the path "@storybook/addon-backgrounds/manager" as external to exclude it from the bundle, which will remove this error.
@acme/docs:dev: 
@acme/docs:dev: ✘ [ERROR] Could not resolve "@storybook/addon-controls/manager"
@acme/docs:dev: 
@acme/docs:dev:     ../../node_modules/.pnpm/@storybook+addon-essentials@7.4.0_react-dom@18.2.0_react@18.2.0/node_modules/@storybook/addon-essentials/dist/controls/manager.mjs:1:14:
@acme/docs:dev:       1 │ export * from '@storybook/addon-controls/manager';
@acme/docs:dev:         ╵               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
@acme/docs:dev: 
@acme/docs:dev:   The Yarn Plug'n'Play manifest forbids importing "@storybook/addon-controls" here because it's not listed as a dependency of this package:
@acme/docs:dev: 
@acme/docs:dev:     ../../../../../.pnp.cjs:45:33:
@acme/docs:dev:       45 │           "packageDependencies": [
@acme/docs:dev:          ╵                                  ^
@acme/docs:dev: 
@acme/docs:dev:   You can mark the path "@storybook/addon-controls/manager" as external to exclude it from the bundle, which will remove this error.
@acme/docs:dev: 
@acme/docs:dev: ✘ [ERROR] Could not resolve "@storybook/addon-toolbars/manager"
@acme/docs:dev: 
@acme/docs:dev:     ../../node_modules/.pnpm/@storybook+addon-essentials@7.4.0_react-dom@18.2.0_react@18.2.0/node_modules/@storybook/addon-essentials/dist/toolbars/manager.mjs:1:14:
@acme/docs:dev:       1 │ export * from '@storybook/addon-toolbars/manager';
@acme/docs:dev:         ╵               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
@acme/docs:dev: 
@acme/docs:dev:   The Yarn Plug'n'Play manifest forbids importing "@storybook/addon-toolbars" here because it's not listed as a dependency of this package:
@acme/docs:dev: 
@acme/docs:dev:     ../../../../../.pnp.cjs:45:33:
@acme/docs:dev:       45 │           "packageDependencies": [
@acme/docs:dev:          ╵                                  ^
@acme/docs:dev: 
@acme/docs:dev:   You can mark the path "@storybook/addon-toolbars/manager" as external to exclude it from the bundle, which will remove this error.
@acme/docs:dev: 
@acme/docs:dev: ✘ [ERROR] Could not resolve "@storybook/addon-viewport/manager"
@acme/docs:dev: 
@acme/docs:dev:     ../../node_modules/.pnpm/@storybook+addon-essentials@7.4.0_react-dom@18.2.0_react@18.2.0/node_modules/@storybook/addon-essentials/dist/viewport/manager.mjs:1:14:
@acme/docs:dev:       1 │ export * from '@storybook/addon-viewport/manager';
@acme/docs:dev:         ╵               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
@acme/docs:dev: 
@acme/docs:dev:   The Yarn Plug'n'Play manifest forbids importing "@storybook/addon-viewport" here because it's not listed as a dependency of this package:
@acme/docs:dev: 
@acme/docs:dev:     ../../../../../.pnp.cjs:45:33:
@acme/docs:dev:       45 │           "packageDependencies": [
@acme/docs:dev:          ╵                                  ^
@acme/docs:dev: 
@acme/docs:dev:   You can mark the path "@storybook/addon-viewport/manager" as external to exclude it from the bundle, which will remove this error.
@acme/docs:dev: 
@acme/docs:dev: Error: Build failed with 7 errors:
@acme/docs:dev: ../../node_modules/.pnpm/@storybook+addon-essentials@7.4.0_react-dom@18.2.0_react@18.2.0/node_modules/@storybook/addon-essentials/dist/actions/manager.mjs:1:14: ERROR: Could not resolve "@storybook/addon-actions/manager"
@acme/docs:dev: ../../node_modules/.pnpm/@storybook+addon-essentials@7.4.0_react-dom@18.2.0_react@18.2.0/node_modules/@storybook/addon-essentials/dist/backgrounds/manager.mjs:1:14: ERROR: Could not resolve "@storybook/addon-backgrounds/manager"
@acme/docs:dev: ../../node_modules/.pnpm/@storybook+addon-essentials@7.4.0_react-dom@18.2.0_react@18.2.0/node_modules/@storybook/addon-essentials/dist/controls/manager.mjs:1:14: ERROR: Could not resolve "@storybook/addon-controls/manager"
@acme/docs:dev: ../../node_modules/.pnpm/@storybook+addon-essentials@7.4.0_react-dom@18.2.0_react@18.2.0/node_modules/@storybook/addon-essentials/dist/measure/manager.mjs:1:14: ERROR: Could not resolve "@storybook/addon-measure/manager"
@acme/docs:dev: ../../node_modules/.pnpm/@storybook+addon-essentials@7.4.0_react-dom@18.2.0_react@18.2.0/node_modules/@storybook/addon-essentials/dist/outline/manager.mjs:1:14: ERROR: Could not resolve "@storybook/addon-outline/manager"
@acme/docs:dev: ...
@acme/docs:dev:     at failureErrorWithLog (/dev/design-system/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:1649:15)
@acme/docs:dev:     at /dev/design-system/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:1058:25
@acme/docs:dev:     at runOnEndCallbacks (/dev/design-system/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:1484:45)
@acme/docs:dev:     at buildResponseToResult (/dev/design-system/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:1056:7)
@acme/docs:dev:     at /dev/design-system/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:1085:16
@acme/docs:dev:     at responseCallbacks.<computed> (/dev/design-system/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:703:9)
@acme/docs:dev:     at handleIncomingPacket (/dev/design-system/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:762:9)
@acme/docs:dev:     at Socket.readFromStdout (/dev/design-system/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:679:7)
@acme/docs:dev:     at Socket.emit (node:events:513:28)
@acme/docs:dev:     at addChunk (node:internal/streams/readable:324:12)
@acme/docs:dev: 
@acme/docs:dev: WARN Broken build, fix the error above.
@acme/docs:dev: WARN You may need to refresh the browser.
@acme/docs:dev: 
@acme/docs:dev:  ELIFECYCLE  Command failed with exit code 1.
@acme/docs:dev: command finished with error, but continuing...
```

The Storybook dev server does not start, Storybook cannot be accessed. Thank you very much for your help! ♥️

### Expected Behavior

When checking out the plain example directory and after running `pnpm I`, running `pnpm dev` results in the Storybook dev server starting without errors.

### To Reproduce

Node.js version: 18.15.0

- Checkout the turbo repo
- copy/move the folder `/examples/design-system` out of the repo into its own project folder
- go to that project folder and run `pnpm i`
- run `pnpm dev`

### Reproduction Repo

https://github.com/vercel/turbo/tree/main/examples/design-system ;)

**Comment by chris-olszewski** [comment] 2023-10-04 22:32
Can you try adding `nodeLinker: node-modules` to your `.yarnrc.yml`?

**Comment by nathanhammond** [comment] 2023-10-05 06:35
Hey @renet! That's not the way we recommend for using the examples, you can get weird partial package manager conversions if you do that.

You'll notice that you're getting a Yarn PnP error, in spite of attempting to use `pnpm`.

Here's an attempted reproduction of what you're trying to do, which works for me:
```
npx create-turbo@canary issue-6099 --example=design-system --package-manager=pnpm
cd issue-6099
pnpm dev
```

```
~/repos/triage$ npx create-turbo@canary issue-6099 --example=design-system --package-manager=pnpm

>>> TURBOREPO

>>> Welcome to Turborepo! Let's get you set up with a new codebase.


Downloading files for example design-system. This might take a moment.

>>> Created a new Turborepo with the following:

apps
 - apps/docs
packages
 - packages/eslint-config-custom
 - packages/tsconfig
 - packages/ui

Installing packages. This might take a couple of minutes.

>>> Success! Created a new Turborepo at "issue-6099".
Inside that directory, you can run several commands:

  pnpm run build
     Build all apps and packages

  pnpm run dev
     Develop all apps and packages

  pnpm run lint
     Lint all apps and packages

Turborepo will cache locally by default. For an additional
speed boost, enable Remote Caching with Vercel by
entering the following command:

  pnpm dlx turbo login

We suggest that you begin by typing:

  cd issue-6099
  pnpm dlx turbo login

~/repos/triage$ cd issue-6099
~/repos/triage/issue-6099 (main)$ pnpm dev

> @ dev /Users/nathanhammond/repos/triage/issue-6099
> turbo run dev --no-cache --continue

• Packages in scope: @acme/docs, eslint-config-custom, tsconfig, ui
• Running dev in 4 packages
• Remote caching disabled
ui:dev: cache bypass, force executing 228809718ac4dab7
@acme/docs:dev: cache bypass, force executing b4e243e546c7ee3a
@acme/docs:dev: 
@acme/docs:dev: > @acme/docs@0.0.0 dev /Users/nathanhammond/repos/triage/issue-6099/apps/docs
@acme/docs:dev: > storybook dev -p 6006
@acme/docs:dev: 
ui:dev: 
ui:dev: > ui@0.0.0 dev /Users/nathanhammond/repos/triage/issue-6099/packages/ui
ui:dev: > tsup src/index.tsx --format esm,cjs --watch --dts --external react
ui:dev: 
ui:dev: CLI Building entry: src/index.tsx
ui:dev: CLI Using tsconfig: tsconfig.json
ui:dev: CLI tsup v5.12.9
ui:dev: CLI Running in watch mode
ui:dev: CLI Target: node12
ui:dev: ESM Build start
ui:dev: CJS Build start
ui:dev: DTS Build start
ui:dev: ESM ⚡️ Build success in 354ms
ui:dev: CJS ⚡️ Build success in 350ms
ui:dev: ESM dist/index.mjs 249.00 B
ui:dev: CJS dist/index.js 1.27 KB
ui:dev: CLI Watching for changes in "."
ui:dev: CLI Ignoring changes in "**/{.git,node_modules}/**" | "dist"
@acme/docs:dev: @storybook/cli v7.4.0
@acme/docs:dev: 
ui:dev: DTS ⚡️ Build success in 359ms
@acme/docs:dev: 
@acme/docs:dev: attention => Storybook now collects completely anonymous telemetry regarding usage.
@acme/docs:dev: This information is used to shape Storybook's roadmap and prioritize features.
@acme/docs:dev: You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
@acme/docs:dev: https://storybook.js.org/telemetry
@acme/docs:dev: 
@acme/docs:dev: info => Starting manager..
@acme/docs:dev: ╭─────────────────────────────────────────────────────────────────────╮
@acme/docs:dev: │                                                                     │
@acme/docs:dev: │   Storybook 7.4.0 for react-vite started                            │
@acme/docs:dev: │   262 ms for manager and 807 ms for preview                         │
@acme/docs:dev: │                                                                     │
@acme/docs:dev: │   Local:            http://localhost:6006/                          │
@acme/docs:dev: │   On your network:  http://192.168.88.157:6006/                     │
@acme/docs:dev: │                                                                     │
@acme/docs:dev: │   A new version (7.4.6) is available!                               │
@acme/docs:dev: │                                                                     │
@acme/docs:dev: │   Upgrade now: npx storybook@latest upgrade                         │
@acme/docs:dev: │                                                                     │
@acme/docs:dev: │   Read full changelog:                                              │
@acme/docs:dev: │   https://github.com/storybookjs/storybook/blob/next/CHANGELOG.md   │
@acme/docs:dev: │                                                                     │
@acme/docs:dev: ╰─────────────────────────────────────────────────────────────────────╯
```

I'm closing this because I suspect that it will also work for you. If it doesn't please let us know!

**Closed** 2023-10-05 06:35 UTC
Labels: kind: bug, needs: triage, owned-by: turborepo

**Comment by renet** [comment] 2023-10-05 06:53
Thanks, @nathanhammond, I was wondering what was the correct way of doing this. However, this just results in the same behavior.

@chris-olszewski Your approach didn't help, either (created a `.yarnrc.yml` in the project root).

I figured out that there was a `.pnp.cjs` file im my user's home directory, which probably didn't belong there. After deleting this, everything works fine. So thanks for your help and this ticket can stay closed. :)
