### ISSUE TITLE
turbo run dev --filter=[app name] no longer executes persistently

### ISSUE THREAD

**Issue by adamdva** [vercel/turbo#7201] opened 2024-01-31 22:56 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

don't have one currently

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Linux

### Which canary version will you have in your reproduction?

1.11.4-canary.4

### Describe the Bug

My package,json has the follwing script:
```"dev:web": "turbo run dev --filter=web"```
previously this would build and execute the dev server, with logs piped to the console.
With the latest release, the build ends, and the dev server can not be accessed on the port expected.

### Expected Behavior

The ```turbo run dev``` command to stay running with logs to the console.

### To Reproduce

```pnpm run dev:web```

### Additional context

I previous was using ```@types/node: 20.11.7`` and ```turbo: 1.11.3```
now after upgrade ```@types/node: 20.11.14``` and ```turbo: 1.12.1```
and dev server is not working as expected.

**Comment by anthonyshew** [comment] 2024-01-31 23:02
Duplicate of #7181. Should be fixed in 1.12.2 now!

P.S. In the future, please provide a reproduction.

**Closed by anthonyshew** 2024-01-31 23:02 UTC
Labels: kind: bug, needs: triage, owned-by: turborepo

**Comment by adamdva** [comment] 2024-01-31 23:10
thank you
