### ISSUE TITLE
[turborepo] defining `passThroughEnv` breaks next.js internal revalidate api

### ISSUE THREAD

**Issue by klaasman** [vercel/turbo#5932] opened 2023-09-12 10:29 UTC
### What version of Turborepo are you using?

1.10.12

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

_I'm not sure whether this issue belongs to the next.js, or the turbopack repository._

I recently ran into a weird bug where the nextjs [on-demand revalidate api](https://nextjs.org/docs/pages/building-your-application/rendering/incremental-static-regeneration#on-demand-revalidation) suddenly was broken. Calling the `response.revalidate()` would throw an error which, at least to me, was not helpful at all.

error:
```
Error revalidating: Failed to revalidate /test: Cannot find module '/var/task/apps/web/.next/server/pages/test.js'\nRequire stack:\n- /var/task/node_modules/.pnpm/next@13.4.19_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/require.js\n- /var/task/node_modules/.pnpm/next@13.4.19_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/next-server.js\n- /var/task/apps/web/___next_launcher.cjs
```

After some debugging I was able to figure out that setting the `passThroughEnv` array was the culprit. I suspect that turbo strict mode is removing a bunch of env variables which are used by next.js internally.

### Expected Behavior

I expect the next.js on-demand revalidate api to keep working when I configure `passThroughEnv` variables in turbo.

### To Reproduce

See bug in action: https://turborepo-next-revalidate-bug-git-main-klaasman.vercel.app/api/revalidate?path=/test
([here](https://turborepo-next-revalidate-ixcewtean-klaasman.vercel.app/api/revalidate?path=/test) is a working preview deployment w/o the "passThroughEnv" array, introduced in [this commit](https://github.com/klaasman/turborepo-next-revalidate-bug/commit/e8aa54420c74ce77d043bc13c03441f72cd730bb))

Reproduce:
1. Clone repo https://github.com/klaasman/turborepo-next-revalidate-bug
3. deploy to vercel
4. try to revalidate the test page by visiting `/api/revalidate?path=/test`

### Reproduction Repo

https://github.com/klaasman/turborepo-next-revalidate-bug

**Comment by tknickman** [comment] 2023-09-12 13:17
Ooh this is a good one. Thanks for the detailed repro / project! I'm chatting with the Next.js team to see exactly what might be missing here and will follow up.

**Comment by tknickman** [comment] 2023-09-12 20:28
Alright @klaasman, quick unblock is to make sure the `$NOW_BUILDER` env var can make it to the build. In your case: `"passThroughEnv": ["NOW_BUILDER"]` (sent a PR to your reproduction repro)

We're going to need a better way to support this in the future with some type of automatic framework config

**Comment by klaasman** [comment] 2023-09-13 13:45
Great, can confirm that helps works 👍 

> We're going to need a better way to support this in the future with some type of automatic framework config

Doesn't turbo already have "[Automatic environment variable inclusion](https://turbo.build/blog/turbo-1-4-0#automatic-environment-variable-inclusion)"?

**Comment by tknickman** [comment] 2023-09-14 16:18
Yea good question - it does, and this is all you need in most cases. However the automatic variable inclusion relies on the environment variable using a framework prefix (we detect your framework, and then use that to allow all correct the env vars in). 

_This_ var is internal to the Vercel build process and is used to communicate features that are supported to Next. So we're looking at some other solutions to make this one work. This is likely going to be something that changes on our end and will "just work" for you when it's out.

**Comment by klaasman** [comment] 2023-09-14 18:12
Great, good luck fixing this bug and glad I could help to surface it 👍

**Comment by tknickman** [comment] 2023-09-14 18:33
😄 thanks! I'm going to close this one since the specific issue has a resolution, but we're tracking this internally to determine a fix.

**Closed by tknickman** 2023-09-14 18:33 UTC
Labels: kind: bug, owned-by: turborepo
