### ISSUE TITLE
TurboRepo and Git 2.17.1 do not compute new hashes on changes

### ISSUE THREAD

**Issue by cpitt** [vercel/turbo#1696] opened 2022-08-15 17:22 UTC
### What version of Turborepo are you using?

1.4.3

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Linux

### Describe the Bug

with git 2.17.1 installed

When I make make changes to a file in a package and run `turbo run build`. I get a cache hit on the previous hash despite new changes.

### Expected Behavior

I would expect a new hash and a cache miss.

### To Reproduce

---
-  Downgrade git to 2.17.1
-  Run `turbo run build`
-  Make changes to a package
-  Run `turbo run build` again see that it uses previous cache entry instead of rebuilding
---
- Upgrade back to 2.37.2
- Run `turbo run build`
- Make change to a package
- Run `turbo run build` again see that it correctly calculates new hash and runs task

**Comment by cpitt** [comment] 2022-08-15 23:07
I realize that this likely a git issue, At the very least we should update the documentation to include the minimum supported git version.

I've skimmed the rel notes to see if I could find changes to `ls-files` and `ls-tree` that would result in the hash not changing between versions 2.17.1 and current but nothing stuck out.

next step would be to work through the git releases testing to see what version the issue is resolved in assuming someone already know the minimum supported version

**Comment by cpitt** [comment] 2022-08-15 23:58
Just tested with git 2.18.0 it is fixed in that version. Probably safe to assume turborepo requires git  >=2.18.0

**Comment by chris-olszewski** [comment] 2022-08-16 17:26
Thanks for the report. Would be good to understand what breaks us for older versions of git, but supporting a 4 year old version doesn't seem high priority.

**Comment by cpitt** [comment] 2022-08-16 18:09
@chris-olszewski I agree that it's not a high priority. It's probably worth noting that 2.17.1 is what ships with ubuntu bionic which is still the LTS until the EOY (and unfortunately what my client's build agents are running).

I'll open a Docs PR to see if we can get a prereq section added to getting started with the minimum git version

**Comment by nathanhammond** [comment] 2022-08-30 10:07
Here is a complete enumeration of the `git` functions that we call compared between 2.17.1 and 2.18.0. None of the changes strike me as related.

- [`ls-tree`](https://github.com/git/git/compare/v2.17.1...v2.18.0#diff-ffbd45ba02f060ba3bd0bcddddd7afc2cb7ff38a4629906e7e7d8c800fde2f6c)
- [`ls-files`](https://github.com/git/git/compare/v2.17.1...v2.18.0#diff-b860ab9407540e10dc41075db50474c422ae03678e0d009aaf12225cce1e69c6)
- [`hash-object`](https://github.com/git/git/compare/v2.17.1...v2.18.0#diff-0a8114cf527d29f902877803c5198e36ec821e78008f75fb8438faeffbb0c29a)
- [`status`](https://github.com/git/git/compare/v2.17.1...v2.18.0#diff-21ecaaf4e2318a39cdedf505941dbfbabd3329f041c839a03fb84906b4dae4fb)
- [`diff`](https://github.com/git/git/compare/v2.17.1...v2.18.0#diff-bceeb512b610e0e922fd4581445b0201ccf15ea48ad8317eb1f0b5d9a9d62185)
- [`cat-file`](https://github.com/git/git/compare/v2.17.1...v2.18.0#diff-d03110606a7ed8cb9832bbcc572f1093435cc6115c4e58d7a7750af3c33319a7)
- [`rev-parse`](https://github.com/git/git/compare/v2.17.1...v2.18.0#diff-a1362d0be72fdc680c2f42e05e8130ee334a7583ad8cd1588e55b420ea377b69)

Does anything stand out to you?

**Comment by nathanhammond** [comment] 2022-08-30 10:33
I'm unable to reproduce on macOS:

1. <img width="756" alt="2 17 1 Create" src="https://user-images.githubusercontent.com/20542/187414459-9a0073ed-297e-4aef-ba83-452f9daa1f2a.png">
2. <img width="754" alt="2 17 1 First Build" src="https://user-images.githubusercontent.com/20542/187414468-5a3cd360-450b-4b23-aaf7-e68e540f2ca7.png">
3. <img width="754" alt="2 17 1 Modify" src="https://user-images.githubusercontent.com/20542/187414473-f00f7b2d-9bbd-471a-90c6-8a1c56620956.png">
4. <img width="754" alt="2 17 1 Cache Miss" src="https://user-images.githubusercontent.com/20542/187414542-7c464a56-b4d6-4a8d-9294-7a6c9f8df2a5.png">

I see nothing in the diffs that imply there should be an issue resolved by install 2.18, and the features we use are supported back to something like 2015.

Is it possible that this is an issue with those individual boxes?

**Comment by cpitt** [comment] 2022-08-30 16:02
The issue showed up on our build agent's docker containers running ubuntu bionic and was reproduced on my dev machine running OSX Monterey (after downgrading git to 2.17.1). 

I can try reproducing it again on a fresh repository to eliminate whether the issue is specific to my codebase and or configuration.

I did look through the git 2.18 release notes and didn't see anything that would indicate changes with any of the dependent functions.

**Comment by nathanhammond** [comment] 2022-08-31 08:19
@cpitt I'd love to see if you can reproduce it using approximately the same steps I did (captured in the screenshots). I'd like to rule out `git@2.17.1` as a _generic_ cause of problems.

If you can't reproduce it using `create-turbo` then I would be _super_ interested in trying to figure out why it is failing in your particular configuration. (e.g. file paths, symlinks, gitignore, etc.)

**Comment by cpitt** [comment] 2022-09-02 00:00
Here's a git repository with some automated reproduction scripts.

The big difference between this and your repro steps @nathanhammond is that I added an `inputs` to the `turbo.json` file

https://github.com/cpitt/turbo-git-bug-test-repo

It does consistently repro the issue

**Comment by anthonyshew** [comment] 2024-02-05 04:55
Closing because:
- git version that is 4 years old
- Turborepo version from 8 minors ago
- Inactivity

**Closed by anthonyshew** 2024-02-05 04:55 UTC
Labels: needs: reproduction, owned-by: turborepo
