### ISSUE TITLE
[turborepo] basic-demo pnpm dev and pnpm build errors

### ISSUE THREAD

**Issue by Lionel001** [vercel/turbo#6559] opened 2023-11-23 09:59 UTC
### What version of Turborepo are you using?

1.10.16

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

I just use 'pnpm dlx create-turbo@latest' init a turborepo demo, but when I followed the documentation to execute "pnpm dev" and "pnpm build", I encountered an error.

pnpm dev
error is --> docs:dev: ReferenceError: Request is not defined

pnpm build
error is --> docs:build: unhandledRejection ReferenceError: Headers is not defined

And I found that the online documentation is inconsistent with the basic-demo.

### Expected Behavior

--

### To Reproduce

--

**Comment by gautam-ndk** [comment] 2023-11-24 11:11
Looks like nextjs dropped support of older node versions recently. Reference [here](https://github.com/orgs/community/discussions/72835).

Updating node fixed the issue for me.

**Comment by Zertsov** [comment] 2023-11-24 18:42
@Lionel001 I'm having trouble reproducing, can you confirm that updating your Node version fixes this? If not can you provide some more info on your environment so I can try to debug it locally?

**Comment by tknickman** [comment] 2023-11-24 19:24
This is definitely node version related. We're going to add the required node version to all of our examples to make this easier to debug when it happens! cc @anthonyshew

**Comment by anthonyshew** [comment] 2023-11-25 01:10
Addressed in #6568

**Closed by anthonyshew** 2023-11-25 01:10 UTC
Labels: kind: bug, needs: triage, owned-by: turborepo
