### ISSUE TITLE
[turborepo] prune removing env var dependencies from turbo.json

### ISSUE THREAD

**Issue by Suniron** [vercel/turbo#3758] opened 2023-02-11 14:42 UTC
### What version of Turborepo are you using?

1.7.1

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Linux

### Describe the Bug

Since i upgraded turbo to **1.7.1**, env variables are not listed as dependencies in the `out/full/turbo.json`  generated by the command `prune` with `--docker` argument.

Theese variables are set in the turbo.json at the root of my monorepo but in **pipelines > env** instead of `globalEnv`

If i downgrade to **1.7.0** it works again.

Also, i say that this file is now minified on prune.

### Expected Behavior

The `out/full/turbo.json` contains my environment variables set in **pipelines > env**.

### To Reproduce

1. Set at least one env variable in **pipeline > env** of your root `turbo.json`, like bellow:
```json
  "gql#build": {
      "dependsOn": [
        "^build"
      ],
      "outputs": [
        "dist/**"
      ],
      "env": [
        "API_URL"
      ]
    },
```
2. Prune the project with `pnpm turbo prune --docker`
3. Show output `out/full/turbo.json` file

**Comment by yovanoc** [comment] 2023-02-13 21:53
Not working on 1.7.4 for me too. Juste it stopped working from 1.7.1

**Comment by chris-olszewski** [comment] 2023-02-13 22:14
@yangshun Can you provide a reproduction? I quick tested adding an env key to regular tasks and workspace specific tasks and I'm seeing them in the resulting `turbo.json`

**Comment by yangshun** [comment] 2023-02-14 02:40
@chris-olszewski you tagged the wrong person. Probably meant to tag @yovanoc

**Comment by yovanoc** [comment] 2023-02-14 22:58
I'm on holidays so I can't do nothing for next 2 weeks. But if it's still a thing I can try to narrow to a minimal reproduction but actually this is a 50+ apps/packages monorepo so will see

**Comment by yovanoc** [comment] 2023-03-13 16:46
I tried today to do a minimal reproduction without success. It's really weird. Can't find the thing that make me reproduce this

**Comment by wbobeirne** [comment] 2023-07-13 14:50
I'm also running into this issue right now in my Dockerfile which causes the subsequent turbo build to fail due to the `turbo/no-undeclared-env-vars` tslint rule:
```dockerfile
RUN yarn global add turbo
COPY . .
RUN turbo prune --scope="app" --docker

# further down

RUN REACT_APP_ENV_VAR="..." yarn turbo run build --filter=app...
```
I'll try to come up with a minimal reproduction.

**Comment by wbobeirne** [comment] 2023-07-13 17:58
I was able to reproduce over here: https://github.com/wbobeirne/turbo-env-bug. I checked in the `out` directory so you can see it on github, but you should be able to pull and reproduce.

**Comment by chris-olszewski** [comment] 2023-07-18 17:21
@wbobeirne, looking at your repro the only tasks in the original `turbo.json` that have non-empty `env` are `app#build` and `app2#build`. Both of these tasks are pruned from the `turbo.json` as those workspaces don't exist. If I add an `"env": ["REACT_APP_ENV_VAR"]` to the standard `build` task definition then I see that `"env"` key preserved along with it's value.

**Comment by wbobeirne** [comment] 2023-07-18 23:01
Ah yeah I see now that they're missing the `@namespace/` prefix. However, their settings seem to get picked up for `@namespace/app` and `@namespace/app2`. Is there maybe some inconsistency of some systems allowing "fuzzy" matching of package names, and some systems requiring exact matches? Everything works in my real repo (not this reproduction) with those partial names.

**Comment by chris-olszewski** [comment] 2024-06-17 19:17
Sorry for the large delay, this got lost in my notifications.

I quick tested your reproduction with turbo 1.13.4 and changing [this line](https://github.com/wbobeirne/turbo-env-bug/blob/main/turbo.json#L8) to `@namespace/app#build` and the env var was persisted to the `out/full/turbo.json` as expected.

> Is there maybe some inconsistency of some systems allowing "fuzzy" matching of package names, and some systems requiring exact matches?

There was a behavior in turbo 1 where `turbo run` would infer a namespace e.g. `turbo run build --filter=app` would run build for `@namespace/app`, but nothing for configuration.

Closing this as provided reproduction passed when the config was changed. Please reopen if you have a reproduction that fails with a 1.13.4 or 2.0+

**Closed by chris-olszewski** 2024-06-17 19:17 UTC
Labels: kind: bug, needs: author input, owned-by: turborepo
