### ISSUE TITLE
Turborepo includes unnecessary tasks

### ISSUE THREAD

**Issue by IPWright83** [vercel/turbo#2011] opened 2022-09-20 09:11 UTC
### What version of Turborepo are you using?

1.4.3

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Linux

### Describe the Bug

I've configured a dummy command to test out called `cy`. This command exists within 2 packages (that currently do not have any dependencies) and has been configured in my turbo.json like so:

```
"cy": {
    "dependsOn": ["^build"]
},
```

When I run the `cy` command, essentially my entire dependency graph seems to build. Looking at the graph output I don't expect to see any of the things in the red box.

![image](https://user-images.githubusercontent.com/1374775/191217854-5d0332c6-4db0-4373-a199-31953eb8ab42.png)

### Expected Behavior

What I expect to happen is when I run the `cy` command, as there are no dependencies these commands would just run. If they did have dependencies I'd expect just their dependency graph to build

### To Reproduce

```
git clone git@github.com:IPWright83/pnpm-monorepo.git
git checkout turbo-issue-2011
pnpm install
pnpm cy
```

This should run the `cy` command which is only defined within `log`. It should build any dependencies of log (there are none).

![image](https://user-images.githubusercontent.com/1374775/191218893-2cc8292a-de46-4d05-89ad-9b922e7c86f8.png)

More packages than necessary however build :(

![image](https://user-images.githubusercontent.com/1374775/191219532-48a0b589-1561-45a1-ad9d-10a00989eaf4.png)

**Comment by IPWright83** [comment] 2022-09-20 11:05
Thinking about this more it feels like this could work in a similar manner to `--filter`? I expected it to automatically filter the tree, based on the packages that defined the script. So maybe it could hook into that same logic?

**Comment by iDuuck** [comment] 2022-09-22 15:04
I can't see any `cy` script in your example repository though. Just thinking about what could cause this issue, would be, that one package's `build` task has a dependency to `^cy` which needs to be run first. Could this be the case? Is it possible for you to resample the turbo.json in the example repository?

**Comment by IPWright83** [comment] 2022-09-22 17:04
@iDuuck sorry, you need to be on the Turborepo branch that includes this issue number. The script is in the `packages\log\package.json` file.

The `cy` task has a dependency on `^build` but this is a leaf package so this shouldn't build anything

**Comment by iDuuck** [comment] 2022-09-22 18:57
Will check, and keep you posted.

**Comment by iDuuck** [comment] 2022-09-22 19:55
So, afaik this is a strange behavior. As per docs it should only check for the deps of cy, and do nothing before the cy. Def a bug.

**Comment by georeith** [comment] 2022-11-25 16:55
This a duplicate of https://github.com/vercel/turbo/issues/937 I believe.

**Closed** 2023-03-17 15:39 UTC
