### ISSUE TITLE
Prune command crashing on Windows & M1/M2

### ISSUE THREAD

**Issue by LuxuryPanda** [vercel/turbo#1554] opened 2022-07-19 16:25 UTC
### What version of Turborepo are you using?

1.1.2 & latest

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Windows

### Describe the Bug

I have a turborepo project, with sub-projects inside the packages folder. In the main root folder I have turbo.json file configured with pipelines to build each sub-project and their dependencies. Quick note, the project has been set-up from scratch following the https://turborepo.org/docs/getting-started

The problem is that the docker containers get build and work flawlessly on a Linux machine, but when trying to do that on either Windows (WSL2 on both 10 and 11) or Mac M1/M2 it fails.

Something I tried to do was to manually fix the problems by adding all the required files in to each package at cost of turning each one of them into the root project and it still failed. So the steps I did are the following:

1) Normal build process (based on the one working on Linux):

```
=> ERROR [pruner 3/3] RUN turbo prune --scope=@mycoolproject/pack6 --docker                                0.6s
------
 > [pruner 3/3] RUN turbo prune --scope=@mycoolproject/pack6 --docker:
#9 0.620  ERROR  could not construct graph: Could not find turbo.json. Follow directions at https://turborepo.org/docs/getting-started to create one
------
executor failed running [/bin/sh -c turbo prune --scope=${SCOPE} --docker]: exit code: 1
```

2) After manually putting turbo.json from monorepo's root to sub-package:

```
=> ERROR [pruner 3/3] RUN turbo prune --scope=@mycoolproject/pack6 --docker                                0.7s
------
 > [pruner 3/3] RUN turbo prune --scope=@mycoolproject/pack6 --docker:
#9 0.459 2022/07/19 15:35:08 [WARNING] Did not find "packageManager" in your package.json. Please run "npx @turbo/codemod add-package-manager"
#9 0.600 2022/07/19 15:35:09 [WARNING] Did not find "packageManager" in your package.json. Please set the "packageManager" field to your package.json
#9 0.714 2022/07/19 15:35:09 [WARNING] Did not find "packageManager" in your package.json. Please run "npx @turbo/codemod add-package-manager"
#9 0.714 2022/07/19 15:35:09 [WARNING] Did not find "packageManager" in your package.json. Please run "npx @turbo/codemod add-package-manager"
#9 0.714  ERROR  could not construct graph: could not determine package manager. Please set the "packageManager" property in your root package.json (https://nodejs.org/api/packages.html#packagemanager) or run `npx @turbo/codemod add-package-manager` in the root of your monorepo.
------
executor failed running [/bin/sh -c turbo prune --scope=${SCOPE} --docker]: exit code: 1
```

3) After adding the "packageManager" option into the package.json:

```
=> ERROR [pruner 3/3] RUN turbo prune --scope=@mycoolproject/pack6 --docker                                0.6s
------
 > [pruner 3/3] RUN turbo prune --scope=@mycoolproject/pack6 --docker:
#9 0.584  ERROR  could not construct graph: yarn.lock: failed to hash lockfile: open yarn.lock: no such file or directory
------
executor failed running [/bin/sh -c turbo prune --scope=${SCOPE} --docker]: exit code: 1
```

4) After adding the yarn.lock file from monorepo's root to sub-package:

```
 => ERROR [pruner 3/3] RUN turbo prune --scope=@mycoolproject/pack6 --docker                                0.8s
------                                                                                                       
 > [pruner 3/3] RUN turbo prune --scope=@mycoolproject/pack6 --docker:                                           
#9 0.676  ERROR  could not construct graph: could not detect workspaces: package.json: no workspaces found. Turborepo requires Yarn workspaces to be defined in the root package.json
------
executor failed running [/bin/sh -c turbo prune --scope=${SCOPE} --docker]: exit code: 1
```

5) After adding the workspaces from monorepo root's package.json:

```
=> ERROR [pruner 3/3] RUN turbo prune --scope=@mycoolproject/pack6 --docker                                1.4s
------
 > [pruner 3/3] RUN turbo prune --scope=@mycoolproject/pack6 --docker:
#9 1.152 panic: runtime error: invalid memory address or nil pointer dereference
#9 1.152 [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7d4121]
#9 1.152 
#9 1.152 goroutine 1 [running]:
#9 1.152 turbo/internal/prune.(*PruneCommand).Run(0xc000059850, {0xc00001e0a0, 0x2, 0x2})
#9 1.152        turbo/internal/prune/prune.go:110 +0x3a1
#9 1.153 github.com/mitchellh/cli.(*CLI).Run(0xc00012b900)
#9 1.153        github.com/mitchellh/cli@v1.1.2/cli.go:262 +0x5f8
#9 1.153 main.main.func7({0x0, 0x8d6360}, {0xc00001e090, 0x819510, 0x3}, {0x0, 0xc00000e020}, {0x0, 0x0}, 0xc00012b900, ...)
#9 1.153        turbo/cmd/turbo/main.go:154 +0x385
#9 1.153 main.main()
#9 1.153        turbo/cmd/turbo/main.go:159 +0x9e9
------
executor failed running [/bin/sh -c turbo prune --scope=${SCOPE} --docker]: exit code: 2
```

If you manage to successfully build 'em all then most of the containers crash because they won't find the turbo module even if it gets globally installed during container's initial build phase, and they'll report the following message:

![image](https://user-images.githubusercontent.com/37586977/179798858-6f139b93-4076-42ab-8993-e75022f16862.png)

Furthermore, the build on a Linux machine works with both v1.1.2 which is the one we currently use to run it and the latest one.

### Expected Behavior

A full-fledged running build is expected to be made with each docker container to be running flawlessly (which happens on a Linux machine).

### To Reproduce

One of the Docker files the project is using to build the packages:

![image](https://user-images.githubusercontent.com/37586977/180003088-14585c98-b067-494f-ae1e-39cf6b7e12e9.png)

**Comment by DLesage25** [comment] 2022-09-12 19:37
I'm seeing the same issue on an M1. Any update on this?

**Comment by chris-olszewski** [comment] 2022-09-21 19:42
Does someone have a full repro that they can share? I've been trying to repro on my M1 and have been unsuccessful.

Also might be worthwhile checking out the [with-docker](https://github.com/vercel/turborepo/tree/main/examples/with-docker) example project for comparison.

**Comment by nathanhammond** [comment] 2022-09-22 02:47
@LuxuryPanda et al.: I hypothesize that at least there is one possible thing contributing:

1. We have a post-install step in `turbo` which rewrites `node_modules/.bin/turbo`: https://github.com/vercel/turborepo/blob/main/packages/turbo/package.json#L11
2. This is possibly putting your host os/architecture binary into the docker container

Which could explain this random note:
> Furthermore, the build on a Linux machine works with both v1.1.2 which is the one we currently use to run it and the latest one.

If it is a binary, can you get me the first few bytes of the file from a hex editor (e.g. hex fiend) so we can confirm platform?
<img width="1188" alt="Screen Shot 2022-09-22 at 10 45 59 AM" src="https://user-images.githubusercontent.com/20542/191647011-9474195c-7635-4448-b7f4-c995e7d497ca.png">

**Comment by LuxuryPanda** [comment] 2022-09-23 08:27
I checked the file you pointed out and it isn't a binary, just a plain text file as the original one: 
https://github.com/vercel/turborepo/blob/main/packages/turbo/bin/turbo

**Comment by LuxuryPanda** [comment] 2022-09-27 09:10
This is how I see the file on both Windows and M1, pre and post build:

<img width="1124" alt="screenshot" src="https://user-images.githubusercontent.com/37586977/192484921-b9ff6b3a-c533-4310-8bdc-af4871d99e01.png">

**Comment by ghoshanjega** [comment] 2022-10-02 15:23
@chris-olszewski I see this error here https://github.com/ghoshanjega/party/actions/runs/3168910709/jobs/5160454378#step:5:221

**Comment by GoldStrikeArch** [comment] 2023-02-05 20:39
Any update on this one?

**Comment by GoldStrikeArch** [comment] 2023-02-06 19:30
@LuxuryPanda did you fixed the issue?

**Comment by lailo** [comment] 2023-03-16 13:50
Any update on this one?

**Comment by r4881t** [comment] 2023-04-29 14:43
Any update on this?

**Comment by DanielRaj1610** [comment] 2023-06-12 04:42
Facing a similar issue while running prune command 

`RUN turbo prune --scope=dashboard`

`#0 0.778  ERROR  could not construct graph: 1 error occurred:
#0 0.778        * unable to parse yaml: mapping values are not allowed in this context at line 14 column 15
#0 0.778
#0 0.778
#0 0.778 Turbo error: could not construct graph: 1 error occurred:
#0 0.778        * unable to parse yaml: mapping values are not allowed in this context at line 14 column 15
#0 0.778
#0 0.778
------
failed to solve: process "/bin/sh -c turbo prune --scope=${APP_SCOPE}" did not complete successfully: exit code: 1`

**Comment by jrdn91** [comment] 2023-10-18 14:50
Getting this same issue when using pnpm, can verify that there is in fact a `packageManager` property in the root package.json file with `pnpm@7.18.1` as it's value but the prune command continually says that I'm missing this for some reason.

Made sure to prune the builder cache to make sure that it's not cacheing an old version of the root package.json that maybe didn't have this prop but I still receive the error

**Comment by chris-olszewski** [comment] 2024-02-08 23:28
Closing this issue as it has become a dumping ground for various Docker related issues and a lot has changed since it was opened.

If you encounter an issue similar to ones described in this issue with `1.12.3` or higher, then please open a new issue. If you can provide a reproduction, then it will greatly help our ability to help as these issues are usually configuration related.

**Closed by chris-olszewski** 2024-02-08 23:28 UTC
Labels: kind: bug, owned-by: turborepo, area: prune
