### ISSUE TITLE
[WEB-828] [turborepo] "Error: Cannot find module 'next/babel'

### ISSUE THREAD

**Issue by avwie** [vercel/turbo#4408] opened 2023-03-31 11:39 UTC
### What version of Turborepo are you using?

1.8.8

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

ESLint is not working in the most trivial test case of the tutorial on the website in latest WebStorm.

### Expected Behavior

Working ESLint configuration

### To Reproduce

- Open Webstorm, latest version
- Follow the TurboRepo tutorial
- Open _any_ '.tsx' or '.ts' fole
- ESLint: Error: Cannot read config file: .....

```
rror: Cannot read config file: /Users/avanwieringen/Development/private/my-turborepo/packages/eslint-config-custom/index.js
Error: Cannot find module 'next/babel'
Require stack:
- /Users/avanwieringen/Development/private/my-turborepo/packages/eslint-config-custom/index.js
- /Users/avanwieringen/Development/private/my-turborepo/node_modules/.pnpm/@eslint+eslintrc@0.4.3/node_modules/@eslint/eslintrc/lib/config-array-factory.js
- /Users/avanwieringen/Development/private/my-turborepo/node_modules/.pnpm/@eslint+eslintrc@0.4.3/node_modules/@eslint/eslintrc/lib/index.js
- /Users/avanwieringen/Development/private/my-turborepo/node_modules/.pnpm/eslint@7.32.0/node_modules/eslint/lib/cli-engine/cli-engine.js
- /Users/avanwieringen/Development/private/my-turborepo/node_modules/.pnpm/eslint@7.32.0/node_modules/eslint/lib/cli-engine/index.js
- /Users/avanwieringen/Development/private/my-turborepo/node_modules/.pnpm/eslint@7.32.0/node_modules/eslint/lib/api.js
- /Users/avanwieringen/Library/Application Support/JetBrains/Toolbox/apps/WebStorm/ch-0/223.8836.50/WebStorm.app/Contents/plugins/javascript-impl/languageService/eslint/bin/eslint-common.js
- /Users/avanwieringen/Library/Application Support/JetBrains/Toolbox/apps/WebStorm/ch-0/223.8836.50/WebStorm.app/Contents/plugins/javascript-impl/languageService/eslint/bin/eslint-plugin.js
- /Users/avanwieringen/Library/Application Support/JetBrains/Toolbox/apps/WebStorm/ch-0/223.8836.50/WebStorm.app/Contents/plugins/javascript-impl/languageService/eslint/bin/eslint-plugin-provider.js
- /Users/avanwieringen/Library/Application Support/JetBrains/Toolbox/apps/WebStorm/ch-0/223.8836.50/WebStorm.app/Contents/plugins/javascript-impl/jsLanguageServicesImpl/js-language-service.js
Referenced from: /Users/avanwieringen/Development/private/my-turborepo/apps/docs/.eslintrc.js
```

<sub>[WEB-828](https://linear.app/vercel/issue/WEB-828/[turborepo]-error-cannot-find-module-nextbabel)</sub>

**Comment by NicholasLYang** [comment] 2023-03-31 22:16
Duplicate of #4348

**Closed by NicholasLYang** 2023-03-31 22:16 UTC
Labels: kind: bug, pkg: create-turbo, area: turborepo
