### ISSUE TITLE
[turborepo] Next.js13 and tailwind do not have proper loader

### ISSUE THREAD

**Issue by hamidre13** [vercel/turbo#4307] opened 2023-03-22 20:04 UTC
### What version of Turborepo are you using?

1.8

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Mac

### Describe the Bug

I have a turborepo project and upgraded to next.js13. I do have tailwind as my CSS library. After creating app directory and adding the tailwind CSS import in the root layout.tsx I am getting this error:
`web:dev: error - ./styles/tailwind.scss
web:dev: Module parse failed: Unexpected character '@' (1:0)
web:dev: You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
web:dev: > @tailwind base;
web:dev: | @tailwind components;
web:dev: | @tailwind utilities;`

### Expected Behavior

application compiles and run without loader error compiles

### To Reproduce

simply add tailwind css to nextjs 13 and turborepo in app directory

**Comment by chris-olszewski** [comment] 2023-03-22 22:40
Hi @hamidre13, the error you linked could be due to a Turbo configuration problem, but it's hard to debug without the exact configuration. Could you provide a repo with a reproduction?

**Comment by engrwaqasali** [comment] 2023-03-23 08:55
facing the same loader issue when starting a new project with 

`npx degit vercel/turbo/examples/with-yarn with-yarn`

and simply cannot run the project with yarn dev

i reported the issue cannot start new project
[4316](https://github.com/vercel/turbo/issues/4316)

**Comment by hamidre13** [comment] 2023-03-24 20:25
Thanks @chris-olszewski , 

Here is my web tsconfig web file:
```{
  "extends": "tsconfig/nextjs.json",
  "include": [
    "next-env.d.ts",
    "**/*.ts",
    "**/*.tsx",
    ".next/types/**/*.ts"
  ],
  "exclude": [
    "node_modules"
  ],
  "compilerOptions": {
    "baseUrl": ".",
    "plugins": [
      {
        "name": "next"
      }
    ]
  }
}
```

Here is the next tsconfig:
```
{
  "$schema": "https://json.schemastore.org/tsconfig",
  "display": "Next.js",
  "extends": "./base.json",
  "compilerOptions": {
    "target": "es5",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "incremental": true,
    "esModuleInterop": true,
    "module": "esnext",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve"
  },
  "include": ["src", "next-env.d.ts"],
  "exclude": ["node_modules"]
}

```

here is my base tsconfig:
```
{
  "$schema": "https://json.schemastore.org/tsconfig",
  "display": "Default",
  "compilerOptions": {
    "composite": false,
    "declaration": true,
    "declarationMap": true,
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "inlineSources": false,
    "isolatedModules": true,
    "moduleResolution": "node",
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "preserveWatchOutput": true,
    "skipLibCheck": true,
    "strict": true
  },
  "exclude": ["node_modules"]
}

```

Here is a turbo confing:
```
{
  "$schema": "https://turbo.build/schema.json",
  "pipeline": {
    "build": {
      "dependsOn": [
        "^build"
      ],
      "outputs": [
        "dist/**",
        ".next/**"
      ]
    },
    "lint": {
      "outputs": []
    },
    "dev": {
      "cache": false
    }
  },
  "globalEnv": [
    "ALGOLIA_APPLICATION_ID",
    "ALGOLIA_ADMIN_KEY",
    "SENDGRID_API_KEY",
    "NEXT_PUBLIC_ALGOLIA_API_KEY",
    "NEXT_PUBLIC_ALGOLIA_APP_ID"
  ],
  "globalDependencies": [
    ".env"
  ]
}
```

I did not change any cofigs, so I am pretty sure any fresh install will have this issue, but I will be happy to create a repo if necessary.

**Comment by hamidre13** [comment] 2023-04-07 22:00
@chris-olszewski  Please let me know if you need any help with this. I will be happy to help

**Comment by jasonduffus** [comment] 2023-04-17 00:30
Is there a fix for this yet? I am running into the same issue and I have a demo to due incorporating a design system with Tailwind.

**Comment by anthonyshew** [comment] 2024-03-12 11:43
Hey, folks, looks to be a stale here! There's been a lot of work put into the examples so this should be fixed. Please open a new issue if you're still seeing problems.

**Closed by anthonyshew** 2024-03-12 11:43 UTC
Labels: kind: bug, needs: reproduction, needs: author input, owned-by: turborepo
