### ISSUE TITLE
Apps using ESLint config package using stale version

### ISSUE THREAD

**Issue by NicHaley** [vercel/turbo#938] opened 2022-03-24 21:56 UTC
### What version of Turborepo are you using?

1.1.10

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Mac

### Describe the Bug

I am sharing an ESLint config between different apps / packages using Turborepo. My apps / packages are able to consume the linting configuration, but are stuck on a stale version. I have tried cleaning my directories (ie. `rm -rf .turbo && rm -rf node_modules`), as well as making new updates, but the apps always reference the outdated file.

The only way I am able to use new updates is by creating a new distribution file for my ESLint config and referencing that instead.

Here is a simplified version of my code:

packages/eslint-config/package.json
```
{
  "name": "@my-org/eslint-config",
  "version": "1.0.0-beta.1",
  "description": "",
  "main": "index.js",
  "files": [
    "base.js",
    "base2.js",
    "react.js"
  ],
  "scripts": {
    "clean": "rm -rf .turbo && rm -rf node_modules"
  },
  "devDependencies": {
    ...
  },
  "peerDependencies": {
      ...
  }
}

```

packages/eslint-config/base.js
```
module.exports = { ... }
```

packages/eslint-config/base2.js
```
module.exports = { ... }
```

packages/my-library/package.json
```
{
  "version": "0.1.0",
  "license": "MIT",
  "main": "dist/index.js",
  "typings": "dist/index.d.ts",
  "files": [
    "dist",
    "src"
  ],
  "scripts": {
     ...
    "clean": "rm -rf .turbo && rm -rf node_modules"
  },
  "name": "@my-org/my-library",
  "module": "dist/dom-js.esm.js",
  "dependencies": {
    ...
  },
  "devDependencies": {
    "@my-org/eslint-config": "*",
    ...
  }
}
```

packages/my-library/.eslintrc.js
```
// Doesn't work
module.exports = {
  ...require("@my-org/eslint-config/base");
};

// Works (using newly created base file)
module.exports = {
  ...require("@my-org/eslint-config/base2");
};

```

In the example above, the `base2` config, which was newly created, works and uses the correct config. The old `base` config is stale and cannot be updated.

### Expected Behavior

The eslint config should be up to date.

### To Reproduce

You can use the snippets above to try and reproduce.

**Comment by NicHaley** [comment] 2022-04-11 16:17
UPDATE:

I still haven't figured out the fix, but I have a bit more info about the problem. It appears my monorepo root `node_modules` is using the correct "symlink" version. However, the `node_modules` directory inside my packages is using an outdated version.

**Comment by christianalares** [comment] 2022-09-01 09:05
> UPDATE:
> 
> I still haven't figured out the fix, but I have a bit more info about the problem. It appears my monorepo root `node_modules` is using the correct "symlink" version. However, the `node_modules` directory inside my packages is using an outdated version.

Just found this issue. I haven't experienced the same problems as you but did you try using the `extends` instead of requiring the whole file in there? I have the same setup as you except in one of my apps where i want to consume the config I do this instead:
```
module.exports = {
  extends: ["@my-org/eslint-config/base"],
  ...
};
```

**Comment by tknickman** [comment] 2023-11-24 15:45
Hey all, we're revamping our eslint handling in our examples / docs now. This particular issues seems like it's specific to your eslint setup, and not caused by Turborepo. Going to close this one out, but if you're still seeing issues with our latest lint let us know!

**Closed by tknickman** 2023-11-24 15:45 UTC
Labels: kind: bug, area: caching, needs: triage, owned-by: turborepo
