### ISSUE TITLE
Run script in app/package without definining it in turbo.json

### ISSUE THREAD

**Issue by MickL** [vercel/turbo#7432] opened 2024-02-20 12:53 UTC
### Which project is this feature idea for?

Turborepo

### Describe the feature you'd like to request

I would like to be able to execute a script from an app/package without it being defined in `turbo.json`:

```
turbo run drizzle:push --filter=database
```

In Lerna this is possible:
```
lerna run build --scope=header
```

But in Turbo I need to define this script in the pipeline which I dont want because it is a very unique script

### Describe the solution you'd like

Allow running scripts without defining them in `turbo.json`

### Describe alternatives you've considered

-

**Comment by anthonyshew** [comment] 2024-02-20 14:58
Closing as duplicate of #4549. In the future, please be more conscientious about searching for duplicates before opening issues as we were also able to close #7433 as a duplicate as well. If you do want to express your interest about an existing issue, you can do so by adding a thumbs up reaction to it.

**Closed by anthonyshew** 2024-02-20 14:58 UTC
Labels: story, owned-by: turborepo

**Comment by MickL** [comment] 2024-02-20 15:29
I was looking for duplicated for a long time but I didnt found them. E.g. the other issue doesnt have the search terms "cli prompt" in it and this one doesnt have "run script". I guess its good because other people migh find this issue that then links to the other one.

**Comment by anthonyshew** [comment] 2024-02-20 16:18
No problem! Was definitely deep in the archives. 😄

This also made me realize that I had some things to clean up around feature requests and how we now want to handle them on the core team so thank you! Getting those cleaned up in https://github.com/vercel/turbo/pull/7435
