### ISSUE TITLE
Unexpected script run

### ISSUE THREAD

**Issue by 19Qingfeng** [vercel/turbo#1890] opened 2022-09-08 16:51 UTC
### What version of Turborepo are you using?

1.4.6

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

I encountered an unexpected script run.

As the example in the documentation, I redefine turpo.json:

```json
{
  "$schema": "https://turborepo.org/schema.json",
  "pipeline": {
    "build": {
      "dependsOn": ["test", "lint"],
      "outputs": ["dist/**", ".next/**"],
      "cache": false
    },
    "lint": {
      "dependsOn": []
    },
    "test": {
      "dependsOn": []
    },
    "dev": {
      "cache": false
    }
  }
}
```

When I do npm run build , something unexpected happens. The lint of the UI will be executed, but the UI does not have build scripts,Although the UI is relied upon by other applications.

### Expected Behavior

UI does not define a build script and should not execute UI's lint command.

### To Reproduce

in this repo: https://github.com/19Qingfeng/turo-bug-report.

you can run `pnpm install` and `pnpm build`,then you can get:

<img width="914" alt="image" src="https://user-images.githubusercontent.com/31119562/189180478-a30a6207-5186-4df4-bca1-eaf36799ade3.png">

**Comment by mehulkar** [comment] 2023-12-09 07:06
This is expected behavior and a duplicate of https://github.com/vercel/turbo/issues/937. I recently added some docs to explain why this is expected: https://turbo.build/repo/docs/core-concepts/monorepos/task-graph#transit-nodes

**Closed by mehulkar** 2023-12-09 07:06 UTC
Labels: needs: triage, owned-by: turborepo
