### ISSUE TITLE
expo debugger not working if server start from root(only windows OS)

### ISSUE THREAD

**Issue by FedeRBeije** [vercel/turbo#8700] opened 2024-07-09 10:34 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

no link

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Windows

### Which canary version will you have in your reproduction?

turbo@2.0.7-canary.0

### Describe the Bug

When, from the root of the project i run a task for a expo app and then i try (with the new terminal'ui and features) to press **_j_** to open the (chrome devtools) for debugging, the command fail with:
![image](https://github.com/vercel/turbo/assets/108535310/c974c343-b3f3-43cc-860c-ffd9e53a212b)

If i do the same but inside project folder, the debugger works fine.

This happen only in windows system.
using - windows 11 pro 64 bit

### Expected Behavior

Chrome devtools should work without problems.

### To Reproduce

init an expo project and then try to use the dubber by running app from monorepo'root project.

**Comment by anthonyshew** [comment] 2024-07-09 12:03
Hey, thanks for the issue!

I'd like to quickly check if this has to do with package management or Expo itself. Are you able to successfully run this outside of `turbo` in your monorepo? As in, with a root script that calls the script command directly?

**Comment by anthonyshew** [comment] 2024-07-09 12:04
Alternatively, a link to a reproduction would be the most helpful!

**Comment by FedeRBeije** [comment] 2024-07-09 16:00
> Hey, thanks for the issue!
> 
> I'd like to quickly check if this has to do with package management or Expo itself. Are you able to successfully run this outside of `turbo` in your monorepo? As in, with a root script that calls the script command directly?

Sorry, i expressed myself badly. Yes if i not use `turbo` everything works fine.

**Comment by FedeRBeije** [comment] 2024-07-09 16:30
@anthonyshew i'll reply to you tomorrow as right now i do not have a windows laptop available for try it.

**Comment by FedeRBeije** [comment] 2024-07-10 08:02
So we tried and it's work. Thank you @anthonyshew.

Can i just ask you what --env-mode does?

**Comment by anthonyshew** [comment] 2024-07-10 12:01
Docs are here: https://turbo.build/repo/docs/crafting-your-repository/using-environment-variables#loose-mode

Glad you're unblocked! I'm going to re-open this as a reminder to myself to see if we can come up with a better default for this case. 👍

**Comment by FedeRBeije** [comment] 2024-07-11 07:22
So as that part of docs suggest, it could be that some time i'm living hell with expo(with expo-router) project because some expo env vars are not founded because of this -env-mode?

@anthonyshew  do you think could be related?

**Comment by anthonyshew** [comment] 2024-07-11 18:51
Under Strict Mode, only variables you've listed as passthroughs or in `env` or `globalEnv` would be available in the task runtime, so they would appear to be missing when your scripts are ran through `turbo`. Does that answer your question?

**Comment by FedeRBeije** [comment] 2024-07-12 08:46
Note sure, it's quite difficult even to understand why for me. I can tell that is happening only inside turborepo project but also when running command directly from app(always inside turborepo'mono) without using turbo it gives that problem. I don't understand why sometime all works fine and sometime not. Adding a package into the repo (expo project's) it's always scary 'couse i never know if the problem will come again or not. I tried to add expo envs var like u told me and as doc but looks like is not working.

```json
  "globalPassThroughEnv": ["EXPO_ROUTER_APP_ROOT", "EXPO_ROUTER_IMPORT_MODE"],
```

**Comment by anthonyshew** [comment] 2024-07-12 20:57
>  I can tell that is happening only inside turborepo project but also when running command directly from app(always inside turborepo'mono) without using turbo

This indicates that the issue isn't related to Turborepo, but rather with Expo. If the scripts don't work right when ran without `turbo` involved, then Turborepo isn't involved in the failure.

I've heard of other folks having similar-sounding issues with Expo dependency resolution in monorepos, so you might have better luck looking for answers in Expo-specific communities.

**Comment by anthonyshew** [comment] 2024-07-31 14:48
Going to close this as it appears to be an Expo bug rather than Turborepo.

**Closed by anthonyshew** 2024-07-31 14:48 UTC
Labels: kind: bug, owned-by: turborepo
