### ISSUE TITLE
unable to setup tls windows 11

### ISSUE THREAD

**Issue by wanghaisheng** [vercel/turbo#8512] opened 2024-06-16 04:13 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

https://github.com/jaspreet-singh-96/test-repo

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Windows

### Which canary version will you have in your reproduction?

2.0.3

### Describe the Bug

$ turbo run dev  --output-logs=full
  × Failed to create APIClient: Unable to
  │ set up TLS.
  ├─▶ Unable to set up TLS.
  ├─▶ builder error: 拒绝访问。 (os error  
  │   5)
  ╰─▶ 拒绝访问。 (os error 5)

try https://github.com/vercel/turbo/issues/7957
failled

try to use https://github.com/vercel/turbo/issues/8330 ,but cargo test failed 

### Expected Behavior

should work

### To Reproduce

turbo run dev

**Comment by anthonyshew** [comment] 2024-06-16 04:42
Duplicate of #8493

**Closed** 2024-06-16 04:42 UTC
Labels: kind: bug, needs: triage, owned-by: turborepo
