### ISSUE TITLE
[turborepo] Hashing error: cannot find package-file hash for package

### ISSUE THREAD

**Issue by abrisco** [vercel/turbo#4885] opened 2023-05-10 14:39 UTC
### What version of Turborepo are you using?

1.9.3

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

When I build incrementally, I run into the following error:
```
Hashing error: cannot find package-file hash for package#!.next/!!coverage/**!!dist/**!!next-env.d.ts!!node_modules/**!**/*.js*!**/*.js*!**/*.jsx!**/*.ts!**/*.tsx!.env*!prisma/schema.prisma!tsconfig*.json
```

It's triggered for seemingly random packages in my monorepo but that could just be the execution order of tasks being different and I'm running into the same subset of broken tasks just in different orders. Nuking the `node_modules/.cache` directory gets me building again. This is reproducible without using remote caching

### Expected Behavior

I expect to be able to run tasks incrementally without issue.

### To Reproduce

It seems simply running incrementally leads to this failure. Below is my `turbo.json` file. My `build` tasks are just `"build": "tsc"`, `test` is `"test": "jest"` and `image` is a docker build script which runs `turbo prune` to gather files that should go in the docker image being built. My theory is that running turbo recursively is what's leading to the issue.

```json
{
  "$schema": "https://turbo.build/schema.json",
  "pipeline": {
    "//#coverage": {
      "dependsOn": ["//#package-deps", "@example/lcov-merger#build"],
      "inputs": ["!**/node_modules/**", "**/coverage/lcov.info"],
      "outputMode": "new-only",
      "outputs": ["coverage/_coverage_report.dat"]
    },
    "//#package-deps": {
      "inputs": [
        ".npmignore",
        ".npmrc",
        ".nvmrc",
        "apps/*/*/package.json",
        "apps/*/package.json",
        "packages/*/*/package.json",
        "packages/*/*/prisma/schema.prisma",
        "pnpm-lock.yaml",
        "pnpm-workspace.yaml",
        "tools/*/package.json"
      ],
      "outputMode": "new-only",
      "outputs": ["pnpm-lock.yaml"]
    },
    "build": {
      "dependsOn": ["//#package-deps", "^build"],
      "inputs": [
        "!.next/**",
        "!.vercel/**",
        "!coverage/**",
        "!dist/**",
        "!next-env.d.ts",
        "!node_modules/**",
        ".env*",
        "**/*.js",
        "**/*.jsx",
        "**/*.ts",
        "**/*.tsx",
        "prisma/schema.prisma",
        "tsconfig*.json"
      ],
      "outputMode": "new-only",
      "outputs": [".vercel/output/**", ".next/**", "!.next/cache/**", "dist/**"]
    },
    "image": {
      "dependsOn": ["//#package-deps", "build", "@example/docker#build"],
      "inputs": [
        ".dockerignore",
        ".env*",
        "dist/**",
        "Dockerfile*"
      ],
      "outputMode": "new-only"
    },
    "format": {
      "dependsOn": ["//#package-deps", "eslint-config-example#build"],
      "outputMode": "new-only"
    },
    "lint": {
      "dependsOn": ["//#package-deps", "eslint-config-example#build"],
      "inputs": [
        "!.next/**",
        "!.vercel/**",
        "!coverage/**",
        "!dist/**",
        "!next-env.d.ts",
        "!prisma/**",
        ".eslint*",
        "**/*.js",
        "**/*.jsx",
        "**/*.ts",
        "**/*.tsx"
      ],
      "outputMode": "new-only"
    },
    "test": {
      "dependsOn": ["//#package-deps", "build"],
      "inputs": [
        "!.next/**",
        "!.vercel/**",
        "!coverage/**",
        "!dist/**",
        "!next-env.d.ts",
        "!prisma/**",
        ".env*",
        "**/*.js",
        "**/*.json",
        "**/*.jsx",
        "**/*.ts",
        "**/*.tsx",
        "**/Dockerfile*"
      ],
      "outputMode": "new-only",
      "outputs": ["coverage/lcov.info"]
    }
  }
}

```

**Comment by chris-olszewski** [comment] 2023-05-10 16:12
That's a very odd message as it looks like somehow input/output globs are clobbering the task name. The one thing that I'm wondering about your setup is the `image` task. Where do you have `turbo prune` output directory setup? Turbo doesn't support nested workspaces and if your `pnpm-workspace.yaml` includes the prune output directory bad things could happen. Could you also quick `grep -F '!.next/!!coverage/**!!dist/**!!next-env.d.ts!!node_modules/**!**/*.js*!**/*.js*!**/*.jsx!**/*.ts!**/*.tsx!.env*!prisma/schema.prisma!tsconfig*.json'` and verify that there's not some rogue `package.json` with a wild name?

**Comment by abrisco** [comment] 2023-05-10 16:46
I don't think I have any control over where `turbo prune` outputs it. I tried to use an absolute path to a temp directory but it instead rendered to a relative path from the root of the repo. Because turbo seems to be forcing me to write to the repo, I delete it after the image is built. Ideally I'd be able to use absolute paths to a temp directory though. Should I file a separate issue for this?

I ran `grep -F '!.next/!!coverage/**!!dist/**!!next-env.d.ts!!node_modules/**!**/*.js*!**/*.js*!**/*.jsx!**/*.ts!**/*.tsx!.env*!prisma/schema.prisma!tsconfig*.json'` and it came up with nothing 😞

**Comment by chris-olszewski** [comment] 2023-05-10 17:39
> I tried to use an absolute path to a temp directory but it instead rendered to a relative path from the root of the repo

Ah yeah, that's a bug and I can quick get a fix up for that. A temporary work around can be use of `../`. Is there a reason why you're pruning as part of a turbo task instead of pruning the project as part of the `Dockerfile`?

> it came up with nothing

Thanks for checking, wasn't expecting anything would come of that, but figured it was worth a shot. 

Am I understanding correctly that once you hit the error you're unable to build until you clear `node_modules/.cache`?

**Comment by abrisco** [comment] 2023-05-11 05:32
> Is there a reason why you're pruning as part of a turbo task instead of pruning the project as part of the `Dockerfile`?

I want to be able to benefit from work that was already done in other tasks. Instead of building everything then attempting to build everything again and having to deal with multiple different kinds of caching, I want my docker images to be dumb and just copy in things built in previous tasks. The outputs of tasks are platform agnostic so I don't see why I would need to repeat this work. I did notice that the [suggested workflow](https://turbo.build/repo/docs/handbook/deploying-with-docker) is to build in a Dockerfile but I feel this is unnecessary and clunky. I want users and CI to verify any change to the entire repo by simply running `turbo run lint test image`. If this passes, then the changes is good and we can merge or deploy and we can avoid complicated multi-stage build pipelines or having someone author a `ci.sh` script that would do the repo-wide verification. Do you feel this is going against-the-grain in some way?

> Am I understanding correctly that once you hit the error you're unable to build until you clear `node_modules/.cache`?

Yeah, then I'm able to try building again, and usually make it through the first build, but the second or some subsequent one fails.

**Comment by abrisco** [comment] 2023-05-11 13:46
> Ah yeah, that's a bug and I can quick get a fix up for that. A temporary work around can be use of `../`.

I just tried this and it unfortunately doesn't seem to fix the issue. I'm able to write the outputs of `turbo prune` outside the directory but I still run into:
```
Hashing error: cannot find package-file hash for package#!.next/!!coverage/**!!dist/**!!next-env.d.ts!!node_modules/**!**/*.js*!**/*.js*!**/*.jsx!**/*.ts!**/*.tsx!.env*!prisma/schema.prisma!tsconfig*.json
```

**Comment by jakeleventhal** [comment] 2023-05-12 19:39
This can likely close now with https://github.com/vercel/turbo/releases/tag/v1.9.5-canary.0 being released

**Comment by abrisco** [comment] 2023-05-12 23:40
I don't think this is true. Moving the output directory out of the repo still leads to the hashing issue 😞

**Comment by chris-olszewski** [comment] 2023-05-15 13:18
@abrisco Is there any way you could provide a reproduction repo for me? I haven't been able to trigger this behavior from the `turbo.json` you provided.

**Comment by anthonyshew** [comment] 2024-04-06 15:33
Closing due to staleness and lack of reproduction.

**Closed by anthonyshew** 2024-04-06 15:33 UTC
Labels: kind: bug, needs: reproduction, owned-by: turborepo
