### ISSUE TITLE
[Turbopack] Error during SSR Rendering

### ISSUE THREAD

**Issue by is-it-ayush** [vercel/turbo#2479] opened 2022-10-29 02:10 UTC
### What version of Turbopack are you using?

4.7.4

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Windows

### Describe the Bug

When running the `yarn run dev` or `npm run dev` on the default turbopack `npx create-next-app --example with-turbopack` example. The app randomly crashes and produces the following the error:
```
error - [rendering] [root of the dev server]/hooks  Error during SSR Rendering
  timed out waiting for the Node.js process to connect
```

### Expected Behavior

The error shouldn't exist as there were no modifications made to any of the files.

### To Reproduce

1.) Use `npx create-next-app --example with-turbopack` and create the app with any name.
2.) Run `yarn install`
3.) Run `yarn dev`.
4.) Now navigate inside the template app. It'll crash producing the error. Randomly.

**Comment by xpadev-net** [comment] 2022-10-29 05:16
A similar error occurred

### What version of Turbopack are you using?
nextjs 13.0.0

### What package manager are you using / does the bug impact?
yarn 1.22.19 / probably no

### What operating system are you using?
win11 21h2 (22000.1098)


### Describe the Bug
When running the yarn run dev or npm run dev on the default turbopack npx create-next-app --example with-turbopack example. The app randomly crashes and produces the following the error:

>error - [rendering] [root of the dev server]/context/clothing
Error during SSR Rendering
timed out waiting for the Node.js process to connect
error - [rendering] [root of the dev server]/context/books
Error during SSR Rendering
timed out waiting for the Node.js process to connect
error - [rendering] [root of the dev server]/context/electronics
Error during SSR Rendering
timed out waiting for the Node.js process to connect
error - [rendering] [root of the dev server]/styling/global-css
Error during SSR Rendering
timed out waiting for the Node.js process to connect

### Expected Behavior

The error shouldn't exist as there were no modifications made to any of the files.

### env
node 16.15.0
yarn 1.22.19
win11 21h2 (22000.1098) / i5-9600K / 16GB

### To Reproduce
1. Use `npx create-next-app --example with-turbopack` and create the app with any name.
2. Run `npm run dev`.
3. The above error occurs rarely when opening the application in a browser

Often crashed on first startup
Also, crashes often occurred when memory usage was high.
![image](https://user-images.githubusercontent.com/96982836/198815240-1a96276e-b0e6-4ce4-a0a8-4b84b5aaa463.png)

**Comment by is-it-ayush** [comment] 2022-10-29 08:47
@xpadev-net let me know of you get turbopack working.

**Comment by m7yue** [comment] 2022-11-03 03:11
> @xpadev-net let me know of you get turbopack working.

node version 16+

**Comment by Sandeep06Dev** [comment] 2022-11-07 17:21
Getting the same issue with  NodeJs v14.17.3

**Comment by dangvanthanh** [comment] 2023-01-18 16:16
The same too with Nodejs `v16.14.2`

**Comment by padmaia** [comment] 2023-05-10 21:40
duplicate of #2352

**Closed by padmaia** 2023-05-10 21:40 UTC
Labels: kind: bug, area: turbopack
