### ISSUE TITLE
[turborepo] Hash always the same on a pruned project 

### ISSUE THREAD

**Issue by lillheaton** [vercel/turbo#4150] opened 2023-03-10 09:48 UTC
### What version of Turborepo are you using?

1.8.4

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Windows

### Describe the Bug

Once you have pruned a project, running turbo tasks ex build, within the pruned ./out folder is always giving the same hash

### Expected Behavior

Same behavior as you have in the root folder, where as soon as you modify your files you get a unique hash.

### To Reproduce

1. Prune project (npx turbo prune --scope=myapp
2. cd ./out
3. Install dependencies (I use npm, so npm ci)
4. turbo run build --filter=myapp --dry=json
5. Modify any file within the pruned app
6. turbo run build --filter=myapp --dry=json - _generates the same hash_

**Comment by arlyon** [comment] 2023-03-10 14:00
Hi! I am able to reproduce it and the answer is luckily straight forward. Turbo will ignore `.gitignore`'d files when calculating input file hashes, and my assumption is that your `out` folder is ignored completely.

If you remove the ignore on the folder (or rename it) everything will go back to normal. I know this is weird and unintuitive, and the least we can do is warn when that is the case.

Let me know if changing the ignore fixes it, and I will look into surfacing a warning when this is the case.

**Comment by lillheaton** [comment] 2023-03-14 13:33
Hey @arlyon! that was indeed the issue. Thank you for clarifying.

**Comment by mehulkar** [comment] 2023-03-17 08:35
Looks like this has been resolved. Closing down, feel free to ping if we need to re-open @lillheaton!

**Closed by mehulkar** 2023-03-17 08:35 UTC
Labels: kind: bug, area: turborepo, area: caching
