### ISSUE TITLE
Vercel not detecting .vercel_build_output (nuxt3) when building with turbo

### ISSUE THREAD

**Issue by mjrobinson86** [vercel/turbo#1123] opened 2022-04-26 18:15 UTC
### What version of Turborepo are you using?

1.2.5

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Mac

### Describe the Bug

Hi there,

Really enjoying working with Turborepo, but I seem to have encountered an issue...

Similar to #208 it would seem that _.vercel_build_output_ output is not re-detected on a cache replay. The issue does not occur when using the --force flag, neither when source has been updated, i.e. results in a cache miss.

I also tried specifying the output directory _.vercel_build_output_ but this didn't seem to have any effect (and should probably be inferred).

### Expected Behavior

Vercel should be able to detect the output directory automatically as it would on a non cache build and complete the deployment.

### To Reproduce

**Vercel settings:**

<img width="767" alt="Screenshot 2022-04-26 at 19 58 26" src="https://user-images.githubusercontent.com/102296883/165362953-7196cf86-5ac7-450b-9ace-4e54b7335545.png">

**NOTE:** Given that Nuxt3 is just reached RC.1 at the time of writing, The nuxt.js preset does not seem appropriate given that the apparent defaults are no longer applicable so I left the preset as other.

**turbo.json (WIP):**

```json
{
    "$schema": "https://turborepo.org/schema.json",
    "baseBranch": "origin/master",
    "pipeline": {
        "dev": {
            "dependsOn": ["^build"],
            "cache": false
        },
        "web#dev": {
            "dependsOn": ["^build", "nuxt-contentful-module#build"],
            "cache": false
        },
        "build": {
            "dependsOn": ["^build"],
            "outputs": ["dist/**"]
        },
        "web#build": {
            "dependsOn": [
                "^build",
                "$CONTENTFUL_GRAPHQL_ENDPOINT",
                "$CONTENTFUL_DELIVERY_API_TOKEN",
                "$CONTENTFUL_PREVIEW_API_TOKEN"
            ],
            "outputs": [".nuxt/**", ".output/**"]
        },
        "lint": {
            "dependsOn": ["^build"]
        },
        "test": {
            "dependsOn": ["^build"]
        }
    }
}
```

**LOG (Without force flag or on cache hit)**

_...OMITTED FOR BREVITY_
[19:51:43.502] web:build: [log] Nuxt CLI v3.0.0-rc.1
[19:51:43.502] web:build: [info] Vite client warmed up in 2743ms
[19:51:43.502] web:build: [info] Client built in 4232ms
[19:51:43.502] web:build: [info] Building server...
[19:51:43.502] web:build: [success] Server built in 1478ms
[19:51:43.502] web:build: [success] [nitro] Generated public .vercel_build_output/static
[19:51:43.503] web:build: [start] [nitro] Building server...
[19:51:43.503] web:build: [start] [nitro] Writing server bundle...
[19:51:43.503] web:build: [success] [nitro] Server built
[19:51:43.503] web:build:   ├─ .vercel_build_output/functions/node/server/package.json (717 B) (338 B gzip)
[19:51:43.503] web:build:   ├─ .vercel_build_output/functions/node/server/index.mjs.map (103 B) (100 B gzip)
[19:51:43.503] web:build:   ├─ .vercel_build_output/functions/node/server/index.mjs (324 B) (194 B gzip)
[19:51:43.503] web:build:   ├─ .vercel_build_output/functions/node/server/chunks/vue3.mjs.map (338 B) (223 B gzip)
[19:51:43.503] web:build:   ├─ .vercel_build_output/functions/node/server/chunks/vue3.mjs (317 B) (226 B gzip)
[19:51:43.503] web:build:   ├─ .vercel_build_output/functions/node/server/chunks/nitro/vercel.mjs.map (14.3 kB) (2.67 kB gzip)
[19:51:43.503] web:build:   ├─ .vercel_build_output/functions/node/server/chunks/nitro/vercel.mjs (12.1 kB) (3.96 kB gzip)
[19:51:43.503] web:build:   ├─ .vercel_build_output/functions/node/server/chunks/index.mjs.map (1.81 MB) (84.1 kB gzip)
[19:51:43.504] web:build:   ├─ .vercel_build_output/functions/node/server/chunks/index.mjs (405 kB) (92.2 kB gzip)
[19:51:43.504] web:build:   ├─ .vercel_build_output/functions/node/server/chunks/handlers/renderer.mjs.map (29.9 kB) (4.8 kB gzip)
[19:51:43.504] web:build:   ├─ .vercel_build_output/functions/node/server/chunks/handlers/renderer.mjs (23.5 kB) (6.51 kB gzip)
[19:51:43.504] web:build:   ├─ .vercel_build_output/functions/node/server/chunks/build/templates.serverMiddleware.a3ac8d10.mjs.map (11.6 kB) (2.5 kB gzip)
[19:51:43.504] web:build:   ├─ .vercel_build_output/functions/node/server/chunks/build/templates.serverMiddleware.a3ac8d10.mjs (15.3 kB) (2.9 kB gzip)
[19:51:43.504] web:build:   ├─ .vercel_build_output/functions/node/server/chunks/app/server.mjs.map (513 kB) (71.4 kB gzip)
[19:51:43.504] web:build:   ├─ .vercel_build_output/functions/node/server/chunks/app/server.mjs (438 kB) (96.7 kB gzip)
[19:51:43.505] web:build:   ├─ .vercel_build_output/functions/node/server/chunks/app/client.manifest.mjs.map (928 B) (325 B gzip)
[19:51:43.505] web:build:   └─ .vercel_build_output/functions/node/server/chunks/app/client.manifest.mjs (1.04 kB) (341 B gzip)
**[19:51:43.505] web:build: Σ Total size: 5.79 MB (1.04 MB gzip)
[19:51:43.505] 
[19:51:43.505]  Tasks:    2 successful, 2 total
[19:51:43.505] Cached:    2 cached, 2 total
[19:51:43.505]   Time:    709ms >>> FULL TURBO
[19:51:43.505] 
[19:51:43.563] Error: No Output Directory named "dist" found after the Build completed. You can configure the Output Directory in your Project Settings. Learn More: https://vercel.link/missing-public-directory**

**LOG (With force flag or on cache miss)**

**_...OMITTED FOR BREVITY_**
[20:09:25.832] web:build: [log] Nuxt CLI v3.0.0-rc.1
[20:09:33.758] web:build: [info] Vite client warmed up in 2947ms
[20:09:35.169] web:build: [info] Client built in 4358ms
[20:09:35.175] web:build: [info] Building server...
[20:09:36.668] web:build: [success] Server built in 1493ms
[20:09:36.689] web:build: [success] [nitro] Generated public .vercel_build_output/static
[20:09:36.705] web:build: [start] [nitro] Building server...
[20:09:43.225] web:build: [start] [nitro] Writing server bundle...
[20:09:43.962] web:build: [success] [nitro] Server built
[20:09:44.674] web:build:   ├─ .vercel_build_output/functions/node/server/package.json (717 B) (338 B gzip)
[20:09:44.676] web:build:   ├─ .vercel_build_output/functions/node/server/index.mjs.map (103 B) (100 B gzip)
[20:09:44.676] web:build:   ├─ .vercel_build_output/functions/node/server/index.mjs (324 B) (194 B gzip)
[20:09:44.677] web:build:   ├─ .vercel_build_output/functions/node/server/chunks/vue3.mjs.map (338 B) (223 B gzip)
[20:09:44.677] web:build:   ├─ .vercel_build_output/functions/node/server/chunks/vue3.mjs (317 B) (226 B gzip)
[20:09:44.677] web:build:   ├─ .vercel_build_output/functions/node/server/chunks/nitro/vercel.mjs.map (14.3 kB) (2.67 kB gzip)
[20:09:44.677] web:build:   ├─ .vercel_build_output/functions/node/server/chunks/nitro/vercel.mjs (12.1 kB) (3.96 kB gzip)
[20:09:44.677] web:build:   ├─ .vercel_build_output/functions/node/server/chunks/index.mjs.map (1.81 MB) (84.1 kB gzip)
[20:09:44.677] web:build:   ├─ .vercel_build_output/functions/node/server/chunks/index.mjs (405 kB) (92.2 kB gzip)
[20:09:44.678] web:build:   ├─ .vercel_build_output/functions/node/server/chunks/handlers/renderer.mjs.map (29.9 kB) (4.8 kB gzip)
[20:09:44.678] web:build:   ├─ .vercel_build_output/functions/node/server/chunks/handlers/renderer.mjs (23.5 kB) (6.51 kB gzip)
[20:09:44.678] web:build:   ├─ .vercel_build_output/functions/node/server/chunks/build/templates.serverMiddleware.a3ac8d10.mjs.map (11.6 kB) (2.5 kB gzip)
[20:09:44.679] web:build:   ├─ .vercel_build_output/functions/node/server/chunks/build/templates.serverMiddleware.a3ac8d10.mjs (15.3 kB) (2.9 kB gzip)
[20:09:44.679] web:build:   ├─ .vercel_build_output/functions/node/server/chunks/app/server.mjs.map (513 kB) (71.4 kB gzip)
[20:09:44.679] web:build:   ├─ .vercel_build_output/functions/node/server/chunks/app/server.mjs (438 kB) (96.7 kB gzip)
[20:09:44.679] web:build:   ├─ .vercel_build_output/functions/node/server/chunks/app/client.manifest.mjs.map (928 B) (325 B gzip)
[20:09:44.679] web:build:   └─ .vercel_build_output/functions/node/server/chunks/app/client.manifest.mjs (1.04 kB) (341 B gzip)
**[20:09:44.679] web:build: Σ Total size: 5.79 MB (1.04 MB gzip)
[20:09:44.723] 
[20:09:44.723]  Tasks:    2 successful, 2 total
[20:09:44.723] Cached:    0 cached, 2 total
[20:09:44.724]   Time:    26.898s 
[20:09:44.724] 
[20:09:45.207] Detected Serverless Functions in ".vercel_build_output"
[20:09:45.207] Detected Static Assets in ".vercel_build_output"
[20:09:45.207] Detected Routes Configuration in ".vercel_build_output"
[20:09:45.831] Uploading build outputs...
[20:09:46.526] Deploying build outputs...
[20:09:50.779] Build completed. Populating build cache...
[20:09:51.169] Uploading build cache [959.04 kB]...
[20:09:51.901] Build cache uploaded: 732.266ms
[20:09:51.920] Done with "package.json"**

**Comment by kenjonespizza** [comment] 2022-05-13 16:43
I, too, am stuck on this issue

**Comment by kenjonespizza** [comment] 2022-05-13 23:59
The solution of [#208](https://github.com/vercel/turborepo/issues/208) solved this for my use case

**Comment by anthonyshew** [comment] 2024-02-05 04:33
It sounds like this is a duplicate of #208 from what I'm seeing. Additionally, the issue is quite old and doesn't have a reproduction.

If you're still having this problem, please do open a fresh issue with a reproduction!

**Closed by anthonyshew** 2024-02-05 04:33 UTC
Labels: area: caching, needs: triage, owned-by: turborepo, area: vercel
